### ISSUE TITLE
WP6 Workshop on Type/Module Systems

### ISSUE THREAD

**Issue by kohlhase** [OpenDreamKit/OpenDreamKit#10]
On the kickoff meeting, we discovered that there is a strong interest in looking at type/module systems of the systems and data bases and how they relate to the OMDoc/MMT Module systems. The vision is that we can combine the the computational semantics from the systems with the deductive semantics in a fine-grained mode.

The workshop is intended to give a forum for looking at the dbs and type systems in detail and possibly start on writing some exporter code. Intended Participants are system/db specialists and students/new hires.

We identified the second half of January as a plausible time frame for the workshop. JacobsUni has offered to organize it, but other nominations for venue are also welcome.

**Comment by williamstein** [comment]
There's a lot of buzzwords I don't understand in the description of this issue (I wasn't at the kickoff meeting).

**Comment by alex-konovalov** [comment]
@kohlhase We have a suggestion for St Andrews as an alternative venue for this workshop. We are currently considering an opportunity to run the 1st Joint GAP-SageMath days in St Andrews from Monday January 18th till Friday January 22nd. In this case, we could run the WP6 workshop immediately prior of after that, assuming that some project partners would be interested to participate in both events.

**Comment by pdehaye** [comment]
I do not care so much about the venue, and that time in January seems appropriate. However I would need to know quickly as exams are to be scheduled around that time. 
I will not be at the GAP-SageMath days.

**Comment by VivianePons** [comment]
I would be available prior the to the Gap-SageMath Days if you do plan the
OpenMath meeting at these dates (and I'm indeed really interested). I won't
attend GAP-SageMath but I am in favor of joining events as it is better for
finances and foster collaborations.

Best

Viviane

2015-09-11 11:37 GMT+02:00 pdehaye <notifications@github.com>:

**Comment by JohnCremona** [comment]
I might be able to get to St Andrews for the second half of that week, as
my teaching schedule is concentrated in the first half (ends 10am
Wednesday).  But the train takes 6-7 hours from here...

John

**Comment by nthiery** [comment]
At this point, basically any time in January is fine for me. I'll try to attend both workshops if they are at the same place, but no promise.

**Comment by alex-konovalov** [comment]
We've by finalised the week for the [1st GAP-SageMath days](http://www.codima.ac.uk/events/) to be January 18th-22nd (Monday to Friday). Regarding the co-location of the two events, it looks like it should be rather immediately after, perhaps starting around Friday lunchtime. In this case, @JohnCremona could hopefully join us from Thursday morning to cover a part of GAP-SageMath days and then the workshop.

**Comment by pdehaye** [comment]
Have the dates been finalized?

**Comment by alex-konovalov** [comment]
The GAP-Sage days website is now http://gapdays.de/gap-sage-days2016/. We will have
* GAP Coding sprint: Wed-Sat January 13-16, 2016
* First Joint GAP-​SageMath Days: Mon-Fri January 18-22, 2016

Hence, the WP6 workhshop will be after that, on Mon-Wed January 25-27, 2016. We are in the process of room(s) booking at the moment.

**Comment by alex-konovalov** [comment]
Just to give an update: I've found the venue for the WP6 workshop for  Monday-Tuesday January 25th and 26th. However, that place is not available for Wednesday January 27th, so I am trying to find another location for Wednesday.

**Comment by JohnCremona** [comment]
I teach Monday-Wednesday so am not likely to be able to come.  There's a
chance I might be able to get someone to take some of my lectures, but I
would have to leave on Wednesday at the latest to be back for Thursday as I
have other commitments all day Thursday 28 and Friday 29.

John

**Comment by kohlhase** [comment]
hmmm, that would be bad, it would be very good to have you there for our discussions.

**Comment by alex-konovalov** [comment]
@JohnCremona thanks - so if there will be a chance that you could manage with lecturing, then you could hopefully be here for Mon-Tue and Wednesday morning?

**Comment by JohnCremona** [comment]
I will certainly try.

**Comment by florian-rabe** [comment]
Sorry, I didn't know this thread existed (which means other relevant people might not know either).

I will attend the workshop, and I thought January 25-27 had been fixed already.

But it doesn't make much sense if the relevant people can't attend. So what is the state here?

**Comment by JohnCremona** [comment]
On 3 December 2015 at 09:34, Florian Rabe <notifications@github.com> wrote:

> Sorry, I didn't know this thread existed (which means other relevant
> people might not know either).
>
> I will attend the workshop, and I thought January 25-27 had been fixed
> already.
>
> But it doesn't make much sense if the relevant people can't attend. So
> what is the state here?
>

If you mean me, I am certainly hoping to, but as I am on leave at the
moment I have not yet been able to ask a colleague to take over my teaching
for those 3 days.  I already have a commitment to be away on the Thursday
and Friday that week (Jan 28-29) and it takes quite a long time to travel
between Warwick and St Andrews, so it is likely that I would not be there
for much of Wednesday.

John

**Comment by alex-konovalov** [comment]
OK, let's do a quick check before a proper registration. It looks like we may welcome in St Andrews
* @kohlhase 
* @florian-rabe 
* @JohnCremona (for 2 days?)
* @nthiery 

If you are coming and your name is not here, please edit this comment on GitHub or reply by email.

**Comment by VivianePons** [comment]
I will be there, but only Monday and Tuesday

2015-12-03 15:50 GMT+01:00 Alexander Konovalov <notifications@github.com>:

**Comment by pdehaye** [comment]
Planning on coming
Paul

**Comment by kohlhase** [comment]
At the Kickoff meeting there seemed to be more general interest. Are we reaching the potential participants by this method? Should we announce via the mailing list? 

I guess we should also have something like an agenda so that people can see whether they are interested.

**Comment by bpilorget** [comment]
Saint-Andrews and the ODK coordinator are getting organised to set up an agenda and to decide the best way to communicate the whole WP6 workshop event to the ODK participants. 
The information should come in the next few days hopefully.

Stay tuned ;)

**Comment by nthiery** [comment]
+1: as soon as we have some rough outline of the workshop content, we should mail news@opendreamkit.org (which is participants@odk plus followers).

Btw: https://github.com/OpenDreamKit/OpenDreamKit.github.io/blob/master/meetings/2016-01-25-DKS/program.md

**Comment by florian-rabe** [comment]
I'm testing if I can mention a whole team on an issue and trigger according notications.
@OpenDreamKit/wp6

**Comment by alex-konovalov** [comment]
@florian-rabe seems to work, but maybe I've got this because I'm watching the repo and/or contributed to this issue.

**Comment by florian-rabe** [comment]
So mentioning a team works fine.

I've created a team WP6 and added all of us.

We should mention this team when creating future issues to ensure that the relevant people get subscribed automatically.

**Comment by pdehaye** [comment]
Closing this, as the workshop happened!
