### ISSUE TITLE
T5.2: GAP

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#100]
- **WP5:** [High Performance Mathematical Computing](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP5)
- **Lead Institution:** University of St Andrews
- **Partners:** None
- **Work phases:** 0-48!0.375

See page 49 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by ClementPernet** [comment]
@stevelinton @alex-konovalov : could you feed me with some status updated on this task. Even if the delivery is scheduled for next year, we need to write a status update in D1.5 (issue #21 ) of this fall's report. This is urgent (we need to write this update by thursday Aug. 30th).

**Comment by alex-konovalov** [comment]
GAP 4.9 release now includes HPC-GAP (see [here](https://www.gap-system.org/Manuals/doc/changes/chap2.html#X7F52B77B7DBACC17)). I will look at D1.5 later.

**Comment by alex-konovalov** [comment]
@ClementPernet done in dffd5edd9652b09b9fe4646bafc5167a4a1e88f8

**Comment by ClementPernet** [comment]
Great. thanks.

Le 30/08/2018 à 13:15, Alexander Konovalov a écrit :

**Comment by alex-konovalov** [comment]
@ClementPernet you can now have a preview of report D5.15 at https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP5/D5.15
