### ISSUE TITLE
T5.4: Singular

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#102]
- **WP5:** [High Performance Mathematical Computing](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP5)
- **Lead Institution:** University of Kaiserslautern
- **Partners:** None
- **Work phases:** 0-48!0.9
- **Proposal**: [p. 50](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)
- **Deliverables**: D5.6 (#119), D5.7 (#120), D5.13 (#111)

The unique challenge of parallelizing Singular has been that it is a decades-old project, with a codebase exceeding 300,000 lines of code and an enormous existing investment of development effort. This makes a wholesale manual rewrite or reengineering approach infeasible. We therefore use a multi-pronged approach: First, we have created automated source-to-source translation tools that take existing C/C++ code as input and generate thread safe code as output. Secondly we are also adding facilities to the C/C++ code and the Singular interpreter to safely access shared memory. These facilities ensure in particular that common pitfalls of concurrent programming, such as data races and deadlocks, cannot occur. For this, we leverage approaches that have already been successfully used for HPC-GAP and whose principles are well-understood.  To supplement the above existing work, we propose to add very fine-grained parallelism to some key components of Sin- gular. These include writing a multi-threaded implementation of the Singular multivariate polynomial arithmetic, of the main quadratic sieve implementation for integer factoring and parallelisation of the FFT based integer and dense poly- nomial multiplication algorithm. These key components are used extensively for Singular’s overall workload, including in the Groebner basis engine and polynomial subsystems. Performance increases through fine-grained parallelisation of key components such as these will provide extensive benefits to virtually all users of Singular on multi-core machines.

**Comment by ClementPernet** [comment]
@wbhart @wdecker : could you feed me with some status update on this task. Even if the delivery is scheduled for next year, we need to write a status update in D1.5 (issue #21 ) of this fall's report. This is urgent (we need to write this update by thursday Aug. 30th).
Best would be if you could edit the report of D1.5 with these updates.

**Comment by wbhart** [comment]
I'm not sure what you mean by "edit the report of D1.5". If I click the link to issue #21 I don't see anything to edit.

**Comment by ClementPernet** [comment]
It is about editing the tex file for the report of deliverable D1.5.
It is located at:
  OpenDreamKit/WP1/D1.5/WP5.tex

( https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP1/D1.5/WP5.tex )

But feel free to feed me with the status update and I'll merge it to this file.

Clément

Le 29/08/2018 à 15:12, wbhart a écrit :

**Comment by wbhart** [comment]
Thanks. Any idea on how much prose you want? 1/2 page, 2 pages?

**Comment by ClementPernet** [comment]
Max 1/2 page (total for WP5 should be 2-3 pages).
By default the WP5.tex file contains the status update from the previous evaluation period.
Feel free to drop all of it, or to keep some pieces if you find that they would help putting the new 
information into context.

Le 29/08/2018 à 15:39, wbhart a écrit :

**Comment by nthiery** [comment]
>    Thanks. Any idea on how much prose you want? 1/2 page, 2 pages?

yeah, 1/2 page or so; you can find our previous technical report
there:

https://github.com/OpenDreamKit/OpenDreamKit/blob/master/ReportingPeriod_1/Technical_Report/report-final.pdf

and got no complaint about it; of course with time there is presumably
some more to say, and you should adjust to whatever space you need.

**Comment by wbhart** [comment]
Yeah, the deliverables mentioned in the previous report have all been delivered already and closed. The deliverable we are working on wasn't mentioned at all, as far as I can see. So we'll be removing three sections and adding one in it's place it seems.

**Comment by ClementPernet** [comment]
No problem. Thanks
