### ISSUE TITLE
T5.6: HPC infrastructure for combinatorics

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#104]
- **WP5:** [High Performance Mathematical Computing](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP5)
- **Lead Institution:** Université Paris-Sud
- **Partners:** CNRS
- **Work phases:** 0-6!0.3,12-36!0.5
- **Deliverables:** D5.1 (#107), D5.8 (#121), D5.11 (#109)

See page 50 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by jdemeyer** [comment]
One part which is needed for this is a *good* multi-processing library for Python. The best implementation of multiprocessing that I know of is the one used by the Sage doctesting framework (I mostly wrote that :-)).

I think we should convert the multiprocessing framework used in the doctester to a real Python package and use that. If somebody can instead show me an existing library which works well, that's of course also good. But I doubt such a library exists.

Useful features:
- multi-level multiprocessing (multiprocessing children should also be able to run multiprocessing themselves)
- interrupting (CTRL-C)
- more generally: proper exception handling (allow to display exceptions from children)
- detect when a child has crashed (e.g. a segmentation fault)
- redirecting standard output/error of the children
- no race conditions
- be fast (low overhead)

Note that it might be needed to restrict to POSIX systems to implement all this (for example, the doctester uses the `pselect()` system call). I don't consider this a problem.

**Comment by jdemeyer** [comment]
There is [joblib.Parallel](http://pythonhosted.org/joblib/parallel.html) which has many user-side features but doesn't really solve the problems I mentioned above. I guess what's needed is a better joblib backend.

**Comment by hivert** [comment]
On Mon, Nov 23, 2015 at 02:42:22AM -0800, jdemeyer wrote:
> One part which is needed for this is a *good* multi-processing library for
> Python. The best implementation of multiprocessing that I know of is the one
> used by the Sage doctesting framework (I mostly wrote that :-)).

Right now for what I'm currently finishing for ODK (see ticket: #13580) I'm
using the basic multiprocessing library of Python. It's not ideal but does the
job. I've no experience of using some more advanced stuff and I'm interrested
in sharing experience.

Florent

**Comment by jdemeyer** [comment]
I think that [#13580](http://trac.sagemath.org/ticket/13580) would also serve as a good example of what this better multiprocessing framework should support. It would need to support
- parallel doctesting
- parallel docbuilding
- parallel distutils
- `@parallel`
- #13580

**Comment by hivert** [comment]
On Mon, Nov 23, 2015 at 04:29:46AM -0800, jdemeyer wrote:
> I think that [#13580](http://trac.sagemath.org/ticket/13580) would also serve as a good example of what this better multiprocessing framework should support. It would need to support
> - parallel doctesting
> - parallel docbuilding
> - parallel distutils
> - `@parallel`
> - #13580

If you want to know more about what I'm doing, I'm presenting my work on
Thursay to a seminar on parallel computing. When done, the slides will be
accessible at:

   https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP5/T5.6

Florent

**Comment by videlec** [comment]
Has has anybody some experience with Open MP and how it can be mixed with Cython?

On the other hand, Sage is clearly lacking something for parallel computation with *several* computers. The Message Passing Interface (MPI) seems to be the standard approach for that. There are several Python bindings available. Does anybody already played with it?

(I aimed to recruit an engineer for that task in Bordeaux, but we lacked serious candidatures)

**Comment by serge-sans-paille** [comment]
This may or may not suit your problem, but pythran (part of the project) supports full OpenMP3 integration into Python, but only for the subset of Python supported by Pythran.

I have not played with the MPI bindings, but combining pythran + one of these binding would be a great way to achieve a full-python efficient HPC toolchain ;-)

**Comment by fangohr** [comment]
Cython does support OpenMP parallelism (http://docs.cython.org/src/userguide/parallelism.html). 

Regarding MPI and Python, we are just starting to work with this (for a different project), so I'd be interested to stay in touch about this, exchange ideas etc. A good starting point might be https://pythonhosted.org/mpi4py/, and I also recommend the 'demos' from https://bitbucket.org/mpi4py/mpi4py

**Comment by serge-sans-paille** [comment]
Yes! This only a very small part of OpenMP though (no tasks, no barrier, no mutex, no atomic etc).

**Comment by jdemeyer** [comment]
`openmp` is multithreading, not multiprocessing, so it's a different thing.

MPI looks useful, but you still need a good interface for it.

**Comment by gouarin** [comment]
Hi,

I have used mpi4py for many years and I think that you will not find a
better interface. L. Dalcin has used Cython to call the C library and it is
perfectly done to have the same performance when we have NumPy arrays. A
colleague tells me recently that mpi4py has no very good scalability when
you have more than 1 000 cores but I need to test this to confirm (he was
not sure).

You can also take a look at openACC (in that way you could also use GPU). I
would like to work on that with Serge to use it with Pythran. OpenMP and
openACC shoud be the norm in the next few years to have parallel code on
several architectures (CPU, GPU, KNL, ...).




2015-11-23 18:33 GMT+01:00 jdemeyer <notifications@github.com>:

**Comment by jdemeyer** [comment]
The way I see it, there are 3 depths of parallellization:

1. multi-threading (on 1 machine you have several threads sharing memory) -> use Cython

2. forked multi-processing (on 1 machine you fork off child processes) -> **no good interface yet**

3. running on multiple machines -> use MPI

I would like to implement a good low-level interface to do 2 since I think it does not exist yet. The focus would be on providing a solid foundation, rather than having many user-level features. Of course, that user-level functionality could be added on top of this. The implementation would be based on the parallel doctester in Sage and aims to support all existing use-cases of multiprocessing in Sage.

**Comment by martinal** [comment]
Maybe consider also http://zeromq.org/ which is in may ways more flexible
than mpi. I don't have personal experience with it but others in
OpenDreamKit surely do.

Martin

**Comment by serge-sans-paille** [comment]
Depending on your parallelism grain, 2) can be done with 1) or 3), no?

**Comment by jdemeyer** [comment]
> Depending on your parallelism grain, 2) can be done with 1) or 3), no?

Certainly not 1) because of shared memory, Python doesn't like that.

In certain cases it might be possible to use 3) but then you need to start independent Python processes. So you're looking at an overhead of 1 second or so per process when you're running Sage. It also makes the communication harder to implement (you cannot use pipes or shared memory for example).

I really think there is a use case for all 3 scales.

**Comment by serge-sans-paille** [comment]
It's ok to do 1) in a native module. Thansk for the info about 3 \o/

**Comment by hivert** [comment]
Dear HPC fan,

For your information [#13580](http://trac.sagemath.org/ticket/13580)
"Distributed/Paralell computations using RecursivelyEnumeratedSet" which is
the first deliverable for T5.6: HPC infrastructure for combinatorics is now in
needs review on Sage trac.

Cheers,

Flornet

**Comment by ClementPernet** [comment]
@hivert @VivianePons : could you feed me with some status update on this task. Even if the delivery is scheduled for next year, we need to write a status update in D1.5 (issue #21 ) of this fall's report. This is urgent (we need to write this update by thursday Aug. 30th).
Best would be if you could directly edit the report of D1.5 with these updates.

**Comment by hivert** [comment]
@ClementPernet : Done. I was waiting for @videlec input... Please reread.
