### ISSUE TITLE
D5.1: Turn the Python prototypes for tree exploration into production code, integrate to Sage .

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#107]
- **WP5:** [High Performance Mathematical Computing](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP5)
- **Lead Institution:** Université Paris-Sud
- **Due:** 2015-11-30 (month 3)
- **Submitted to Sage:** 2015-11-30
- **Merged into Sage:** 2015-12-??
- **Task**: T5.6 (#104)
- **Nature:** Demonstrator

Turn the Python prototypes for tree exploration into production code,
integrate to SageMath. See:

- [Trac Ticket 13580](http://trac.sagemath.org/ticket/13580) for the source code as well as the discussion about the integration into Sage.

- The [slides](https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP5/T5.6/HPC-Combi.pdf) of a presentation for the [journée du groupe de travail LaMHA](http://tesson.julien.free.fr/LaMHA/2015/automne.php), Automne 2015, Université Pierre et Marie Curie - 2015, November the 26.

- A [snapshot of the documentation](https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP5/T5.6/documentation.pdf).

- Page 51 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf).

**Comment by hivert** [comment]
Ticket [#13580](http://trac.sagemath.org/ticket/13580) "Distributed/Paralell computations using RecursivelyEnumeratedSet and Map-Reduce" is now needs review on Sage trac.

**Comment by hivert** [comment]
Ticket [#13580](http://trac.sagemath.org/ticket/13580) "Distributed/Paralell computations using RecursivelyEnumeratedSet and Map-Reduce" was just integrated to Sage. I'm closing this issue.

**Comment by nthiery** [comment]
Yippee!
