### ISSUE TITLE
D5.12: Exact linear algebra algorithms and implementations. Library maintenance and close integration in mathematical software for LinBox library

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#110]
- **WP5:** [High Performance Mathematical Computing](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP5)
- **Lead Institution:** Universite Grenoble Alpes
- **Due:** 2018-08-31 (month 36)
- **Nature:** Demonstrator
- **Task:** T5.3 (#101) LinBox
- **Proposal:** [p. 51](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)
- **[Final report](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP5/D5.12/report-final.pdf)** ([sources](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP5/D5.12/))

# Context
Computational linear algebra is a key tool delivering high computing throughput to applications requiring large scale compuations. In numerical computing, dealing with floating point arithmetic and approximations, a long history of efforts has lead to the design of a full stack of technology for numerical HPC: from the design of stable and fast algorithms, to their implementation in standardized libraries such as LAPACK and BLAS, and their parallelization on shared memory servers or supercomputers with distributed memory.

On the other hand, computational mathematics relies on linear algebra with exact arithmetic, i.e. multiprecision integers and rationals, finite fields, etc. This leads to significant differences in the algorithmic and implementations approaches. Over the last 20 years, a continuous stream of research has improved the exact linear algebra algorithmic and simultaneously, software projects, such as LinBox and fflas-ffpack were created to deliver, a similar set of kernel linear algebra routines as LAPACK but of exact arithmetic. 

# Goal of the deliverable
This deliverable aims at taking a major step forward in the advancement of this technology stack for exact linear algebra: the development of new application frameworks, new algorithms, their careful implementation as high performance kernels in a standardized library. As a demonstrator for the usability of this building block for the development of virtual research environment, a key outcome of this deliverable is a tight integration of the libraries LinBox and fflas-ffpack into the software SageMath.

**Comment by nthiery** [comment]
Salut @ClementPernet,
How is the report writing going? Only 14 days left!
Thanks in advance,

**Comment by ClementPernet** [comment]
@nthiery : part of this deliverable consist in scientific publications and I am summarizing them in the deliverable report. Since I read that the report should be self contained, do you think that I should also add the papers as appendix to the deliverable?

**Comment by nthiery** [comment]
>    [1]@nthiery : part of this deliverable consist in scientific
>    publications and I am summarizing them in the deliverable report. Since
>    I read that the report should be self contained, do you think that I
>    should also add the papers as appendix to the deliverable?

+1

Thanks!

**Comment by videlec** [comment]
On the practical side you can also mention some trac tickets

- [#22924](https://trac.sagemath.org/ticket/22924) and [#22970](https://trac.sagemath.org/ticket/22970) (positive review),
- [#24544](https://trac.sagemath.org/ticket/24544)  (needs work because of compilation failure),
- [#23214](https://trac.sagemath.org/ticket/23214) (needs work because depends on [#24544](https://trac.sagemath.org/ticket/24544)).

If you do so, you can mention the Cython efforts to support more C++ than it used to be that made all this happen.

**Comment by ClementPernet** [comment]
Thanks @videlec . Which deliverable/task would be best to cite for the Cython efforts ?

**Comment by ClementPernet** [comment]
Done with the report. Open for reviews

**Comment by hivert** [comment]
I'm rereading it right now...

**Comment by hivert** [comment]
@ClementPernet : Everything looks good to me except for table 1. Maybe you should not show all the cases here but only one of them and detail a little bit more which column corresponds to which computation.

**Comment by ClementPernet** [comment]
Ok, I'm on it

**Comment by ClementPernet** [comment]
I reduced the table and added a paragraph giving more explanations on it.

**Comment by hivert** [comment]
Doesn't compile anymore:
```
! Undefined control sequence.
l.132 ...ntation outperform  LAPACK's best \dsytrf
                                                   for larger dimension, eve...
```

**Comment by ClementPernet** [comment]
Oups. Sorry. It is fixed now.

**Comment by hivert** [comment]
I now got now several undefined references and missing citations:
```
LaTeX Warning: Reference `tab:timings' on page 2 undefined on input line 120.


Package natbib Warning: Citation `jgd:2017:bruhat' on page 2 undefined on input line 122.

Package natbib Warning: Citation `LAPACK99' on page 2 undefined on input line 123.

Package natbib Warning: Citation `lawn294' on page 2 undefined on input line 125.
```

**Comment by ClementPernet** [comment]
Apologies. I was trying to go too fast.

**Comment by ClementPernet** [comment]
Should be fixed now

**Comment by hivert** [comment]
There where still some ash of a previous sentence and I added a comma to ease the reading. Seems good to me. Pushed the fix.

**Comment by ClementPernet** [comment]
Thanks

**Comment by hivert** [comment]
Nicolas is waiting for your green light on this report. No rush is needed. He has plenty more work to do ;-)

**Comment by ClementPernet** [comment]
Ok, I was waiting for yours, yes green light!

**Comment by nthiery** [comment]
Submitted!

Thanks @ClementPernet! I did not yet get to read the report in full, but the context is nicely explained and it shows off well the strong scientific work behind.

**Comment by nthiery** [comment]
It would be worth to advertise this as a blog post on our web site; it could be basically the same content of the report; or maybe something less technical; possibly just the abstract, with links to the reports.

**Comment by IzabelaFaguet** [comment]
Accepted by the EU on December 5th.

**Comment by IzabelaFaguet** [comment]
Accepted by the EU on December 5th.
