### ISSUE TITLE
D5.3: Sun Grid Engine support for Project Jupyter Hub

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#116]
- **WP5:** [High Performance Mathematical Computing](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP5)
- **Lead Institution:** University of Sheffield
- **Due:** 2016-08-31 (month 12)
- **Nature:** Other
- **Task:** T5.8 #106 
- **Proposal:** [p.51](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)
- **[Final report](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP5/D5.3/report-final.pdf)**

It is common for academic High Performance Computing (HPC) clusters to make use of schedulers based on Sun Grid Engine with Son of Grid Engine as one of the most popular. It is used, for example, on the institutional HPC systems in the Universities of Sheffield and Manchester in the UK. It is also used on the regional N8 HPC facility, a system shared by the 8 most research intensive universities in the North of England.
In this deliverable, we have developed and demonstrated a Sun Grid Engine notebook spawner for Project Jupyter, allowing users to easily access Jupyter notebooks on HPC clusters directly from the web-browser. This development allows users with no background in High Performance Computing to easily migrate workflows from laptop to HPC cluster, allowing them to access greater resources with no additional training required.

**Comment by mikecroucher** [comment]
We have an experimental service on Sheffield's HPC system based on the work done for this task.  User-facing docmentation is at http://docs.iceberg.shef.ac.uk/en/latest/using-iceberg/accessing/jupyterhub.html

**Comment by mikecroucher** [comment]
The code that allows this to happen:

* https://github.com/cadair/sgespawner - Extends JupyterHub such that it can spawn notebook servers on worker nodes by interacting with the Sun Grid Engine queue.

* https://github.com/Cadair/jupyter_environment_kernels. This allows users of the HPC cluster to install specialised environments in their home directory and subsequently make use of them in the Jupyter notebook on the system.

**Comment by mikecroucher** [comment]
Report submitted -- PR #195

**Comment by bpilorget** [comment]
@mikecroucher Can you write an abstract of the report here please? So taht people outside the consortium know what theyr are going to read. Thanks X

**Comment by bpilorget** [comment]
Deliverable finished. To be submitted.

**Comment by nthiery** [comment]
Let's keep this open until the report is actually uploaded on the EU portal. I am working on it.

**Comment by nthiery** [comment]
I proofread the document, made micro improvements and improved the report style file. I have now submitted report-final.pdf on the EU portal.
Nice features, clear report, all delivered on time. I love you guys :-)
Now looking forward further progress on this front!

**Comment by mikecroucher** [comment]
Thanks Nicolas, greatly appreciated.
