### ISSUE TITLE
D5.4: Make Pythran typing better to improve error information.

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#117]
- **WP5:** [High Performance Mathematical Computing](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP5)
- **Lead Institution:** Logilab
- **Originally due:** 2016-08-31 (month 12)
- **Nature:** Demonstrator
- **Task:** T5.7 (#105)
- **Proposal:** [p.51](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)
- **[Final report](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP5/D5.4/report-final.pdf)**

Pythran is a Python to C++ compiler for a subset of the Python language, with a focus on scientific computing, which takes advantage of multi-cores and SIMD instruction units. Given the importance of Python in the OpenDreamKit ecosystem, Pythran is one of the promising building blocks for high performance mathematical computing.

This deliverable is about enhancing the Pythran compiler to provide better user feedback when a type error is meet, by extracting and taking advantage of fine grain type information. The optimizations developed in this context are a more accurate version of identifier binding that increases the scope of Pythran valid input. Second, an unsound type checker has been developed and integrated in the 0.8 version of the Pythran compiler. It provides usable, meaningful feedback to users in case of type error, instead of internal compiler errors. These two steps make it easier to write computation-intensive kernels to be compiled by Pythran.

**Comment by serge-sans-paille** [comment]
Nice step toward better typing in pythran: Better identifier binds-to computation.

http://serge-sans-paille.github.io/pythran-stories/identifier-binding-computation.html

**Comment by bpilorget** [comment]
Deliverable to be postponed

**Comment by bpilorget** [comment]
The README gives info on how to write deliverables (scroll down): https://github.com/OpenDreamKit/OpenDreamKit

**Comment by serge-sans-paille** [comment]
Ack!

**Comment by bpilorget** [comment]
@ClementPernet and @serge-sans-paille 
This deliverable is due for February 2017(No postponement allowed!!)

**Comment by serge-sans-paille** [comment]
Not an issue for me, I am to deliver this on december :-)

**Comment by serge-sans-paille** [comment]
Deliverable sent to logilab, merged into the trunk of pythran and advertise in a blogpost http://serge-sans-paille.github.io/pythran-stories/from-pythran-import-typing.html

**Comment by nthiery** [comment]
Great, there just remain to write the report. Who is handling this? @serge-sans-paille ? @fcayre ?

**Comment by nthiery** [comment]
Ping! Since it's jut a matter of a short report, it would be good to get this done.

**Comment by serge-sans-paille** [comment]
Woops missed that one. I'll write the report, @nthiery can you just point me to the place I should put it?

**Comment by nthiery** [comment]
On Wed, Feb 01, 2017 at 11:28:38AM -0800, serge-sans-paille wrote:
>    Woops missed that one. I'll write the report, [1]@nthiery can you just
>    point me to the place I should put it?

See our main README :-)

https://github.com/OpenDreamKit/OpenDreamKit/#submitting-a-deliverable

**Comment by nthiery** [comment]
Dear M18 deliverable leaders,

Just a reminder that reports are due for mid-february, to buy us some time for proofreading, feedback, and final submission before February 28th. See our [README](https://github.com/OpenDreamKit/OpenDreamKit/#submitting-a-deliverable) for details on the process.

In practice, I'll be offline February 12-19, and the week right after will be pretty busy. Therefore, it would be helpful if a first draft could be available sometime this week, so that I can have a head start reviewing it.

Thanks in advance!

**Comment by nthiery** [comment]
Final report, as of 28859db3f523812229b4dae72bf5df30226942fd submitted on the EU portal.

Thank you Serge for this nice improvement to Pythran and its report!
