### ISSUE TITLE
Generate Issues and Milestones for Work Packages

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#12]
As discussed at the Kickoff meeting, I have written [a script](https://github.com/KWARC/LaTeX-proposal/blob/master/bin/generate-issues) to generate GitHub issues for discussion of the work packages. The decision at the meeting was to  do the following:

- create an Issue for each Task
- create an Issue and Milestone for each Deliverable
- label each Issue with the associated institutions and work package and whether they are a task or deliverable.

The latest conclusion was to create all of these on this OpenDreamKit/OpenDreamKit repo. The results of this script can be seen [on this test repo](https://github.com/minrk/odktest). If I get the go-ahead, I can run the script and create all the issues. **It will result in about 150 emails to people subscribed to this repo**.

**Comment by nthiery** [comment]
I have just browsed through the test repo, and it's great. I am really glad you volunteered for automatizing this for this is so much higher quality than what we would have done by hand. Thanks a lot!

Some very last suggestions for the description of the task-related issues:
- Make the workpackage item (e.g. WP5: ...) a link to the corresponding repo OpenDreamKit/WP5
- Add the proposal page as is done for in the work package description
- Maybe there is no need anymore to include the "Partners" item in the description given that this info is in the labels
- Maybe we don't need a line break between each item? This would save some vertical space. Or alternatively this could be an itemized list.

Once you have made up your mind about the above, just go ahead, and press the button!

Thanks again,

**Comment by minrk** [comment]
> Make the workpackage item (e.g. WP5: ...) a link to the corresponding repo OpenDreamKit/WP5

My understanding was that there was not going to be such a repo for each work package. Has this changed?

> Add the proposal page as is done for in the work package description

This would be easy if the information existed in the metadata file, but it does not.

> Maybe there is no need anymore to include the "Partners" item in the description given that this info is in the labels

I like having the partners in the initial description as a verification that the labels are correct, but I can remove them. I expect the body description to change over time, so these are just a starting point.

> Maybe we don't need a line break between each item?

Bulleted list is easy enough, I will do that.

**Comment by nthiery** [comment]
On Mon, Sep 07, 2015 at 04:39:09AM -0700, Min RK wrote:
>      Make the workpackage item (e.g. WP5: ...) a link to the
>      corresponding repo OpenDreamKit/WP5
> 
>    My understanding was that there was not going to be such a repo for
>    each work package. Has this changed?

Sorry, I misformulated: I meant a link to the corresponding directory
OpenDreamKit/OpenDreamKit/WP5.

>      Add the proposal page as is done for in the work package description
> 
>    This would be easy if the information existed in the metadata file, but
>    it does not.

Oh, really? On my machine, in proposal.pdata I see:

    \@pdata@def{task}{dissem@task4}{title}{Dissemination and Communication activities}
    \@pdata@def{task}{dissem@task4}{lead}{PS}
    \@pdata@def{task}{dissem@task4}{partners}{SA}
    ...
    \@pdata@def{task}{dissem@dissemination-communication}{page}{40}

>    I like having the partners in the initial description as a verification
>    that the labels are correct, but I can remove them. I expect the body
>    description to change over time, so these are just a starting point.

Ok, proceed as you feel like.

I forgot to mention: to make sure that the info matches correctly with
the very final version of the proposal on the web, please pull
OpenDreamKit/OpenDreamKit, and run:

        make final

Oh but wait, the compilation is not going smoothly right now!

@kohlhase: it seems your merge
46173c4cfe13a088c60884706f55b737490cf3ed reverted some of the changes
I had introduced in 69e251649a0adaebee746bf277712cf050393a03, in
particular the definition of \ifgrantagreement.

There are also several warnings like:

    pdfTeX warning (dest): name{mile@proto1@target} has been referenced but does not exist, replaced by a fixed one

But that might be just a consequence of the above. Michael, do you
mind investigating this? Then we can recompile a last time and push
the very final version of the proposal on the web. And then Min can
press the green button to create the issues.

Thanks,
				Nicolas

**Comment by minrk** [comment]
> I meant a link to the corresponding directory OpenDreamKit/OpenDreamKit/WP5

That makes sense, will do.

> Oh, really? On my machine, in proposal.pdata I see

Ah, I see a page number for tasks, just not for deliverables. I will add them for tasks, at least.

**Comment by kohlhase** [comment]
I am sure that I can generate the page information for deliverables in the proposal class (but only tomorrow since I am traveling today), and then we can have the links.

Michael


----------------------------------------------------------------------
 Prof. Dr. Michael Kohlhase, Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1,
 Jacobs University Bremen D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase
 m.kohlhase@jacobs-university.de<mailto:m.kohlhase@jacobs-university.de> http://kwarc.info/kohlhase
----------------------------------------------------------------------


________________________________

**Comment by minrk** [comment]
@kohlhase thanks, I will wait for that, then re-run the script with page info for deliverables. The rest of @nthiery's requests are already done and testing now.

**Comment by martinal** [comment]
A sidenote: I wonder if I did a mistake earlier by pushing some edits after
the final proposal was finalized. Should they be reverted?

[martinal@martinal-mc OpenDreamKit (master)]$ git log --
Proposal/WorkPackages/UserInterfaces.tex
commit 13927831f86b5e60199b7468d768e88364ef742c
Author: Martin Sandve Alnæs <martinal@simula.no>
Date:   Wed Jun 24 09:34:26 2015 +0200

    Minor language edits in UI WP description.

**Comment by nthiery** [comment]
On Mon, Sep 07, 2015 at 05:48:04AM -0700, Martin Sandve Alnæs wrote:
>    A sidenote: I wonder if I did a mistake earlier by pushing some edits
>    after
>    the final proposal was finalized. Should they be reverted?

No, that's fine. Having a proposal that reads better is good, and as
long as it only differs from the grant agreement by trivial
reformulation that's ok w.r.t. the EU.

But we should probably indeed freeze the proposal once we have built
all the issues from it to avoid risking some page shift.

Cheers,
				Nicolas
--
Nicolas M. Thiéry "Isil" <nthiery@users.sf.net>
http://Nicolas.Thiery.name/

**Comment by stevelinton** [comment]
The label for St Andrews should be USTAN, not US

**Comment by defeo** [comment]
And UVSQ for Versailles would be preferable.

**Comment by minrk** [comment]
@defeo @stevelinton thanks for the feedback, I've updated the script. We can easily change the text of labels at a later point if we don't like how they are spelled, if anyone has similar preferences after the script has been run.

**Comment by kohlhase** [comment]
> @kohlhase thanks, I will wait for that, then re-run the script with page info for deliverables. The rest of @nthiery's requests are already done and testing now.

I have added the deliverable pages to ```proposal.pdata```, please re-run and then you can generate.

**Comment by minrk** [comment]
Script is updated and re-uploading a test to [minrk/odktest2](https://github.com/minrk/odktest2). If anyone wants to sign-off on that output, I will do the real thing on this repo.

**Comment by kohlhase** [comment]
> If anyone wants to sign-off on that output

sounds like the privilege of Nicolas :-)

**Comment by defeo** [comment]
If anyone is wondering how to sign-off, here it is: https://github.com/settings/notifications

Temporarily uncheck the email checkbox for watched repositories (I believe).

**Comment by nthiery** [comment]
@kohlhase: thanks for the merge!

I still get a couple compilation warnings, like:

    LaTeX Warning: label for task research-categories@. undefined on input line 79.
    \@EveryShipout@Output ...@Org@Shipout \box \@cclv                                               
    l.459 
    pdfTeX warning (ext4): destination with the same identifier (name{table.3.4.9}) has been already used, duplicate ignored

    Package biblatex Warning: Deprecated option.
    (biblatex)                Ignoring 'maxnames' on input line 1159.

    LaTeX Warning: No publication pages specified; use the pubspage key in the proposal environment! on input line 1159.

    LaTeX Warning: There were undefined references.
    pdfTeX warning (dest): name{mile@community@target} has been referenced but does not exist, replaced by a fixed one
    pdfTeX warning (dest): name{mile@proto1@target} has been referenced but does not exist, replaced by a fixed one
    pdfTeX warning (dest): name{mile@startup@target} has been referenced but does not exist, replaced by a fixed one

Do you mind having a brief look while I double check on Min's script output?

Thanks.

**Comment by kohlhase** [comment]
I think that these are safe to ignore. Unfortunately, I do not have the time to look at them now.

**Comment by nthiery** [comment]
I looked a bit more in details at the log file. There were four undefined references left which I fixed. I believe we can freeze `proposal-www.pdf` now.

@minrk: I checked the output, and it's great!
At some point we probably will want to add our four real milestones (as given by the lines looking like `\@pdata@def{mile}{startup}{delivs}` in `final.pdata`). But we can always do that later.

So, @minrk, please pull, run `make final` a last time on your machine, and run your script for real on the produced `final.pdata`!

Thanks

**Comment by minrk** [comment]
@nthiery thanks! Firing away. Apologies in advance for the coming emails...

**Comment by minrk** [comment]
All done.

**Comment by nthiery** [comment]
On Tue, Sep 08, 2015 at 01:48:42PM -0700, Min RK wrote:
>    All done.

Yeah! Thanks!
