### ISSUE TITLE
D5.8: Explore the possibility to interface smoothly Pythran , Cython and Cilk++.

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#121]
- **WP5:** [High Performance Mathematical Computing](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP5)
- **Lead Institution:** Université Paris-Sud
- **Due:** 2017-08-31 (month 24)
- **Task:** T5.6 (#104) and related to T5.7 (#105)
- **Nature:** Demonstrator

See page 51 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by bpilorget** [comment]
@hivert @ClementPernet  This deliverable is officially due for 31/08/2017. Can you please report on the progress you have achieved?
Thanks in advance

**Comment by bpilorget** [comment]
#121 was merged into #109 after 3rd amendment to the contract
