### ISSUE TITLE
D5.9: Library design and domain specific language exposing LinBox parallel features to Sage

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#122]
- **WP5:** [High Performance Mathematical Computing](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP5)
- **Lead Institution:** Université Joseph Fourier
- **Due:** 2017-08-31 (month 24)
- **Nature:** Report

See page 51 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by bpilorget** [comment]
@ClementPernet

**Comment by bpilorget** [comment]
#122 was merged into #112 after 3rd amendment to the contract
