### ISSUE TITLE
T6.1: Survey of existing DKS bases, Formulation of requirements

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#123]
- **WP6:** [Data/Knowledge/Software-Bases](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP6)
- **Lead Institution:** Universität Zürich
- **Partners:** Jacobs University Bremen, University of St Andrews, University of Warwick, University of Silesia
- **Work phases:** 0-3
- **Deliverables:** D6.2 (#136)
- **Proposal:** [p.53](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)

**Comment by pdehaye** [comment]
Own note: initial survey before St Andrews given at 2016-01-25-DKS/survey-generic.md
