### ISSUE TITLE
T6.5: Knowledge-based code infrastructure

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#127]
- **WP6:** [Data/Knowledge/Software-Bases](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP6)
- **Lead Institution:** Université Paris-Sud
- **Partners:** Universität Zürich, Jacobs University Bremen
- **Work phases:** 12-48
- **Deliverables:** D6.5 (#139), D6.2 (#136)
- **Proposal:** [p.54](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)

**Comment by kohlhase** [comment]
assigning to Nicolas as the UPSud site leader, please assign further.
