### ISSUE TITLE
T6.6: OEIS Case Study (Coverage and automated Import)

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#128]
- **WP6:** [Data/Knowledge/Software-Bases](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP6)
- **Lead Institution:** Jacobs University Bremen
- **Partners:** None
- **Work phases:** 12-18
- **Deliverables:** #138 

See page 54 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by kohlhase** [comment]
@nthiery @bpilorget @florian-rabe @m-iancu @pdehaye 
I have just added a [first draft (thanks to my student Enxhell Luzhnica who has done most of the work) of an OEIS report that reports on the work done for this task](tree/master/WP6/OEIS). 
This is one of the main parts of deliverable 6.4 (see #138), but we can already report on this now. Therefore I would like to make an ODK report for the formal review. 
BUT I am not sure how to best do that. Could you please advise?

**Comment by nthiery** [comment]
On Mon, Jan 09, 2017 at 06:28:07AM -0800, Michael Kohlhase wrote:
>    [1]@nthiery [2]@bpilorget [3]@florian-rabe [4]@m-iancu [5]@pdehaye
>    I have just added a [6]first draft (thanks to my student Enxhell
>    Luzhnica who has done most of the work) of an OEIS report that reports
>    on the work done for this task.
>    This is one of the main parts of deliverable 6.4 (see [7]#138), but we
>    can already report on this now.

Great :-)

>    Therefore I would like to make an ODK
>    report for the formal review.
>    BUT I am not sure how to best do that. Could you please advise?

Would you have time for a chat? I am on https://appear.in/odk

**Comment by kohlhase** [comment]
@nthiery and I chatted and we agreeed that I would make an "interrim report for D6.4" out of this, which can then be extended to full D6.4 when we have the other parts.
