### ISSUE TITLE
Create mailing lists for OpenDreamKit

### ISSUE THREAD

**Issue by nthiery** [OpenDreamKit/OpenDreamKit#13]
- [x] participants@opendreamkit.org (public, archived)
  - [x] announces@opendreamkit.org    (public, archived)
  - [x] community@opendreamkit.org    (public, archived)
  - [x] coordination@opendreamkit.org (private)
  - [x] advisory@opendreamkit.org     (private)
  - [x] steering@opendreamkit.org     (private)
  - [x] coordinator@opendreamkit.org  (private, coordinator, coordinator deputy, manager)
  - [x] admin@opendreamkit.org (private, the admin team for each site)

**Comment by nthiery** [comment]
Thanks Benoit!

**Comment by slel** [comment]
I'd suggest "news" instead of "announces".

**Comment by fangohr** [comment]
Yes, 'news' or 'announcements' would be better from a language point of view than 'announces'.

**Comment by nthiery** [comment]
Just as a data point: I had a look at a few projects (mozilla, ...), and most used "announce".

So I'd go for "news" or "announce", without a specific preference for one or the other.

**Comment by nthiery** [comment]
@bpilorget: I just had another use case for forwarding information to all people involved in a given work package; so it sounds worth creating them. Could you handle it in the coming days?
Thanks!

**Comment by bpilorget** [comment]
Will do!

**Comment by bpilorget** [comment]
They are now created. I will need your help to know who I can register in this list.

Plus, I propose the following aliases:
-wp2: dissemination-WP2@opendreamkit.org
-WP3: component-WP3@...
-wp4: interfaces-WP4@...
-wp5: hpc_WP5@...
-WP6: infrastructure_WP6@...
-wp7: social-WP7@...

**Comment by nthiery** [comment]
On Tue, Nov 03, 2015 at 03:20:51AM -0800, bpilorget wrote:
>    They are now created. I will need your help to know who I can register
>    in this list.
> 
>    Plus, I propose the following aliases:
>    -wp2: [1]dissemination-WP2@opendreamkit.org
>    -WP3: [2]component-WP3@...
>    -wp4: [3]interfaces-WP4@...
>    -wp5: [4]hpc_WP5@...
>    -WP6: [5]infrastructure_WP6@...
>    -wp7: [6]social-WP7@...

Thanks Benoît!

For now, please add the WP coordinator, myself, and Steve, in each of
them, all with list admin permissions. Then the WP coordinator can add
people as they see fit. As a complement, please send an e-mail on the
participants mailing list to advertise those lists (and remind about
the others), and ask people to subscribe to those lists they are
interested in.

Cheers,
				Nicolas

PS: I tried to do some administration on the coordination team mailing
list, but was denied admin access; could you check here (and the
others) that I and Steve have admin rights? Thanks!

**Comment by bpilorget** [comment]
Aliases for WP are done. Will publish them on the website today, and I will probably send a general email to all participants.

I've tried to look for the admin issue, but could not find the trick. Will ask CNRS IT support for help. 
When I know how to do it I will put WP leaders as administrators too (Who is WP7 WP leader???).
But FYI I am the "privileged owner", so that might explain the reason why you cannot administrate everything. I'll see if several people can be privileged owners.

Benoît
