### ISSUE TITLE
T6.9: Memoisation and production of new data

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#131]
- **WP6:** [Data/Knowledge/Software-Bases](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP6)
- **Lead Institution:** University of St Andrews
- **Partners:** University of Silesia, Université Paris-Sud, University of Warwick
- **Work phases:** 24-42!.6
- **Deliverables:** D6.9 (#143 )

Many CAS users run large and intensive computations, for which they want to collect the results while simultaneously working on software improvements. GAP retains computed attribute values of objects within a session; SAGE currently has a limited cached method. Neither offers storage that is persistent across sessions or supports publication of the result or sharing within a collaboration. We will use, extend and contribute back to, an appropriate established persistent memoisation infrastructure, such as python-joblib, redis-simple-cache or dogpile.cache, adding features needed for storage and use of results in mathematical research. We will design something that is simple to deploy and configure, and makes it easy to share results in a controlled manner, but provides enough assurance to enable the user to rely on the data, give proper credit to the original computation and rerun the computation if they want
to. Results are reported in D6.9 (#143).

See page 54 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by kohlhase** [comment]
assigning to Steve as the St. Andrews site leader, please assign further.

**Comment by nthiery** [comment]
cc: @nthiery, @markuspf , @alex-konovalov
