### ISSUE TITLE
D6.1: Full-text Search (Formulae + Keywords) over LaTeX-based Documents (e.g. the arXiv subset)

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#133]
- **WP6:** [Data/Knowledge/Software-Bases](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP6)
- **Lead Institution:** Jacobs University Bremen
- **Due:** 2016-05-31 (month 9)
- **Nature:** Other
- **Task:** T6.10 (#132)
- **Proposal:** [p.55](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)
- **[Final report](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP6/D6.1/report-final.pdf)**

**Comment by kohlhase** [comment]
I committed a first draft of report to ```WP6/D6.1```. Please have a look. Iwill give the report a throrough reading today and finish it up by tonight.

**Comment by kohlhase** [comment]
I have committed the final version, this now needs to be submitted to the EU.

**Comment by nthiery** [comment]
Report submitted to EU

**Comment by bpilorget** [comment]
# DELIVERABLES UPDATE

@kohlhase As you know , during the interim review in Bremen, reviewers gave advice to improve deliverables. UPSud tried to follow their advice by updating D5.1 #107 
The main critic is that deliverables should be static document. Therefore we went through the #107 report to check if all links were still working and also if the information contained on the links was necessary for the understanding of the report.
As a result when it was necessary annexes were added to the #107 report.

Can you please do the same for this deliverable and add annexes when need be?

**Comment by nthiery** [comment]
The reviewers had pointed to this specific report as a good example. I checked it briefly, recompiled it w.r.t. the latest style file, and resubmitted.
