### ISSUE TITLE
D6.11: LMFDB Integration of Algorithms, Data and Presentation

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#135]
- **WP6:** [Data/Knowledge/Software-Bases](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP6)
- **Lead Institution:** Jacobs University Bremen
- **Due:** 2019-08-31 (month 48)
- **Nature:** Report

See page 55 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

cc: @pdehaye, @JohnCremona

**Comment by bpilorget** [comment]
#135 was merged into #139 and #142 after 3rd amendment to the contract
