### ISSUE TITLE
D6.4: Conversion of existing and new Databases ( LMFDB , OEIS, FindStat ) to unified interoperable System:

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#138]
- **WP6:** [Data/Knowledge/Software-Bases](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP6)
- **Lead Institution:** Universität Zürich
- **Due:** 2017-08-31 (month 24)
- **Nature:** Websites, Media, etc.

See page 55 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by kohlhase** [comment]
(see discussion #128). We have a [first draft of the OEIS part](tree/master/WP6/D6.4) here, we can show this off at the review meeting.

**Comment by kohlhase** [comment]
We need a general introduction that recaps what we generally want to do (c/p from the proposal/MitM paper?) and then branch to the respective chapters. @pdehaye, could you do that? 
I would really like to already show this at the review meeting.

**Comment by kohlhase** [comment]
yes, that is the idea. But this is an optional thing. It would be nice if we could show something early. So do not feel bad.

**Comment by pdehaye** [comment]
@kohlhase I have read the interim D6.4 report now. Very nice work! I have decided to focus for tomorrow on a little explanation of how the different deliverables/goals/tasks fit together, poached from screenshots of the MITM paper. Will work on the introduction later, and aim to get that ready by the review moment. Getting this polished by then would buy WP6 significant goodwill from our officers for a D6.8 request as described in #201.

**Comment by kohlhase** [comment]
@pau, that sounds great. I also think that the OEIS work will make a good impression.

**Comment by pdehaye** [comment]
I have prepared my slides for now (have to take a break due to school run).

Have a look [here](http://opendreamkit.org/meetings/2017-01-19-EdinburghSteeringCommittee/ProgressReports/Zurich/). It really consists of the UZH progress report, and then more slides. The goal is to reexplain WP6, with a cue for you about D6.4, and then to explain deliverables after that and end with a hint for you again to speak.

**Comment by bpilorget** [comment]
@kohlhase  This deliverable is officially due for 31/08/2017. Can you please report on the progress you have achieved?
Thanks in advance

**Comment by kohlhase** [comment]
There is a [work-in-progress report (mostly about OEIS)](../tree/master/WP6/D6.4)  in the repos. 

> (see discussion #128). We have a first draft of the OEIS part here, we can show this off at the review meeting.

For the LMFDB the research has been done in @tkw1536 M.Sc thesis and we just need to put the necessary parts into the report. 

For Findstat nothing has been done yet, and I would argue that we should not do that anytime soon. 
In face the current state is that we have developed two general methods of data integration 
- source parsing and conversion (shown in the OEIS case study) 
- virtual theories in MMT (as in the LMFDB case study) 
which should cover the remaining cases including findstat. 
Findstat should be better to tackle when Florian is in Paris.

**Comment by bpilorget** [comment]
#138 was merged into  #139 after the 3rd amendment to the contract
