### ISSUE TITLE
D6.5: GAP/SAGE/LMFDB Interface Theories and alignment in OMDoc/MMT for System Interoperability 

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#139]
- **WP6:** [Data/Knowledge/Software-Bases](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP6)
- **Lead Institution:** Jacobs University Bremen
- **Due:** 2017-08-31 (month 24)
- **Nature:** Other
- **Tasks:** T6.4 (#126) and T6.5 (#127)
- **Proposal**: [p.54](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)
- **[Final report](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP6/D6.5/report-final.pdf)** ([sources](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP6/D6.5/))

There is a large ecosystem of mathematical software systems and knowledge bases.
Individually, these are optimized for particular domains and functionalities, and together they cover many needs of practical and theoretical mathematics.
However, each system specializes on one particular area, and it remains very difficult to solve problems that need to involve multiple systems.
Some integrations exist, but they are ad-hoc and have scalability and maintainability issues.
In particular, there is not yet an interoperability layer that combines the various systems into a virtual research environment (VRE) for mathematics.
  
The OpenDreamKit project aims at building a toolkit for such VREs.
It suggests using a central system-agnostic formalization of mathematics (Math-in-the-Middle, MitM) as a mathematical pivot point for semantic-preserving translations in the needed interoperability layer.
In this deliverable, we report on a series of case studies that instantiates the MitM paradigm with the systems GAP, SageMath, LMFDB, and Singular to perform distributed computation in group, ring, and number theory.
 
Our work involves massive practical efforts, including a novel formalization of computational group theory, improvements and extensions of the involved software systems and knowledge bases, an extension of the underlying knowledge management system to cope with large theories, and a novel mediating system that sits at the center of a star-shaped integration layout between mathematical software systems and knowledge bases.

Together with deliverable report [D6.8](https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP6/D6.8/report-final.pdf), this report describes the implementation and initial evaluation of the MitM integration and interoperability paradigm initially envisioned in deliverables D6.2 (#136) and D6.3 (#137).

The MitM paradigm constitutes the core development goal of WP6 and the curated content described in this report enables running non-trivial integrations. In the future, we expect further extending the reach of the integration in terms of both systems covered as well as knowledge available in the central MitM ontology.

**Comment by kohlhase** [comment]
In this deliverable we essentially describe the SageMath export based on the DKSbases design (see D6.2: #136). The Python/Sage foundation mostly gives meaning to the types/categories.

**Comment by bpilorget** [comment]
@florian-rabe  This deliverable is officially due for 31/08/2017. Can you please report on the progress you have achieved?
Thanks in advance

**Comment by florian-rabe** [comment]
I think this should be assigned to @kohlhase 

I'm involved in the MMT/GAP and MMT/Sage work, but @kohlhase is coordinating.

**Comment by kohlhase** [comment]
The work on this is done, we have mostly reported on this in Brussels, we only need to write this up. 
The main people involved in this are @pdehaye, @nthiery, @markuspf, @tkw1536 and myself I think. We should have most of the parts lying around somewhere for GAP (after all this was part of the CICM 2016 paper). 
BUT for SAGE, this needs to be written up, I am hoping for a contribution from @nthiery there (and maybe some improvements of the export now that he has thought about this some more).

**Comment by kohlhase** [comment]
Incidentally, we made good progress on D6.8 (which is due in one year). @markuspf summarizes this as 
```
We
have been working quite hard on multiple fronts over the last weeks:

 - Making an effort to develop theories for permutation groups
 - Actually setting up the MitM environment (and this was much more work
   than one might think: Victor had to work with and fix 3 different
   SCSCP implementations (GAP, MMT, Python), and setup 3 bits of
   software. We went with singular instead of Pari because there at
   least I know people who I can ask when there are problems.

One of the main big things I set Victor up to do right now is to hae a
reliable setup for MitM experiments, that is a simple way to install
GAP, MMT, Singular, Python, with all the SCSCP connections there so that
this example use case becomes doable.

The example use case is to act on singular polynomials with GAP
permutation groups (and Victor thinks he knows how to do this now; I
have faint hopes it might materialise this week).
```
We are planning to submit a paper on this soon, (authors to be deterined), so we could probably already give a preview.

**Comment by nthiery** [comment]
On Thu, Aug 17, 2017 at 06:50:59AM +0000, Michael Kohlhase wrote:
>    The work on this is done, we have mostly reported on this in Brussels,
>    we only need to write this up.
>    The main people involved in this are [1]@pdehaye, [2]@nthiery,
>    [3]@markuspf, [4]@tkw1536 and myself I think. We should have most of
>    the parts lying around somewhere for GAP (after all this was part of
>    the CICM 2016 paper).
>    BUT for SAGE, this needs to be written up, I am hoping for a
>    contribution from [5]@nthiery there (and maybe some improvements of the
>    export now that he has thought about this some more).

Thanks Michael for the feedback and the update on ongoing work!

I thought about it a bit more, but that has not been exercised with
practical use cases, and that's what's needed now to get from nebulous
thoughts to concrete actions. I guess what I need is to get together
with your team, like Markus did. Fall is going to be busy with
teaching, but freeing myself for a 2-3 days visit should be doable. A
variant would be to discuss this in Orsay with @florian-rabe when he
will be here.

**Comment by bpilorget** [comment]
#138 was merged into  #139 after the 3rd amendment to the contract

**Comment by bpilorget** [comment]
#135 was merged into #139 and #142 after 3rd amendment to the contract

**Comment by bpilorget** [comment]
I reopened this issue as I haven't found any written report yet.

**Comment by kohlhase** [comment]
We are currently working on the LMFDB part in practice now. The genreal framework has been published on MACIS. This will take a little more time; but it would be good to finish that for a meaninful  report (which we can generate mostly from the MACIS paper).

**Comment by kohlhase** [comment]
I have (finally) assembled/spliced the parts from the MACIS papers into a (somewhat coherent) story, which is in the repository. It still contains duplicates and some of the recent LMFDB work needs to be integrated as well. I will be working on this some more in the next days, pinging @Jazzpirate,   @nthiery, and @JohnCremona for input.

**Comment by JohnCremona** [comment]
Michael, is that D6.5/report.tex?  When I try to process that I get an
error:

! LaTeX Error: File `eudelivreport.cls' not found.

Should I have that file?

John

**Comment by kohlhase** [comment]
Indeed you have that: it is part of the ODK repository (which I assume to be at `<DIR>`)
You should set your `TEXINPUTS` variable with something like 
```
export TEXINPUTS="<DIR>/OpenDreamKit/Proposal/LaTeX-proposal//:$TEXINPUTS"
```
Then it will be found.

**Comment by kohlhase** [comment]
@JohnCremona it would be very helpful, if you could write a very high-level description of your use case (see ednote 7).

**Comment by JohnCremona** [comment]
On 3 July 2018 at 16:14, Michael Kohlhase <notifications@github.com> wrote:

> Indeed you have that: it is part of the ODK repository (which I assume to
> be at <DIR>)
> You should set your TEXINPUTS variable with something like
>
> export TEXINPUTS="<DIR>/OpenDreamKit/Proposal/LaTeX-proposal//:$TEXINPUTS"
>
> Then it will be found.
>

Thanks, that now works (I didn't know about the double trailing //).  Now i
get other latex errors, starting with

Runaway argument?
{\small Progress on and finalization of this deliverable has been tra\ETC.
! Paragraph ended before \multicolumn was complete.
<to be read again>
                   \par
l.135 \maketitle

**Comment by kohlhase** [comment]
hmmm, weird, I had fixed this error this morning. Are you sure you have pulled lately?

**Comment by JohnCremona** [comment]
On 3 July 2018 at 17:02, Michael Kohlhase <notifications@github.com> wrote:

> hmmm, weird, I had fixed this error this morning. Are you sure you have
> pulled lately?
>
Definitely!

**Comment by kohlhase** [comment]
Could you pull again and check that 
```
%\usepackage{arydshln} % interacts negatively with proposal.cls
```
in `report.tex` is indeed commented out?

**Comment by JohnCremona** [comment]
On 3 July 2018 at 17:10, Michael Kohlhase <notifications@github.com> wrote:

> Could you pull again and check that
>
> %\usepackage{arydshln} % interacts negatively with proposal.cls
>
> in report.tex is indeed commented out?
>
I did (just white space change to report.tex I think), and that line is
commented out.

Perhaps I am using a different version of tex than you (mine is pdfTeX,
Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded
format=pdflatex 2017.8.23))

**Comment by kohlhase** [comment]
Mine is indeed different, but do not really believe that this is the problem. 
```
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
LaTeX2e <2018-04-01> patch level 5
```
I will commit the PDF for now (you can just ignore the error as well).

**Comment by JohnCremona** [comment]
On 3 July 2018 at 17:29, Michael Kohlhase <notifications@github.com> wrote:

> Mine is indeed different, but do not really believe that this is the
> problem.
>
> This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdflatex)
>  restricted \write18 enabled.
> entering extended mode
> LaTeX2e <2018-04-01> patch level 5
>
> I will commit the PDF for now (you can just ignore the error as well).
>

Thanks.  I can now look for ednote 7 and respond (probably tomorrow).

**Comment by nthiery** [comment]
On Tue, Jul 03, 2018 at 08:11:18AM -0700, John Cremona wrote:
>    ! LaTeX Error: File `eudelivreport.cls' not found.

I (semi-automatically) added it to the WP6/D6.5 directory (as we do
for the other deliverables) so that it won't be needed anymore to set
TEXINPUT. Now

        pdflatex report.tex

should work.

**Comment by JohnCremona** [comment]
On 4 July 2018 at 08:44, Nicolas M. Thiéry <notifications@github.com> wrote:

> On Tue, Jul 03, 2018 at 08:11:18AM -0700, John Cremona wrote:
> > ! LaTeX Error: File `eudelivreport.cls' not found.
>
> I (semi-automatically) added it to the WP6/D6.5 directory (as we do
> for the other deliverables) so that it won't be needed anymore to set
> TEXINPUT. Now
>
> pdflatex report.tex
>
> should work.


Thanks.  But on a different machine (yesterday I was using my laptop but I
don't have it with me right now), where TEXINPUT is set but just points to
a directory of my own, I still get an error:

Runaway argument?
{\small Progress on and finalization of this deliverable has been tra\ETC.
! Paragraph ended before \multicolumn was complete.
<to be read again>
                   \par
l.133 \maketitle

**Comment by nthiery** [comment]
>    Thanks. But on a different machine ...

That sounds like an orthogonal problem, so I am not surprised that
fixing the missing file did not resolve that one. I hope Michael will
be of better help!

**Comment by JohnCremona** [comment]
I have not yet had time to write what was needed on page 5 (EdNote7) and
will be away for 2 days, but will do so on Monday before our next
conference call (next Tuesday).

**Comment by kohlhase** [comment]
John, I have a couple more ednotes for you, just look for MK@JC.

**Comment by JohnCremona** [comment]
On 5 July 2018 at 17:51, Michael Kohlhase <notifications@github.com> wrote:

> John, I have a couple more ednotes for you, just look for MK@JC.
>

I think I have addressed the various places needed; also looked at all the
LMFDB parts.  I suggest that we offer to add David L-D as an author --
shall I?

At DLD's suggestion I added the line \usepackage{xstring} to the preamble
as he said that allowed him to process the file.  For me that helps and I
can process the file though I still get two errors at the point of
\maketitle.  But at least I could proceed.

**Comment by kohlhase** [comment]
I agree DLD should be a co-author. Sorry to have forgotten.

**Comment by nthiery** [comment]
Hi! What's the status for this report?
For info: I just took care of the ednote I was in charge for, and pushed. I had done a bit of proofreading in late July too.
Cheers,

**Comment by kohlhase** [comment]
I will finalize it when I am back tue/Wed next week.

**Comment by nthiery** [comment]
>    I will finalize it when I am back tue/Wed next week.

Ok! Thanks for the feedback.

**Comment by florian-rabe** [comment]
I've made a complete and substantial revision of the deliverable on September 1. [*]
This involved restructuring the text fragments, tightening their integration, and polishing everything.

[*] My commits include restoring work that I had done a month ago and that somehow got lost in between (at least partially due to my own mistakes, but I have no clue how what happened exactly).
I've been very careful to make sure everybody else's changes were preserved. Details are in my commit messages.

**Comment by kohlhase** [comment]
Dennis and I made a lot of progress on this report, and are almost finished. But I will need a bit more time. It will be done tomorrow.

**Comment by florian-rabe** [comment]
Let me know if there's anything for me to do. I'll catch up on sleep today but will check online from time to time. I can do another round tonight.

I noticed the new Sect. 5.4. Was there a special reason not to integrate it into Sect. 6?

**Comment by kohlhase** [comment]
> I noticed the new Sect. 5.4. Was there a special reason not to integrate it into Sect. 6?

yes, is is about the LMFDB interface theories (i.e. analogous to GAP/Sage/Singular), not about the virtual theories interface. 
But I should probably cross-reference it in both places and explain the difference.

**Comment by kohlhase** [comment]
@nthiery I went over the report a final time and substantially extended it in many cases (all ednotes can just be hidden (they would be good to keep for the Journal version). 

 I am turning it over to Florian for final editing; It should be ready to submit later today (I hope).

**Comment by kohlhase** [comment]
@florian-rabe your turn now.

**Comment by florian-rabe** [comment]
Is this still due M24 or has it also been officially moved to M36?

**Comment by nthiery** [comment]
>    Is this still due M24 or has it also been officially moved to M36?

I just checked, and it's apparently still M24:

- https://github.com/OpenDreamKit/OpenDreamKit/blob/master/Proposal/WorkPackages/WorkPackages.tex
- https://github.com/OpenDreamKit/OpenDreamKit/blob/master/Proposal/grantagreement-history.tex

**Comment by florian-rabe** [comment]
I've finished this deliverable. It's ready to submit.

I've kept M24 as the due date. Being one year late is awkward, but this is more comprehensive than other deliverables, which should help.

**Comment by nthiery** [comment]
Thanks Florian, Michael and everyone who contributed!
