### ISSUE TITLE
D6.6: Full-text search (Formulae + Keywords) over CAS Modules and Notebooks

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#140]
- **WP6:** [Data/Knowledge/Software-Bases](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP6)
- **Lead Institution:** Jacobs University Bremen
- **Due:** 2018-02-28 (month 30)
- **Nature:** Other
- **Task:** T6.10 (#132)
- **Proposal:** [p.55](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)

**Comment by bpilorget** [comment]
#140 was merged into #134 after the 3rd amendment to the contract
