### ISSUE TITLE
D6.7: GAP/ SAGE Interface Views OMDoc/MMT

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#141]
- **WP6:** [Data/Knowledge/Software-Bases](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP6)
- **Lead Institution:** Jacobs University Bremen
- **Due:** 2018-08-31 (month 36)
- **Nature:** Other

See page 55 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by bpilorget** [comment]
#68 and #141 were merged into #142 after the 3rd amendment to the contract.
