### ISSUE TITLE
D6.8: Curated Math-in-the-Middle Ontology and Alignments for GAP/SAGE/LMFDB

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#142]
- **WP6:** [Data/Knowledge/Software-Bases](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP6)
- **Lead Institution:** FAU Erlangen-Nürnberg
- **Due:** 2018-08-31 (month 36)
- **Nature:** Other
- **Tasks:** T6.3 (#125) and T6.8 (#130)
- **Proposal:** [p. 54](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)
- **[Final report](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP6/D6.8/report-final.pdf)** ([sources](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP6/D6.8/))

Work Package WP6 develops a novel, foundational, knowledge-based framework for interfacing existing open source mathematical software systems and knowledge bases into a mathematical VRE, where systems can delegate functionalities among each other seamlessly without losing semantics.
The overall Math-in-the-Middle (MitM) Framework developed in WP6 over the last three years is described in D6.5 (#139). This Report complements it by describing the curated contents Math- in-the-Middle (MitM) Ontology which serves as a reference and pivotal point for translations between the various input languages of mathematical software systems and knowledge bases.

In a nutshell, the MitM Ontology describes the mathematical objects, concepts, and their relations in a general, system-agnostic way in an OMDoc/MMT theory graph while the mathematical systems export API theories that describe the system interface language in terms of types, classes, constructors, and functions – again in OMDoc/MMT. These two levels of descriptions are linked by OMDoc/MMT alignments that allow the translation of expressions between systems.

Together with deliverable report [D6.5](https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP6/D6.5/report-final.pdf), this report describes the implementation and initial evaluation of the MitM integration and interoperability paradigm initially envisioned in deliverables D6.2 (#136) and D6.3 (#137) The MitM paradigm constitutes the core development goal of WP6, and the curated content described in this report enables running non-trivial integration case studies. In the future, we hope to further consolidate content, increase coverage of alignment, and greatly extend the reach of the integration both in terms of OpenDreamKit systems covered as well as knowledge available in the MitM Core ontology.

**Comment by bpilorget** [comment]
#135 was merged into #139 and #142 after 3rd amendment to the contract

**Comment by bpilorget** [comment]
#68 and #141 were merged into #142 after the 3rd amendment to the contract

**Comment by kohlhase** [comment]
I have started writing this deliverable.

**Comment by kohlhase** [comment]
@florian-rabe @Jazzpirate I made a first pass on this deliverable. This needs to be iterated, @Jazzpirate could you make a next pass?

@bpilorget could you see if the format is OK? @nthiery

**Comment by kohlhase** [comment]
@bpilorget, @nthiery we have completed this report. Please start the quality review procedures (and make any admin changes that need to be done).

**Comment by nthiery** [comment]
>    [1]@bpilorget, [2]@nthiery we have completed this report. Please start
>    the quality review procedures (and make any admin changes that need to
>    be done).

Excellent. Feels good to see progress! I'll try to get to this in the
coming days.

Do you know of anyone outside of ODK that would be genuinely
interested in the reported and willing to provide feedback?

**Comment by nthiery** [comment]
Not quite in the coming days, but I finally got to review the report; sorry for the delay.

Generally speaking, the report looks good; thanks! I made some minor edits and threw in some additional ednotes. In addition the abstract could be expanded according to our deliverable recommendations:
 
    Have an executive summary on the first page (just half a page).
    - why does this deliverable exist? (context)
    - have you achieved everything you set out to do?
    - what would be / are the next steps?

There is already quite some contextualization in the document, but the reviewer will be looking for contextualization w.r.t. the rest of the project (objectives, tasks, previous and future deliverables). The reports for earlier deliverables like D6.2 #136 were very nice in this respect; presumably some of the language can be recycled.

Thanks in advance!

**Comment by nthiery** [comment]
@kohlhase: the manual merge seems to have corrupted this deliverable report as well; it does not compile as of ead1e67705a7969de54b3ef5d861b145569419d0

**Comment by kohlhase** [comment]
I have fixed the corruption and have now started to read it.

**Comment by nthiery** [comment]
Hi @kohlhase; how is this going along?

**Comment by kohlhase** [comment]
I have pushed contextualization and some more content refactorign yesterday, but will need Mo/Tue to complete it.

**Comment by kohlhase** [comment]
Dennis and I made a lot of progress on this report, and are almost finished. But I will need a bit more time. It will be done tomorrow.

**Comment by kohlhase** [comment]
@nthiery this report is done now. I have updated also updated the issue description. Sorry for being after the deadline.

**Comment by nthiery** [comment]
Submitted! Thanks for all the work.

**Comment by IzabelaFaguet** [comment]
Accepted by the EU on December 5th.
