### ISSUE TITLE
T7.1: Social Science Input to Design

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#144]
- **WP7:** [Social Aspects](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP7)
- **Lead Institution:** University of Oxford
- **Partners:** University of Oxford, Université Paris-Sud
- **Work phases:** 0-3!.5,12-42!.5

See page 56 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by bpilorget** [comment]
Cancelled after 3rd amendment to the contract. Person-Months reallcoated to WP3
