### ISSUE TITLE
T7.2: Implications of VREs for Publication

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#145]
- **WP7:** [Social Aspects](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP7)
- **Lead Institution:** University of Sheffield
- **Partners:** University of Oxford
- **Work phases:** 12-42

See page 56 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by bpilorget** [comment]
Cancelled after 3rd amendment to the contract. Person-Months reallcoated to #29
