### ISSUE TITLE
T7.3: Mechanism Design for Free Software Development

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#146]
- **WP7:** [Social Aspects](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP7)
- **Lead Institution:** University of Oxford
- **Partners:** None
- **Work phases:** 6-48!.5

See page 57 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by bpilorget** [comment]
Cancelled after 3rd amendment to the contract. Person-Months reallocated to #50, #52 and #105
