### ISSUE TITLE
T7.4: Evaluation of Micromagnetic VRE

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#147]
- **WP7:** [Social Aspects](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP7)
- **Lead Institution:** University of Southampton
- **Partners:** University of Oxford, Université Paris-Sud
- **Work phases:** 32-44!0.5

See page 57 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by bpilorget** [comment]
#147 was merged to #31 after the 3rd amendment to the contract
