### ISSUE TITLE
D7.2: TRAC add-on to manage ticket prioritisation

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#149]
- **WP7:** [Social Aspects](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP7)
- **Lead Institution:** University of Oxford
- **Due:** 2017-08-31 (month 24)
- **Nature:** Other

See page 58 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by bpilorget** [comment]
@dimpase @embray  This deliverable is officially due for 31/08/2017. Can you please report on the progress you have achieved?
Thanks in advance

**Comment by dimpase** [comment]
This is a deliverable that would disappear together with WP7. I think the most meaningful would be to request an extension on it, while we wait for our proposal on WP7 to be accepted.

**Comment by bpilorget** [comment]
Cancelled after 3rd amendment to the contract
