### ISSUE TITLE
D7.3: Demo: Mechanism for comments on posted Jupyter notebooks

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#150]
- **WP7:** [Social Aspects](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP7)
- **Lead Institution:** University of Sheffield
- **Due:** 2017-08-31 (month 24)
- **Nature:** Demonstrator

See page 58 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by dimpase** [comment]
We work on it, and already have a [paper](http://dblp.org/rec/journals/corr/IgarashiE16) on this.

**Comment by alex-konovalov** [comment]
Could you point out where to look - it's 22 pages long and it's not obvious to me. Please also remember to acknowledge the project (see http://opendreamkit.org/acknowledge/)

**Comment by dimpase** [comment]
@alex-konovalov : wrong link - fixed.

**Comment by dimpase** [comment]
and a wrong place - it must go to #154

**Comment by bpilorget** [comment]
@mikecroucher @dimpase This deliverable is officially due for 31/08/2017. Can you please report on the progress you have achieved?
Thanks in advance

**Comment by bpilorget** [comment]
Cancelled after 3rd amendment to the contract
