### ISSUE TITLE
D7.4: Demo: Jupyter Notebook Live Poster

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#151]
- **WP7:** [Social Aspects](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP7)
- **Lead Institution:** University of Sheffield
- **Due:** 2018-08-31 (month 36)
- **Nature:** Demonstrator

See page 58 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by bpilorget** [comment]
Cancelled after 3rd amendment to the contract
