### ISSUE TITLE
D7.5: Report on relevant research in sociology of mathematics and lessons for design of OpenDreamKit VRE, parts I-III, with part I (resp. II) due at month 3 (resp. 24)

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#152]
- **WP7:** [Social Aspects](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP7)
- **Lead Institution:** University of Oxford
- **Due:** 2019-02-28 (month 42)
- **Nature:** Report

See page 58 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by nthiery** [comment]
Hi @dimpase: "Part I on Month 3" was an informal deadline; still we may want to reschedule this; maybe for the informal project review in June?

**Comment by dimpase** [comment]
yeah, sure, let us reschedule to June.

**Comment by dimpase** [comment]
It seems I forgot to link here the annotated bibliography that we [got](https://github.com/dimpase/abib) on this.

**Comment by bpilorget** [comment]
Cancelled after 3rd amendment to the contract
