### ISSUE TITLE
D7.6: Review of new publication mechanisms, including evaluation of demonstrator projects

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#153]
- **WP7:** [Social Aspects](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP7)
- **Lead Institution:** University of Sheffield
- **Due:** 2019-02-28 (month 42)
- **Nature:** Report

See page 58 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by bpilorget** [comment]
Cancelled after 3rd amendment to the contract
