### ISSUE TITLE
D7.7: Game-theoretic analysis of development practices in open-source VREs

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#154]
- **WP7:** [Social Aspects](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP7)
- **Lead Institution:** University of Oxford
- **Due:** 2019-02-28 (month 42)
- **Nature:** Report

See page 58 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by dimpase** [comment]
We work on it, and already have a [paper](http://dblp.org/rec/conf/atal/PavlouE16) on this.

**Comment by bpilorget** [comment]
Cancelled after 3rd amendment to the contract
