### ISSUE TITLE
D7.8: Micromagnetic VRE environment evaluation report

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#155]
- **WP7:** [Social Aspects](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP7)
- **Lead Institution:** University of Southampton
- **Due:** 2019-08-31 (month 48)
- **Nature:** Report

See page 58 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by bpilorget** [comment]
#155 was merged into #38 after 3rd amendment to the contract
