### ISSUE TITLE
First informal review

### ISSUE THREAD

**Issue by nthiery** [OpenDreamKit/OpenDreamKit#156]
A first, informal, [review will happen 6 months from the start date](http://opendreamkit.org/2016/06/27/ODK_project_meetings_review_and_workshop_in_Jacobsuni/)

In that meeting there will be the experts who will review and assess
the progress of the project. This means reviewing the deliverables
which have a deadline prior to this review date: #17  and #18,
#34, #58 and #61, #83 and #91, #107.

Other participants will basically be those from the projects responsible for these deliverables and the Project Officer. There will be two or three reviewers. Due to the informal nature of this first review, the PO may invite just two.

This issue is for organizing this review.

TODO:
- [x] Announce the June review and workshop as a post on the web site:
       http://opendreamkit.org/meetings/2016-06-27-Bremen/agenda/
- [x] ...
- [x] Send report to the participants

**Comment by annihellman** [comment]
We first just need to agree on the date for the review, somewhere in March. Then we discuss whether it is in Brussels - normally they are here - or whether for a specific reason the review should take place at another location. We will pick the experts and we will then distribute the deliverables to them to read and assess, in due time. I am sure it will be very, very interesting. regards, the PO :-)

**Comment by pdehaye** [comment]
:+1: :clap:

**Comment by kohlhase** [comment]
So which participants should really come from our side?

**Comment by annihellman** [comment]
The project coordinator and those partners who were responsible for the deliverables that had a delivery date prior to the review, so that they can demonstrate the deliverables and results.
