### ISSUE TITLE
Participation to the 11th e-concertation meeting

### ISSUE THREAD

**Issue by nthiery** [OpenDreamKit/OpenDreamKit#158]
We attended the 11-th e-concertation meeting in  Brussels for meeting other e-infrastructure projects on November 9th. We were registered for the following parallel sessions:
- Open scholarship (afternoon)
- HPC Cluster with Centers of Excellence (morning)
- Skills and Training (afternoon)

PO Dehaye further suggested:
- Integration of data and computing services (afternoon)
# Participants from ODK:
- @nthiery (9th-10th) 
  Sessions:  "Earth sciences, energy and environment" and "Integration of data and computing services"
- @fangohr (8th-9th) 
  Sessions: "HPC cluster with Centers of Excellence" and "Skills and Training"
- @defeo (9th) 
  Sessions: "Humanities and Social sciences" and "Open Scholarship"
- @ClementPernet (9th)
  Sessions: "HPC cluster with Centers of Excellence" and "Open Scholarship"

@nthiery used the occasion for a longer meeting with ODK's Project Officer on the 10th.
# Documents
- [announce.txt](https://github.com/OpenDreamKit/OpenDreamKit/files/2948/announce.txt)
- [Project Allocation](https://github.com/OpenDreamKit/OpenDreamKit.github.io/raw/master/meetings/2015-11-09-EConcertation/ProjectAllocation.pdf)
- [Agenda](https://github.com/OpenDreamKit/OpenDreamKit.github.io/raw/master/meetings/2015-11-09-EConcertation/Agenda.pdf)
- [Participant Booklet](https://github.com/OpenDreamKit/OpenDreamKit.github.io/raw/master/meetings/2015-11-09-EConcertation/ParticipantBooklet.pdf)
# Debriefing notes

The meeting involved about 100 persons from all e-infrastructure projects, a fraction of which was about VRE's. The average age was maybe around 55, when our was more 40. It felt like we also stranded out because we have a strong user perspective in ODK (most of us are users as much as devs), when most other persons are infrastructure providers. There was one hour of general presentation, followed by two sequences where people would split by session, and then gather again to report on the session, pointing out tentative joint actions. And then quite some free time for networking.

The primary goal of the meeting was to search for potential synergies between the projects. I was not very much convinced about the format. Besides the project abstracts (which are rather formal) and, in some sessions, a two sentence presentation of each participant, there were few occasions to learn about the actual content of other projects. I see the idea behind the thematic discussions; but in practice it
seems quite hard to run productively, and the discussion ended up being rather artificial in those discussions I attended. The session on OpenScholarship attended by @ClementPernet  and @defeo was actually of great interest. In particular it triggered discussions on the support for open-data/open-access and possibly open-source by the EU commission. In the HPC session, the point was made by participants that research focus should not be exclusively on the 'exa scale' of high performance computing, but that much impact comes from developing codes, tools and training that are applicable now (as in 'the next six months'). This is also the time scale that is of relevance to industry: What can I do within the next year, not what might be possible within 5 years.

The networking sessions were on the other hand productive, thanks to our Project Officer that knew many people around and could introduce us. The main contacts we got were with the grid/cloud providers (in particular EGI), with GEANT, in particular about our task T2.10 Computational mathematics resources indexing service (#33), and with the Barcelona Super Computing center, where we discussed on the use of their SMPs runtime system for distributed computing.

Suggestions for the commission:
- Make it possible, whenever possible, to access the full text of all project descriptions, in particular tasks and deliverables, with the possibility to do searches on all projects at once.
- Maybe have a poster session, organized in such a way that it would be easy to glance through, e.g. all posters of all VRE projects. It also would make it easy to find persons from a given project.

The other important goal of the meeting is for the commission to get feedback to shape upcoming e-Infrastructure calls. This makes sense: the meeting gathers many experts of the field. At the same time this introduce a bias in favor of the topics of the already funded project. De facto several participants I discussed with informally admitted they were mostly coming to the meeting for lobbying, to ensure that the next calls would be adapted to their needs. Clément involuntarily ended up doing such lobbying. But that was in favor of green access / open source, so that's for the bright side :-)
# Meeting with our Project Officer

On the 10th in the Morning, @nthiery met with our Project Officer Anni Hellman (@annihellman). We first exchanged a bit on our personal career paths and interests in the project. We are lucky to have a PO with a genuine interest in mathematics, in particular from past training and work in the theory of languages in Turku, Finland. We discussed about the project in general and how to best manage it (appropriate granularity of flexibility for the tasks, deliverables, and involvements of the partners; what is internal cuisine and what requires approval from the PO or amendments in the agreements).

We navigated together our web and github pages; they can still be improved but are already a workable way for outsiders and reviewers to track our activity.

There will be an informal review this spring, covering all deliverables due before Month 6. This would be best done at the occasion of a joint workshop, so that the reviewers and Anni could get a feeling of the whole community at work. This could typically be during our next yearly meeting which we are thinking to run in June, assuming that we can find a date that would work for everybody.

We also discussed briefly the Quality Review Board (also with @HansFangohr on Monday). Our [current tentative list](https://github.com/OpenDreamKit/Participants/blob/master/QualityReviewBoard.md) sounds appropriate; one more external person would be good.

@annihellman recommended to initiate a discussion between the various VRE projects on the [digital4science](https://ec.europa.eu/futurium/en/digital4science/ideas/e-infrastructure) platform, to search for potential synergies.

**Comment by defeo** [comment]
I should be able to attend, might have to move some classes though. I'll be fixed next week.

**Comment by defeo** [comment]
I will attend, assuming I can arrange to buy the tickets: for the moment, I haven't heard from the UVSQ financial services yet.

**Comment by defeo** [comment]
How do we assign ourselves to the sessions? I think I promised @nthiery I'd be attending the Open Scolarship session in the afternoon, and I am still fine with that. If @fangohr is attending the Skills and Training session, I guess @nthiery will be attending the Integration of data etc. session.

But what about the morning? Any other relevant sessions apart the HPC one? I doubt the Biomedical and Earth sciences sessions are relevant to us. The Humanities session may be, but I don't feel competent for that.

**Comment by nthiery** [comment]
It seems indeed unrelated to ODK, but I'd be personally interested in the Earth science session (to report to my wife). So if you could attend the social sciences session, and report if there is anything relevant to us, that would be nice. You have insight on the social aspects of software dev :-)

**Comment by nthiery** [comment]
I made some preallocation in the issue description; feel free to update, adjust, complement.

**Comment by defeo** [comment]
Ok, I'll report to my partner about humanities and social sciences :)

**Comment by fangohr** [comment]
Just to confirm that I will attend the HPC session.

**Comment by ClementPernet** [comment]
Hi,
I also confirm that I'll attend the first day (9th) for the HPC session.

**Comment by nthiery** [comment]
@ClementPernet, @fangohr, @defeo: can you have a look at my debriefing notes above, and complement them? Then I'll send a copy on the participants mailing list.
I still need to add notes about the meeting with our PO. Will do later ...

**Comment by ClementPernet** [comment]
Thanks Nicolas. This is summarizes well my experience of the meeting. I edited your text with some additional info on the Openscholarship meeting and contacts I had with the Barcelona SCC group.

**Comment by ClementPernet** [comment]
Also, for the next such meetings: prepare a stack of buisness cards. I felt like a tourist with them!

**Comment by nthiery** [comment]
+1!

**Comment by defeo** [comment]
:+1:
