### ISSUE TITLE
Flagging of interesting and maybe relevant project: sandstorm.io

### ISSUE THREAD

**Issue by pdehaye** [OpenDreamKit/OpenDreamKit#160]
Hi everyone,

Here is a project that might turn out to be relevant to OpenDreamKit a little bit further down the road: http://www.sandstorm.io , also at https://github.com/sandstorm-io

The main idea is to decouple hosting and software development, yet facilitate collaboration and deployment of new (open source) software. From a VM it is extremely easy to install, and provides some sort of app store of open source software with a federated system of authentication, and enhanced sharing features. Sandstorm is meant to be another packaging option for open-source software, beyond the traditional ones that require high level of access to a machine.

One can get for instance in just a few clicks to a SageMathCloud-like form of live sharing of Jupyter notebooks (purely peer to peer though, without necessarily the distinction educator/student that SMC has for homeworks). Another example would be the hosting of a git repository, through GitLab.

**Comment by defeo** [comment]
> Here is a project that might turn out to be relevant to OpenDreamKit a little bit further down the road: http://www.sandstorm.io , also at https://github.com/sandstorm-io

If it's still alive then... Did you grasp their business model?

Looks like Yet Another Hip Silicon Valley Start-up. They even require
packagers to have a keybase.io account (which is still in alpha,
invitation only, and has a [very vague business
plan](https://keybase.io/blog/2015-07-15/keybase-raises-series-a#the-business)).
Very cool ideas, great ideological stances, caged in the free market.

Yet, it's a step forward compared to other general purposes VREs we've seen...

> One can get for instance in just a few clicks to a SageMathCloud-like form of live sharing of Jupyter notebooks

Are you making this example up from a purely theoretical perspective,
or is there a Jupyter app in the marketplace? I couldn't find any.

**Comment by pdehaye** [comment]
There is a post about the business model [on their blog](https://blog.sandstorm.io/news/2015-01-15-sandstorm-1.3M-seed-round-pay-it-forward.html). 

I didn't know keybase was still invitation-only, thanks for that information. 

> Caged in the free market.
Isn't this the reality of the vast majority of software development for infrastructure, once it reaches a certain stage? OpenDreamKit is somehow at the bleeding edge of the amount of infrastructure work done within academia. 

There is an IPython Notebook app, packaged Aug 20th.

**Comment by defeo** [comment]
> I didn't know keybase was still invitation-only, thanks for that information.

If you happen to have spare invitations, btw, I am interested :)

> Caged in the free market.
> Isn't this the reality of the vast majority of software development for infrastructure, once it reaches a certain stage?

Of course. SMC and William's tribulations are a clear example of this.

> There is an IPython Notebook app, packaged Aug 20th.

Oh, I was looking for Jupyter. Silly me!

**Comment by defeo** [comment]
BTW, [Cap'n proto](https://capnproto.org/), by the same people, could be relevant to #51.
