### ISSUE TITLE
Knowledge representation in LMFDB

### ISSUE THREAD

**Issue by pdehaye** [OpenDreamKit/OpenDreamKit#163]
This issue is part of a larger set of tasks listed at #162. For the LMFDB specifically, look at [survey-LMFDB.md](https://github.com/OpenDreamKit/OpenDreamKit.github.io/blob/master/meetings/2016-01-25-DKS/survey-LMFDB.md)

**Comment by pdehaye** [comment]
@JohnCremona : Let me know if you have something to add or clarify to the draft answers listed above. Thanks!

**Comment by JohnCremona** [comment]
On 14 December 2015 at 12:54, pdehaye <notifications@github.com> wrote:

> @JohnCremona <https://github.com/JohnCremona> : Let me know if you have
> something to add or clarify to the draft answers listed above. Thanks!
>

Thanks for making a good start on this.  I do have some comments, some of
which reflect rather recent changes and decisions made during the
just-finished semester at ICERM which included weekly LMFDB working
sessions.

About uploading of data: "This option is still there, but sees little
use."  This has never been a realistic option, and is not even visible
unless a user of the website is a developer with an account and is logged
in.  Perhaps best to say "This option has never been used seriously, and is
not currently supported."

"In general, proper referencing of data sources and documentation of its
quality is a struggle."   Progress has been made on these through a new
collection of "data quality" knowls, see
http://www.lmfdb.org/knowledge/?category=dq .  This only started within the
last few weeks but the intention is to have source / extent / quality /
reliability all documented for the main sections of the database by next
March's workshop.  As an example, see all elliptic curve pages such as
http://www.lmfdb.org/EllipticCurve/Q/  there is a "Learn more about"
section in th euppoe right which links to these knowls.

Under "How is [the data] changed" we could say more though it is not
uniform across the LMFDB.  In the best cases, the data is stored completely
separately fom the LMFDB's own (mongo) database, e.g. in my ecdata github
repository, under full revision control of text files;  and there are
scripts to populate the d.b. from that.

The process of documenting the data formats is ongoing, as has been driven
recently by the writing of the API by Harald Schilly -- all very new.

I don't know if it is relevant here but we are also accumulating a set of
bibliographic references and have already instuted a system for making
citations within knowls very easy.

**Comment by pdehaye** [comment]
Thanks for your response, very helpful!
I will take care of including those comments. I see that LMFDB made a lot
of recent efforts to streamline procedures, document, etc. Will make sure
to include as much of these in the end report, there is lots of valuable
experience there.

**Comment by pdehaye** [comment]
Closing, thanks for doing this, @JohnCremona. Will ask for review of LMFDB part when #123 is ready.
