### ISSUE TITLE
Knowledge representation in GAP

### ISSUE THREAD

**Issue by pdehaye** [OpenDreamKit/OpenDreamKit#165]
This issue is part of a larger set of tasks listed at #162. For GAP specifically, look at [survey-GAP.md](https://github.com/OpenDreamKit/OpenDreamKit.github.io/blob/master/meetings/2016-01-25-DKS/survey-GAP.md)

**Comment by pdehaye** [comment]
Hi, @markuspf ! Thanks for volunteering for this. See above for all you need to know, or ask questions here!

**Comment by pdehaye** [comment]
Have you started work on this, @markuspf ?

**Comment by pdehaye** [comment]
ping ping @markuspf

**Comment by pdehaye** [comment]
@markuspf Can you link to your presentation here? Thanks!

**Comment by pdehaye** [comment]
Please include the map of GAP filters that @stevelinton showed.

**Comment by alex-konovalov** [comment]
@pdehaye, @stevelinton: I am working on making it with [yEd](https://www.yworks.com/products/yed) - hope to have it shortly.

**Comment by stevelinton** [comment]
Warning: This message has had one or more attachments removed
Warning: (typesall.dot.pdf).
Warning: Please read the "StAndrews-Attachment-Warning.txt" attachment(s) for more information.

Here is the actual map I showed.


This is a message from the University of St Andrews IT Service Desk
----------------------------------------------------------------------------
The original e-mail attachment "typesall.dot.pdf"
is on the list of unacceptable attachments for this site and has been 
replaced by this warning message.

If you wish to receive a copy of the original attachment, please e-mail 
helpdesk@st-andrews.ac.uk and include the whole of this message in your 
request.

At Mon Jan 25 20:24:44 2016 the virus scanner said:
   MailScanner: Attempt to hide real filename extension (typesall.dot.pdf)

Note to IT Service Desk: Look on the St Andrews (the StAndrews (mcgraw) MailScanner) MailScanner 
in /var/spool/MailScanner/quarantine/20160125 (message u0PKOhWp011104).
--
IT Service Desk
University of St Andrews
www.st-andrews.ac.uk

**Comment by stevelinton** [comment]
Here is the actual map I showed.

**Comment by alex-konovalov** [comment]
@stevelinton could you attach the image via web-interface please? It seems that email does not permit this :(

**Comment by stevelinton** [comment]
[typesall-dot.pdf](https://github.com/OpenDreamKit/OpenDreamKit/files/104025/typesall-dot.pdf)

**Comment by alex-konovalov** [comment]
These are maps of representations, categories and a big one of all filters. I've selected some automated layouts available in yEd, one could try to apply different layouts and their fine-tuning parameters to try to find most optimal arrangement.
![biggraph](https://cloud.githubusercontent.com/assets/5751387/12568083/1aafe42c-c3bb-11e5-9e6f-9371231e8c86.png)
![catgraph](https://cloud.githubusercontent.com/assets/5751387/12568084/1ab65fb4-c3bb-11e5-9706-86dd5390649e.png)
![repgraph](https://cloud.githubusercontent.com/assets/5751387/12568085/1ab8fb02-c3bb-11e5-9650-4afc78d10f04.png)

**Comment by pdehaye** [comment]
Thanks a lot, to both! Maybe @alex-konovalov you could attach the sources. I am assuming your input to yEd was something I could read into yEd again, and would be easier to read into another system like MMT? 
@kohlhase this might be worth looking at... The bottom graphs have rich structure that might be good to think about, and might genuinely help understand GAP.

**Comment by alex-konovalov** [comment]
Here there are the yEd files. It's very entertaining to play with different automated layouts. We have the data in GAP, so perhaps we may output them in some format which MMT could import - let's look tomorrow. 

[yedfiles.zip](https://github.com/OpenDreamKit/OpenDreamKit/files/104229/yedfiles.zip)

**Comment by alex-konovalov** [comment]
Now the graph containing both categories and representations denoted by corresponding colour (**C**yan stands for **C**aterogies, **R**ed for **R**epresentations)
![biggraph](https://cloud.githubusercontent.com/assets/5751387/12579909/5a8351a2-c423-11e5-82d0-9ab667ece432.png)
.

**Comment by alex-konovalov** [comment]
The next version of the graph is a 14 Mb .png file which is available here: http://alexk.host.cs.st-andrews.ac.uk/gap/typesystem/biggraph_pkg.png. Now it includes also GAP packages, loading not all but at least as much I've managed in my GAP 4.8.1 installation. Now darker cyan and read are for categories and representation in the core system, while light cyan and orange are for those in packages. 

The graph for the core system has 540 vertices, 759 edges, and 8 connected components. With loaded packages, it gets 1616 vertices, 2178 edges and 17 connected components. This statistics is speaking for itself.

**Comment by pdehaye** [comment]
Hi all,
We (KWARC + I) are working on D6.2 (due in a couple days) and we are still missing formal input from GAP people to this. There was a survey at [https://github.com/OpenDreamKit/OpenDreamKit.github.io/blob/master/meetings/2016-01-25-DKS/survey-GAP.md](survey-GAP.md). I know you have effectively answered these questions orally or through your papers, but if you filled it, your completed survey would fit the same structure as Sage, FindStat and LMFDB survey responses. Feel free to edit directly the Markdown file and signal here afterwards. Thanks!

**Comment by alex-konovalov** [comment]
@pdehaye I've just pushed update of survey-GAP.md](https://github.com/OpenDreamKit/OpenDreamKit.github.io/blob/master/meetings/2016-01-25-DKS/survey-GAP.md) - is that OK? @markuspf anything to add?

**Comment by pdehaye** [comment]
Thanks, yes, excellent!
