### ISSUE TITLE
OpenDreamKit contributions to the e-infrastructure document

### ISSUE THREAD

**Issue by annihellman** [OpenDreamKit/OpenDreamKit#167]
Dear OpenDreamKit partners, 
let me wish you a great 2016! And let me remind you of the message which was sent to all our project coordinators on 17 December. OpenDreamKit has not to my knowledge yet responded to it.
It would be good to have you in. The final result should have a page describing your project!
Best regards, Anni Hellman, your PO.

"Dear project manager,

Thank you for participating to our webinar that explored new ways for European e-infrastructures projects to collaborate.  For those of you who couldn't attend, we discussed a joint exercise that should enable us to show how H2020 e-Infrastructure projects help researchers in Europe and around the world to do excellent science. 

The idea is to compile a document emphasising the complementarity of e-infrastructures to a broad audience and a document aimed at the research community assessing the services offered and positioning H2020 WP14-15 eInfra projects with respect to similar initiatives and to national and regional e-infrastructures.

You can find the slides presented enclosed. They are also available online via http://ec.europa.eu/digital-agenda/en/news/webinar-exploring-synergies-overlaps-and-gaps-follow-e-infrastructures-e-concertation-meeting where you can also find a recording of the webinar.

 

I would like to stress again the first milestones for this exercise:

•	By 22 December:
•	Projects to send names of contributors
•	Projects to indicate willingness to help me with the draft versions (if possible those following-up on e-concertation meeting actions to avoid overlaps) 
•	By 15 January 
•	Projects to provide their one-pager 
•	Projects to suggest use cases and testimonials 
•	By 12 February 
•	Draft table of contents for the non-technical 10-page document 

Could you please provide us with the requested information before going on well-deserved holidays?
Let me wish you again a Merry Christmas and Happy New Year! Looking forward to a fruitful 2016.

Augusto"

**Comment by nthiery** [comment]
Dear Anni,

My best wishes as well for 2016!
Thanks a lot for the reminder, even better as a github issue.

Collaboration with other infrastructure projects, and in particular the H2020 ones is indeed very important. We have already taken several other steps to collaborate with other projects (some of which started at the e-Concertation meeting).

I am not sure how productive the above joint e-infrastructure document approach will be and haven't put the highest priority on it. Yet I agree that it's worth a try, and it would be good for OpenDreamKit to participate to the effort. Writing a one pager by Friday should be doable, starting from our existing documents.

Anybody interested in joining (or even better leading) the effort?

@OpenDreamKit/coordination
@OpenDreamKit/steering 

Best regards,
                                                  Nicolas

**Comment by bpilorget** [comment]
A new document was created  here, under "communication" section: https://github.com/OpenDreamKit/OpenDreamKit/blob/master/Communication/E-infrastructure%20projects%20document.tex

I've added the two texts already in the Grant agreement, which can be a base to the document asked for.

**Comment by bpilorget** [comment]
The one-pager document to be written must contain:
-High-level service catalogue: existing services & services under development

**Comment by annihellman** [comment]
Dear all, thanks for getting started with this. as this is a new project, it is important that it shortly describes what area it will cover ("what problem it will solve") and what the end result will eventually look like. what services will be available for the various relevant stakeholder groups. All that very shortly into one page. A marketing document, basically. :-)

**Comment by szegedip** [comment]
This is Peter from GÉANT (the large e-Infrastructure project). I would kindly offer my liaison to GÉANT and any of our activities, as you feel appropriate. BTW, I'm responsible for the eduOER service development of GÉANT that aims at aggregating metadata from various multimedia content/OER repositories of the research and education community and making them available in an open, structured and linked fashion.

**Comment by nthiery** [comment]
For info: @bpilorget wrote a first draft that I still need to proofread and complete. I did not manage to squeeze that in yesteday; hopefuly tonight, otherwise Monday morning.

@szegedip: thanks for your post!

**Comment by nthiery** [comment]
I wrote a first draft, starting from the suggestions by Benoit and with proofreading by Sam (thanks!)
See:
https://github.com/OpenDreamKit/OpenDreamKit/blob/master/Communication/eInfra-Booklet/ODK.md

Comments? Suggestions? Feel free to edit the file directly. I plan to submit it tomorrow. I guess it's still possible to update it in the coming days.

**Comment by bpilorget** [comment]
Do you validate this @nthiery ? https://github.com/OpenDreamKit/OpenDreamKit/blob/master/Communication/eInfra-Booklet/ODK.md

**Comment by bpilorget** [comment]
ODK one-pager is now shared on the google doc. Issue is closed
