### ISSUE TITLE
Improve our website for reviewers and followers

### ISSUE THREAD

**Issue by nthiery** [OpenDreamKit/OpenDreamKit#173]
Our website could be improved to ease the tracking of our activities by our reviewers and followers,
in particular toward the preparation of the upcoming informal review in June 2016. Please expand on the following list:
- [x] Add a "reports" section to http://opendreamkit.org/follow/, with an itemized list of all reports and minutes (deliverables, worshops, meetings) sorted by date
- [ ] Include all minutes from passed meetings
- [x] Make sure that all deliverables point to the pdf of the report submitted to the EU website
- [x] #172
- [x] Update the minutes of January 2016's meeting with crosslinks for all deliverables/...
- [ ] #220 
- [ ] ...

See also the website issues at https://github.com/opendreamkit/opendreamkit.github.io/issues

**Comment by nthiery** [comment]
I am updating the milestone to Month 18, in preparation for the formal review that will occur then.

**Comment by bpilorget** [comment]
Team of interns to propose evolutions to Coordinator and WP2 leader by Spring 2018

**Comment by bpilorget** [comment]
3 trainees in communication and dissemination are currently working on this topic.
