### ISSUE TITLE
Integrate OpenDreamKit social metrics into dissemination report

### ISSUE THREAD

**Issue by pdehaye** [OpenDreamKit/OpenDreamKit#178]
As a KPI metric for dissemination efforts, we might want to include follower counts on social media. Just a suggestion at this stage.

**Comment by alex-konovalov** [comment]
I would suggest the online impact of OpenDreamKit should be tracked with the help of http://impactstory.org/. The pipeline is as follows: get a DOI (e.g. archive your slides on https://zenodo.org/), add the output to your ORCID profile (http://orcid.org/), and then update your ImpactStory record. An example what it may report: https://impactstory.org/u/0000-0001-5299-3292/p/f4n7DjTiYy.

**Comment by alex-konovalov** [comment]
Another idea is to use Altmetric's API https://www.altmetric.com/products/altmetric-api/. 

Also (for Python and R only so far): http://depsy.org/

**Comment by pdehaye** [comment]
See #237 for rationale behind closing this issue.
