### ISSUE TITLE
D1.2: Data Management Plan V1

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#18]
- **WP1:** [Project Management](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP1)
- **Lead Institution:** Université Paris-Sud
- **Due:** 2016-02-29 (month 6)
- **Nature:** Report

See page 34 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by bpilorget** [comment]
For public work on the deliverable, follow this link: https://github.com/OpenDreamKit/OpenDreamKit/commit/410ab6d0c4a5959b0bb8c69287131c344cc69ae6

**Comment by bpilorget** [comment]
Hello @dimpase,
@nthiery made a small change in the data management plan to make sure that Nathann Cohen is not considered a member of Opendreamkit ("5.1. Addition to SAGEMATH codebase.")
Thank you
Can you check if that is ok for you?

**Comment by dimpase** [comment]
No, it is not OK, cause it is written as if *I* was not supported by ODK in that work, while in fact I was (and am).

**Comment by bpilorget** [comment]
Problem solved. issue still closed.
