### ISSUE TITLE
KPI 1: More effective collaborations between researchers  

### ISSUE THREAD

**Issue by pdehaye** [OpenDreamKit/OpenDreamKit#180]
From proposal:

> OpenDreamKit will strengthen collaborations between European scientific community in different branches of mathematics, through a development of the common e-infrastructure by bringing together previously separated software and databases, and building links with scientific communities in other disciplines (biology, physics, astronomy) that will use this e-infrastructure. The scientific community will considerably increase, by integrating new actors both from academic and non-academic sector.

Key Performance Indicators, from proposal:
1. Number of researchers in the mathematical scientific community using VREs based on OpenDreamKit.
2. Number of researchers in other disciplines (natural sciences, engineering, etc) and industry using VREs based on OpenDreamKit.
   - Number of SageMathCloud active users
     
     Can we track by kernel/software being used, so that we can get an idea of the area of research.
   - Number of users of Cloud-GAP (as soon as registration will be obtained)
   - Number of users of Mathrice's JupyterHub
   - website analytics
3. The number of attendees of our training and dissemination events. (CF post to be uploaded on the website after each event)
4. Number of collaborative (i.e. across institutions) publications using VREs based on OpenDreamKit.

See #179 for a methodology we suggested in the proposal on how to measure those KPIs (comparison year 1 and year 4 through survey).
- Sage/GAP/... Tags on stackexchange
- activity on ask.sagemath.org, sage-support, gap-forum (total / by ODK participants)

**Comment by nthiery** [comment]
Note: many KPI will be about software that we contribute to, not that we are leading; so we should be very clear in our KPI description that only a fraction of the credit goes to us.

**Comment by nthiery** [comment]
a

**Comment by pdehaye** [comment]
See #237 for rationale behind closing this issue.
