### ISSUE TITLE
KPI 5: Increased take-up of collaborative research and data sharing by new disciplines, research communities and institutions

### ISSUE THREAD

**Issue by pdehaye** [OpenDreamKit/OpenDreamKit#184]
From proposal:

> The project will clearly enhance a take-up of collaborative research and data sharing by and between new disciplines and research communities. Those communities already using parts of the tool, will be enlarged, involving more and more industrial actors and young scientists. By developing the tool, it will reinforce collaborations between different branches of mathematics (both pure and applied). Once developed, the tool will be opened for research in various disciplines, such as biology, physics, astronomy etc.

Key performance indicators, from proposal:
1. Increase in collaboration and data sharing between different communities in mathematics.
2. Increase in collaboration and data sharing between research communities in other disciplines.
3. Increase in the number of users and research communities using the tool.
   - KPI: number of SageMathCloud users, cumulated number of downloads for all components, estimated users of Jupyter, as reported by the Jupyter team?
4. Increase in the number of publications citing OpenDreamKit and its components, and in the 
   number of institutions and disciplines exhibited in these publications (although the timescales of publishing in some disciplines, including mathematics, mean that this will be very much a lagging indicator).
   - KPI: number of publications citing ODK or one of its components.  Counted on OpenAIRE? And, if technically easy, number of subject classifications involved.

See #179 for a methodology we suggested in the proposal on how to measure those KPIs (comparison year 1 and year 4 through survey).

**Comment by bpilorget** [comment]
Does "the tool" have a precise shape?

**Comment by pdehaye** [comment]
See #237 for rationale behind closing this issue.
