### ISSUE TITLE
Organize a workshop on social aspects

### ISSUE THREAD

**Issue by nthiery** [OpenDreamKit/OpenDreamKit#186]
Goal kickstart the work on the WP7 tasks

Participating sites:
- Oxford
- Sheffield
- Southampton

Organization: @dimpase, @alex-konovalov

**Comment by kohlhase** [comment]
I think that @stevelinton should also attend this workshop as representative of the ODK overall leadership.

**Comment by alex-konovalov** [comment]
At the moment, the picture looks like the main theme of the workshop is naturally centred around #148  as the chronologically first deliverable for WP7.

**Comment by alex-konovalov** [comment]
Closed as outdated.
