### ISSUE TITLE
D1.3: Internal Progress Reports year 1, including risk management and quality assurance plan

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#19]
- **WP1:** [Project Management](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP1)
- **Lead Institution:** Université Paris-Sud
- **Due:** 2016-08-31 (month 12)
- **Nature:** Report
- **Task:** T.1.3 (#16)
- **Proposal:** [p.34](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)
- **[Final report](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP1/D1.3/report-final.pdf)**

This reports on the scientific progress accomplished during the first year of OpenDreamKit (September 2015 to September 2016):
- [x] Evaluation of the progress of the project at the global level and the task level
- [x] Evaluation of risks foreseen and how they are being handled by partners
- [x] Quality assurance plan and report on Quality Review Board and end-user group's activities

**Comment by bpilorget** [comment]
Current plan

I/ Progress on the project
A)	General progress
B)	Focus on tasks to be implemented by now (cf status reports)

II/ Risk management
A)	Recruitment of highly qualified staff
B)	Different groups not forming effective team
C)	Implementing infrastructure that does not match the needs of end users
D)	Lack of predictability for tasks that are pursued jointly with the community
E)	Reliance on external software components

III/ Quality assurance plan
A)	Deliverables quality: Quality Review Board
B)	Infrastructure quality: End-user group

**Comment by nthiery** [comment]
Dear workpackage leaders (@OpenDreamKit/coordination)

I have writen a first draft of progress report overview in https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP1/D1.3/report.tex. For each workpackage, we want to have a couple paragraphs about the major achievements and ongoing work. Please have a look at the preliminary stuff I put there for your workpackage, and expand!

Yeah, sorry for the last minute, since in principle the report is due today. If we can get this done in the next couple days, that's ok. Next year, I'll have a better idea of what should go there, and try to start in advance!

If you see other things that you can improve elsewhere in the document, please be my guest!

Thanks in advance!

**Comment by nthiery** [comment]
@dimpase: oops, sorry, I just noticed you were *not* yet in @OpenDreamKit/coordination. Fixed!

**Comment by bpilorget** [comment]
@dimpase , @kohlhase @ClementPernet @defeo , Please have a look at section 2.3

**Comment by kohlhase** [comment]
> Please have a look at section 2.3

I have added some paragraphs about WP6. 
Unfortunately, final.pdata does not seem to have a definition for ```\@pdata@def{deliv}{dksbaseslfmverif}{issue}``` I wonder where the others came from.

**Comment by nthiery** [comment]
On Mon, Sep 05, 2016 at 12:59:32PM -0700, Michael Kohlhase wrote:
>    I have added some paragraphs about WP6.
>    Unfortunately, final.pdata does not seem to have a definition for
>    \@pdata@def{deliv}{dksbaseslfmverif}{issue} I wonder where the others
>    came from.

I have just updated the proposal style file so that we could add
github issue numbers to the proposal file, and recover them from the
pdata (makes it easy to link back to github from our files, etc). And
then I manually added the issue numbers to 4 of our 7 WP's. Three more
to go. Ok, I'll do that now :-)

Benoît: I'll let you do the same for tasks!

Cheers,
				Nicolas
--
Nicolas M. Thiéry "Isil" <nthiery@users.sf.net>
http://Nicolas.Thiery.name/

**Comment by kohlhase** [comment]
> have just updated the proposal style file so that we could add github issue numbers to the proposal file,

ah, I see, clever. I had been looking through the code of my proposal class and was wondering whether I had though of it and forgot, ... :-). That being said, it would probably be easy to generate the issue numbers if we make sure that the issue generating script and the issues are evaluated in the same way.

**Comment by nthiery** [comment]
On Mon, Sep 05, 2016 at 10:36:56PM -0700, Michael Kohlhase wrote:
>    ah, I see, clever. I had been looking through the code of my proposal
>    class and was wondering whether I had though of it and forgot, ... :-).
>    That being said, it would probably be easy to generate the issue
>    numbers if we make sure that the issue generating script and the issues
>    are evaluated in the same way.

Yup! That will be for our next project :-) I finished entering all the
issue numbers for the deliverables, and it took 10 minutes for the
last three workpackages. It's less geeky and more error-prone but that
worked for now.

Cheers,
				Nicolas
--
Nicolas M. Thiéry "Isil" <nthiery@users.sf.net>
http://Nicolas.Thiery.name/

**Comment by bpilorget** [comment]
Issue number added to tasks in WP files

**Comment by defeo** [comment]
> @dimpase , @kohlhase @ClementPernet @defeo , Please have a look at section 2.3

I expanded it a bit. Maybe there's something more to say on
SageMathCloud, I have to read Viviane's report first...

**Comment by bpilorget** [comment]
@videlec Peux-tu vérifier que je ne me suis pas trompé dans la partie recrutement, au niveau du paragraphe sur le CNRS stp?

**Comment by videlec** [comment]
@bpilorget  done

**Comment by bpilorget** [comment]
@dimpase , @ClementPernet,  Please have a look at section 2.3 and add the information needed for WP5 and WP7

**Comment by nthiery** [comment]
Done with the paragraphs about risk management. Please proofread.

**Comment by nthiery** [comment]
I would like to send this ASAP to our project coordinator, to have feedback on the new format of our deliverables, and as a way for her to get an overview on our progress. I believe we just need @dimpase and @ClementPernet to finalize the short subsection on their workpackage.

**Comment by nthiery** [comment]
As discussed on another deliverable, the author list should consist of all those that made a nontrivial contribution to the deliverable. For now, we have ``NT, BP, et al.'' as author list. Shall we be more specific, mentionning all the work package leaders?

**Comment by ClementPernet** [comment]
Hi.
I had a paragraph written up last friday for WP5. In case you find it not complete enough I added a 
paragraph on D5.5 today, if it's still time.
Let me know if you think of something specific that need to be improved.

Clément

**Comment by nthiery** [comment]
Merci Clément!

@dimpase: there just remain your blurb about WP7:
https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP1/D1.3/report.tex#L333
Thanks in advance,

**Comment by nthiery** [comment]
Hi @jdemeyer,
https://www.lri.fr/etherpad/p/sage-days77-documentation is now back online. Could you move its content to the sage wiki, and write a very brief summary with a link to the wiki page around
 https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP1/D1.3/report.tex#L249?
Thanks in advance!

**Comment by nthiery** [comment]
@bpilorget: could you have a look at the item left in this issue description:
- [ ] Agregate the site reports from project meeting
Do you think there remains something to be done in this direction?

**Comment by bpilorget** [comment]
@nthiery It's done. Minor improvements followed

**Comment by dimpase** [comment]
Hi, sorry for holding this up, travelling from one conference to another.
Will do tomorrow.

**Comment by nthiery** [comment]
On Thu, Sep 15, 2016 at 08:44:14AM -0700, Dima Pasechnik wrote:
>    Hi, sorry for holding this up, travelling from one conference to
>    another.
>    Will do tomorrow.

Thanks! Enjoy the conferences :-)

**Comment by dimpase** [comment]
how does one use `\delivref` macro? I don't see how e.g. 
`\delivref{component-architecture}{portability-cygwin}` relates to the wp and deliverable numbers. Is this correspondence specified anywhere? Thanks in advance.

**Comment by nthiery** [comment]
On Sun, Sep 25, 2016 at 05:02:29PM -0700, Dima Pasechnik wrote:
>    how does one use \delivref macro? I don't see how e.g.
>    \delivref{component-architecture}{portability-cygwin} relates to the wp
>    and deliverable numbers. Is this correspondence specified anywhere?

This uses the same labels as in our proposal: \delivref{<wp>}{<deliverable>}.
So the correspondence can be retrieved from the sources of the WP
description, e.g. <ODK>/Proposal/WorkPackages/SocialAspects.tex.

Alternatively, I find convenient to make searches in
<ODK>/Proposal/final.pdata, since it contains all the info:
deliverable labels, names, numbers, ..., all in a single file.

Cheers,

**Comment by bpilorget** [comment]
@dimpase  Hi Dima. I don't see your inpu on WP7. Have you had time to write something?

**Comment by dimpase** [comment]
@bpilorget : Hi,  I hear you, I'm working on it.

**Comment by bpilorget** [comment]
@dimpase Dima??

**Comment by markuspf** [comment]
Sorry, I was clicking in the wrong place.

**Comment by nthiery** [comment]
Hi @minrk: could you throw in a few lines on Jupyterhub improvements by ODK in 2015-2016, and maybe expand a bit on the Jupyter paragraphs just above?
See around:
https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP1/D1.3/report.tex#L251

@dimpase: still looking forward a couple paragraphs for WP7:
https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP1/D1.3/report.tex#L338

I'd like to submit this deliverable (already 4 months late ...) this week, in preparation for next week.

Thanks in advance,

**Comment by dimpase** [comment]
oh, I haven't understood I am delaying a deliverable here, sorry. Will be done in a day or two.

**Comment by minrk** [comment]
Yes, I'll do that tonight or tomorrow.​

**Comment by nthiery** [comment]
On Mon, Jan 09, 2017 at 09:57:23AM -0800, Min RK wrote:
>    Yes, I'll do that tonight or tomorrow.​

Great. Let me know if you are touching this right now, as I am doing
some pieces just below and there may be overlap.

**Comment by minrk** [comment]
@nthiery just added some Jupyter notes

**Comment by nthiery** [comment]
On Tue, Jan 10, 2017 at 06:51:01AM -0800, Min RK wrote:
>    [1]@nthiery just added some Jupyter notes

The notes are informative. Thanks!

**Comment by dimpase** [comment]
Added stuff on WP7 - not sure whether it already is TeX-able without errors. Please have a look.

**Comment by nthiery** [comment]
On Tue, Jan 10, 2017 at 05:17:33PM -0800, Dima Pasechnik wrote:
>    Added stuff on WP7 - not sure whether it already is TeX-able without
>    errors. Please have a look.

Thanks Dima! It compiles smoothly; I just add the "publication.bib"
resource for the references.

I refactored a bit the text, attempting to further highlight the
scientific content of the work in addition to the more administrative
aspects (measure of the progress on deliverables). I left too
suggestions of small additions. Can you have a look?

Cheers

**Comment by dimpase** [comment]
@nthiery where are your updates/suggestions?

**Comment by nthiery** [comment]
On Wed, Jan 11, 2017 at 03:49:09AM -0800, Dima Pasechnik wrote:
>    [1]@nthiery where are your updates/suggestions?

Sorry, I was in the train over the phone and did not see that my push
had failed. It's pushed now!

**Comment by fangohr** [comment]
Am just working through this. I notice that tasks (such as T3.8) are printed in bold face in the pdf but deliverables (such as D4.9) are in normal font. I would actually prefer if the tasks where also in normal font (i.e. not bold): they see to attract too much visual attention in the document. 

If there are no objections, can somebody do this ? @kohlhase maybe?

**Comment by kohlhase** [comment]
> If there are no objections, can somebody do this ? @kohlhase maybe?

I have done that, they were just a ```\textbf{...}``` away.

**Comment by nthiery** [comment]
Submitted on the EU portal.
Note: task references were still in bold (as taken from final.pdf). No big deal, so I moved on.
Thanks everybody for the feedback!
