### ISSUE TITLE
Remove or Replace Deliverable D6.8 (Due: 36, Type: OTHER, Dissem.: PU, Lead: UZH) LMFDB Algorithm Verification with respect to a Triformal Theory

### ISSUE THREAD

**Issue by kohlhase** [OpenDreamKit/OpenDreamKit#201]
This is deliverable #142 I want to remove or replace. 

In the WP6 discussions in the first year, it became clear that we want to de-emphasize the verification aspect of software (this is not on the critical path to a VRE). So this deliverable does not really make sense. This was not really clear at proposal time. 
I would ideally like to just remove the deliverable (we have another deliverable on month 36 that is much more on the critical path) and respective parts of the WP6 tasks. 

If need be, we can replace it with another deliverable, e.g. documenting the SCSCP interfaces better. 
cc: @florian-rabe @nthiery @VivianePons 
Please give me feedback on this, when should we attempt this (e.g. the formal review), and how to do this.

**Comment by bpilorget** [comment]
I will see the legal process for deliverable deletion, though I am not 100% sure it is feasable. 
In any case it should be validated in  an amendment to the grant, potentially in the same amendment related to the change of your position.

**Comment by kohlhase** [comment]
thanks, I will wait until you have news.

**Comment by bpilorget** [comment]
It is "unusual" to delete a deliverable, but as for any other matter, it is all up to the Project Officer. We must clearly explain the reason behind the deletion and, and also we need to show how it is good for OpenDreamKit (by turning the deliverable into a new one for example). But at least you are programming this very early and it is always a big plus!
If the change is accepted, it will have to be integrated in a future amendment, preferably the one that will concern you as amendments are a pain to do for every actor.
@nthiery , Have you had news from our PO yet? She should be back from holiday now.

**Comment by nthiery** [comment]
I agree that it would not make much sense to keep focusing manpower for a deliverable that has now been identified as of little relevance to the aims of ODK. Of course we need to argue that this is a shift of manpower for more relevant work.

Would there a way to rethink this deliverable to keep its original aim (grossly speaking evaluating the relevance of triformal theories for validating sofware systems such as LMFDB) if not its exact form? After all, the MMT formalization of the LMFDB has already been useful for identifying certain shortcomings of the LMFDB, right?

**Comment by pdehaye** [comment]
Just discovered this thread, I wasn't flagged in the initial issue posting. I came to the same conclusion as @kohlhase independently, given the manpower we have (and you will have).  To address @nthiery's concern, some verification is (almost) already done as part of @kohlhase's student work on D6.4 (on OEIS), so this might be a much better point to start with a prototype for verification, directly integrating with Sage. Maybe we could run a validation of OEIS formulas from Sage, dispatching through other interoperability tools we are building to other systems? This might help with the OEIS formula parser too. Concentrating all this work at FAU/Bremen makes much more sense. In any case, this would not leave out LMFDB from MMT integration, as there is still D6.11 #135, which is concerned a lot more with "Algorithms, Data, Presentation".

**Comment by kohlhase** [comment]
As we had discussed on an e-mail with the relevant players, I have changed the title of D68. to 
*Curated Math-in-the-Middle Ontology covering exemplary parts
of LMFDB, OEIS, FINDSTAT, GAP, SAGE knowledge bases.*
in the proposed grant agreement (to be voted on today). So if accepted this issues should be taken care of.

**Comment by kohlhase** [comment]
I think the wording of this title is sufficiently careful that we can actually achieve it. (OEIS is mostly done, we are working actively on GAP, Sage, and LMFDB, and FindStat seems smaller).

**Comment by JohnCremona** [comment]
+1

**Comment by nthiery** [comment]
Hi @kohlhase,
Could you update the github issue description accordingly? Maybe you want to add one line at the beginning of the issue description stating that the deliverable was originally called XXX, explain the shift of focus and refer to here.
Thanks!

**Comment by kohlhase** [comment]
OK, implemented
