### ISSUE TITLE
Participation to the "Design Your E-infrastructure workshop", Krakow, Sept 27 of 2016

### ISSUE THREAD

**Issue by nthiery** [OpenDreamKit/OpenDreamKit#202]
We have been strongly encouraged to participate to this workshop, and it indeed seems quite relevant.
In general it would make much sense to participate to the [Digital Infrastructure for Research](http://www.digitalinfrastructures.eu/) event that follows (28th-30th).

Here is the full invitation to the workshop

``I work for the EGI pan-European e-infrastructure as Technical and Customer Outreach Manager. I would like to draw your attention to an upcoming workshop that 4 major European e-infrastructures (EGI, EUDAT, GÉANT and OpenAIRE) will organise jointly on September 27 in Krakow. The workshop is titled 'Design Your E-infrastructure' and it is aimed at projects like OpenDreamKit. The event will be a consultancy workshop to support projects and communities become familiar with e-infrastructures and to establish long-term partnerships with them.

- During the workshop we will give an overview of the EGI, EUDAT, GÉANT, OpenAIRE e-infrastructure service portfolios.

 Selected user communities and projects will bring and present their use cases (following pre-defined template/structure). OpenDreakKit could be one of these!

- In small break-out groups we will analyse each use case and will define solutions to them with the use of e-infrastructures.

- We will report back about the break-out outcomes, defining next steps to implement the use cases - i.e. the joint work/setup with e-infrastructures.

Full details about the workshop can be found at : https://indico.egi.eu/indico/event/3025/

Please let me know if you are interested in participating with a use case at this event. The travel cost to the workshop can be covered by EGI for selected use cases.

We have only a few days left to finalise the list of use cases. If you are interested to submit a use case, then please do that by the end of this week. At the bottom of this email I wrote a set of questions. If you could answer those (as much as possible) that would be enough. Based on your answers we can decide early next week about whether the use case fits to the workshop, or we rather follow it up in some other way (e.g. with a series of teleconference meetings)

The workshop is for free and it will be co-located with the Digital Infrastructures For Research (DI4R) conference.(The big annual event by e-infrastructures for research communities).``

cc: @OpenDreamKit/participants

**Comment by nthiery** [comment]
In general it would make much sense to participate to the [Digital Infrastructure for Research](http://www.digitalinfrastructures.eu/) event that follows (28th-30th).

With teaching starting, it's a bit hard for me to go there, especially on the 29th. Anyone interested / available?

I have started preparing a use case. Please have a look at ... and edit!

**Comment by nthiery** [comment]
I have started preparing a [use case](https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP3/2016-09-27-DesignYourInfrastructureWorkshop-UseCase.md). Please have a look and edit!

**Comment by alex-konovalov** [comment]
Worth mentioning to others that the deadline for the use case is tomorrow September 9th!

**Comment by florian-rabe** [comment]
I've looked briefly at EGI and EUDAT and could not make up my mind if they can be useful to us.
My impression is that

 * they have missions to provide services and are in need of people to use their services,
 * their services use a high level of abstraction and therefore cannot be math-aware.

So if we can think of something high-level that we want, they might do it for us.
Maybe they could host our finished VRE (i.e., all our systems plus web frontends for them)?

**Comment by dimpase** [comment]
It seems that EGI does offer some cloud resources on which you can run stuff (like one does it on commercial systems like AWS (Amazon), Google Cloud, Azure (Microsoft)).
E.g. https://appdb.egi.eu/store/vappliance/docker.ubuntu.14.04 

It's worth exploring in more detail IMHO, it seems there are things one can use for free; apart from the traditional hardware one gets access to GPGPU (graphics cards based parallel stuff).

**Comment by dimpase** [comment]
I can do 27-28 or 27-29.

**Comment by nthiery** [comment]
On Fri, Sep 09, 2016 at 02:13:31AM -0700, Florian Rabe wrote:
>    Maybe they could host our finished VRE (i.e., all our systems
>    plus web frontends for them)?

At this point, this is indeed what came up to my mind: providing
hardware resources + services like resource management,
authentication, assistance in the design and setup, long run
maintenance, ... This for a whole range of services starting from
tmpnb style server (could be deployed immediately) to full-featured
VRE's.

See:

        https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP3/2016-09-27-DesignYourInfrastructureWorkshop-UseCase.md

**Comment by dimpase** [comment]
OK, I can also do the whole http://www.digitalinfrastructures.eu/ event there. Let me know soon.

**Comment by nthiery** [comment]
Oh, sorry Dima; I somehow missed your comments (too many notices these days). It's great that you can go.
It could be nice to have someone from the Jupyter side as a complement. @mikecroucher, @minrk maybe?

**Comment by dimpase** [comment]
@nthiery : has anyone sent         https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP3/2016-09-27-DesignYourInfrastructureWorkshop-UseCase.md 
to the workshop organisers?

**Comment by nthiery** [comment]
On Sun, Sep 11, 2016 at 08:28:32AM -0700, Dima Pasechnik wrote:
>    [1]@nthiery : has anyone sent
>    [2]https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP3/2016-09
>    -27-DesignYourInfrastructureWorkshop-UseCase.md
>    to the workshop organisers?

I had pointed them to our use case, but nothing formal. So it's good
that you got in touch directly and registered. Thanks!

**Comment by bpilorget** [comment]
Dima joined the meeting

**Comment by nthiery** [comment]
The workshop organizers recently got back in touch with Dima, seeking next collaboration steps.
Here is a first draft of answer. Feel free to edit it directly here.

Dear Gregory,

Thanks for getting back in touch. As described in our proposal, funding would indeed be needed on our side for full-fledged tightly integrated services. Nethertheless, there are low hanging fruits that should take no more than a couple days of work on both sides. We would very much like to pursue them jointly as soon as possible if you could spare that time. Not only would those fruits immediately benefit the community, but implementing them would be the occasion to better understand the technicalities involved and refine accordingly the shape and cost of longer term collaboration opportunities.

I (Nicolas) am available next week for an online chat (on Montreal time however). 

Just in case: many of us will be in Brussels the week after for our M18 project review. In case you have personnel there, Thursday 27 and Friday 28 of April would be a good time for a face-to-face discussion if not a coding sprint.

By the way: the report on our proposal included a recommendation to apply for a to follow up "specialized services" call. We haven't heard back about it yet. Do you happen to know the timeline for this call?

Thanks in advance,

Best regards,

**Comment by dimpase** [comment]
I did edit it a bit. Nicolas, will you mail it?

**Comment by nthiery** [comment]
Thanks @dimpase . It's mailed now!
