### ISSUE TITLE
deliverablereport.cls breaks table of contents

### ISSUE THREAD

**Issue by kohlhase** [OpenDreamKit/OpenDreamKit#203]
Somehow the table of contents breaks in ```deliverablereport.cls```: instead of having "Contents" as the "heading", it appears below the table. We should try to fix this before submitting the current crop of reports. 
I have tried a couple of things, but do not really know what is going on. I noticed on D6.2 (#137), but it seems to happen on old reports as well.

**Comment by kohlhase** [comment]
hmmm, in 6.2 it goes away, if I do not include ```local.sty```, looking on.

**Comment by kohlhase** [comment]
Ah, this reveals the culprit: ```parskip.sty```. This problem is described in http://tex.stackexchange.com/questions/54233/table-of-contents-title-removed
So I guess that if we want to keep parskip in, we should make the recepie introduced there into ```deliverablereport.cls```.  Or base the class on something else than ```amsart.cls``` (which I find horrible in any case).

**Comment by kohlhase** [comment]
it seems that we only use parskip in reports D6.1 and D6.2, I removed it from both, so this is fixed.

**Comment by nthiery** [comment]
Thanks Michael for investigating!
