### ISSUE TITLE
refactor defliverablereport.cls

### ISSUE THREAD

**Issue by kohlhase** [OpenDreamKit/OpenDreamKit#204]
I think it would probably be better refactor ```deliverablereport.cls``` into two: the basic functionality in ```LaTeX-Proposal/eu/eudelivreport.cls``` and a class ```odkdelivreport.cls``` that mainly contains a ```\LoadClass{eudelivreport}``` and instantiates it to (e.g. with our logo). But where would that live?
@nthiery @bpilorget

**Comment by nthiery** [comment]
I'd say: let's put odkdelivreport.cls in <ODK>/Proposal/ since that's where we already have all our latex stuff, including the common macros, the pdata database, etc. With time, the directory name is becoming a bit of a misnomer since we have more than just the proposal there, but that's good enough.

Thanks!

**Comment by kohlhase** [comment]
OK, that makes sense. Maybe we should add a ```Proposal/README.md``` describing what is there. Also we should probably have a short description of what is in the repos and why to the ```README.md``` at top level. Let me see what I can do there.

**Comment by nthiery** [comment]
Sounds good.

**Comment by kohlhase** [comment]
OK, I have started refactoring and fixed all the links to the deliverables. Also I have updated the ```README```s a bit. This is done for now.

**Comment by hivert** [comment]
Hi there,

I checked the report for Deliverable D5.1. It looks very nice. Thanks ! However, there where a lot of links in the github-issue-description.md that where lost in the report. As a consequence lots of sentences doesn't really makes sense. What should we do ?

See https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP5/D5.1/github-issue-description.md compared to https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP5/D5.1/report-final.pdf

**Comment by nthiery** [comment]
I do see the links here. Can you specify which one?
We can have a brief look together when I pass by your home this afternoon.

@kohlhase: to recompile the file, I had to add a link to eudelivreport.cls. Is this what we want to do for each deliverable, or do we want to somehow hardcode the path to eudelivreport.cls from odkdelivreport.cls, as we already do for the pdata and other files from Proposal/?

**Comment by nthiery** [comment]
Note: I just updated the pdf w.r.t. the new style file.

Ah, one thing Florent: which of the linked document do we want to consider as being officially part of the report, and thus attach as appendix? The slides maybe?

**Comment by hivert** [comment]
The link are Ok. It's just Github viewer that don't support hyperlink. Now concerning the linked document, I think that both the [slides](https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP5/T5.6/HPC-Combi.pdf) and the [documentation](https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP5/T5.6/documentation.pdf)  deserve to be included as an annex in the final report.

**Comment by defeo** [comment]
> @kohlhase: to recompile the file, I had to add a link to eudelivreport.cls. Is this what we want to do for each deliverable, or do we want to somehow hardcode the path to eudelivreport.cls from odkdelivreport.cls, as we already do for the pdata and other files from Proposal/?

Do we have an answer to this question? I had the same problem.
