### ISSUE TITLE
 Open science in the European Research Area, Ministry of research, Slovenia, 17 November 2016

### ISSUE THREAD

**Issue by bpilorget** [OpenDreamKit/OpenDreamKit#206]
# Conference FAQ
- What: Conference on Open Science in the European Research Area for Slovenian researchers
- Where: Slovenian Ministry of Education, science and Sport
- When: Thursday, 17 November 2016
- What for: 30 min presentation on the topic of virtual research environments
- Money: The University of Ljubljana will cover plane ticket + local transport + hotel accommodation

Weblink to the [conference](https://www.uni-lj.si/research_and_development/open_science/)

**Comment by bpilorget** [comment]
@OpenDreamKit/participants 
Dear all, ODK is invited to do a presentation on virtual research envirionments within Open Science at the Slovenian Ministry of Research. @nthiery is unavailable and I am maybe not the best person to do this. Would someone be interested in this?

**Comment by bpilorget** [comment]
Anybody? @OpenDreamKit/participants

**Comment by fangohr** [comment]
Marijan and I can work something out, and Marijan can go and present. This will be focussed around Jupyter, workflows and reproducible science. I'll contact Min and Benoit for support offline in a moment.
