### ISSUE TITLE
D1.5: Internal Progress Reports years 2 and 3, including risk management and quality assurance plan

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#21]
- **WP1:** [Project Management](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP1)
- **Lead Institution:** Université Paris-Sud
- **Due:** 2018-08-31 (month 36)
- **Nature:** Report
- **Proposal:** [p. 32](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)
- **[Final report](https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP1/D1.5/report-final.pdf)**, [sources](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP1/D1.5)

This document is meant as an internal draft for the project's Technical Report for Reporting Period 2. As such, it provides an overview of the project achievements, by objectives, work packages, and tasks from March 2017 to August 2018, and their impact. It also explains how reviewer's recommendations were tackled and discusses risk and quality management and deviations from the original plan.
We recommend to read directly the technical report itself.

**Comment by nthiery** [comment]
I left a comment in #193 about fixing the title as well in the grant agreement.

**Comment by kohlhase** [comment]
@ntheiry I have updated WP6 to this report period. 

My understanding is that the report is to be read cummulatively, and that I do not have to delete past achievements. 

I am now looking over the other parts of the document.

**Comment by kohlhase** [comment]
@nthiery 
In 2.1. I see `The following people were hired in the past year:` and then the table shows hiring from 2015 and so on. 
I am not sure that to do. I have hired 
Theresa Pollinger: October 2017 - May 2018
Tom Wiesing: September 2017 -

**Comment by nthiery** [comment]
>    @ntheiry I have updated WP6 to this report period.
> 
>    My understanding is that the report is to be read cummulatively, and
>    that I do not have to delete past achievements.

As long as there is a clear distinction between past achievements and
achievements for this reporting period, and if that contributes to the
overall understanding, that's all good!

>    I am now looking over the other parts of the document.

Thanks!

**Comment by nthiery** [comment]
>    In 2.1. I see The following people were hired in the past year: and
>    then the table shows hiring from 2015 and so on.
>    I am not sure that to do. I have hired
>    Theresa Pollinger: October 2017 - May 2018
>    Tom Wiesing: September 2017 -

Hmm, good catch. We definitely should separate hiring from RP1 and
RP2. And possibly remove the former. If you could start a first draft
of this (especially for the information you have) that would be great,
and I'll finalize.

**Comment by kohlhase** [comment]
I have done that; highlighting Florian's joint appointment. 

But someone will have to read the general text carefully and update all the little things. 
I will not have time to do that unfortunately.

**Comment by nthiery** [comment]
>    I have done that; highlighting Florian's joint appointment.

Great, thanks Michael,

>    But someone will have to read the general text carefully and
>    update all the little things. I will not have time to do that
>    unfortunately.

Yeah ... that's on me ...

Luckily, that's the internal report; we will be able to do further
polishing for the full technical report due one month from now.

**Comment by kohlhase** [comment]
I have started carefully going over this report again, and I have pushed the first results of this. I have
* reorganized the sectioning of the report to save on nesting depth and make reading easier (especially in the WPs)
* I have moved the sections into their own (included) files.
* I am leaving lots of `ednote`s and `oldpart`s, where I have the feeling, the text is not updated yet. 
All in all, there is still considerable work to do on this deliverable (boring as it is).

**Comment by kohlhase** [comment]
I will continue doing this all of today.

**Comment by nthiery** [comment]
Thank you Michael; I really really appreciate this. With Benoit away
and all the rest, I am in submarine mode and this plugs a serious
breach: this deliverable was meant as a draft for our periodic technical report
(due October 10th!) and I never got to finalize it. So let's just work on it
as our final technical report, and submit both on October 10th.

@VivianePons, @defeo, @minrk, @ClementPernet, please check on Michael's ednotes and fill them in!

**Comment by nthiery** [comment]
About the overall structure: you may want to double check on the [template](https://github.com/OpenDreamKit/OpenDreamKit/blob/master/ReportingPeriod_1/Technical_Report/template.txt)
and our [previous report](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/ReportingPeriod_1/Technical_Report)

**Comment by kohlhase** [comment]
Wow, that is quite different to the current structure (which I only changed marginally). 
I will have a look how to best adapt that.

**Comment by kohlhase** [comment]
I have adapted the structure of the report (the ToC is now correct) and will continue later.

**Comment by IzabelaFaguet** [comment]
Accepted by the EU on December 5th.
