### ISSUE TITLE
Workshop on live structured documents

### ISSUE THREAD

**Issue by nthiery** [OpenDreamKit/OpenDreamKit#211]
There are many use cases for "live structured documents" and many approaches and toolchains have been explored (Jupyter notebooks, MathHub.info, PreTeXt (former MathBookXML), TeXmacs, LMFDB, Sage's Single Cell server...). It would be a good time to bring together people from the above projects and users/authors with a variety of background to share experience and seek venues for collaborations.

A key step will be to decouple the various aspects involved:

- Authoring language (ReST, XML, latex, ...),
- Converters and toolchains ([Sphinx](http://sphinx-doc.org/) , [LaTeXML](http://dlmf.nist.gov/LaTeXML/), [PreText](http://mathbook.pugetsound.edu/index.html), pandoc, docbook ),
- Infrastructure for rendering documents,
- Infrastructure for interacting with the computing backends (e.g.  [Thebe](https://github.com/oreillymedia/thebe) based on the Jupyter protocol, [sympy live](https://github.com/sympy/sympy-live/), ...),
- Online services providing computing backends (e.g. [tmpnb](try.jupyter.org), [sagecell server](https://sagecell.sagemath.org/), [binder](mybinder.org), ...),
- Integrated collaborative authoring environments (sharelatex, SMC, texmacs, ...)

to foster the reuse of basic building blocks  across the many tool chains.

Dates: 16-20 of October 2017
Location: Simula, Oslo
Registration: https://www.eventbrite.com/e/opendreamkit-workshop-on-live-structured-documents-tickets-37364670736

[PAD for sprints, notes, ...](https://semestriel.framapad.org/p/live-structured-documents-workshop)

Participants:
- Robert Beezer @rbeezer 
- Olivier Cayrol
- Michael Kohlhase @kohlhase 
- Sebastian Gutsche @sebasguts 
- Min Ragan-Kelley @minrk 
- Thomas Kluyver @takluyver 
- Tom Wiesing @tkw1536 
- Nicolas M. Thiéry @nthiery
- ...

Organizers: @minrk, ...

Funding sources:
- OpenDreamKit
- MathBookXML's UTMOST NSF grant?

See also:
- [Sage Days 77 brainstorm notes](https://wiki.sagemath.org/days77/live-structured-documents)
- ODK's [D4.2's report on Active/Structured Documents Requirements and existing Solutions](https://github.com/OpenDreamKit/OpenDreamKit/issues/91)
- Follow up GAP-Jupyter workshop in Saint Andrews (TODO @sebasguts: add link)

**Comment by minrk** [comment]
This sounds great! I think Simula could be a good host for this.

**Comment by kohlhase** [comment]
> This sounds great! I think Simula could be a good host for this.

indeed, alternatively (I would love to come to Norway), I could organize something in Erlangen.

**Comment by nthiery** [comment]
> I would love to come to Norway

Me too :-)

Thanks to both of you for offering! Shall we start by making a
preliminary list of potential participants, and see from there where
the barycenter is? It might end up being on the other side of the
Atlantic.

**Comment by rbeezer** [comment]
This looks like a great idea, and I'd be happy to help with organization.  While I will shift the barycenter significantly to the west, visiting Norway would be enjoyable for me.

I have a sabbatical leave for the 2017-18 academic year, but have also begun planning other travel, so setting dates would help me with that.

Unfortunately, the UTMOST grant got chopped way down before getting funded, so we are cutting it close to the bone.  I do have some personal travel money there, and from my university as part of the sabbatical leave.

Rob

**Comment by kcrisman** [comment]
It would make a lot of sense to invite some people who know about Shiny and/or other R/RStudio apps, with a view toward allowing more broad data science/visualization/statistics participation in the "live structured documents" ecosystem.  E.g. https://bookdown.org/yihui/bookdown/ even though it's based on md 😉 but has very nice examples of [embedding Shiny](https://bookdown.org/yihui/bookdown/web-pages-and-shiny-apps.html) and so forth, also has support for knitr which is SageTeX but for R

**Comment by fangohr** [comment]
I'd be interested in participating. I'd expect @takluyver might be as well?

**Comment by takluyver** [comment]
I would indeed.

**Comment by markuspf** [comment]
I would be interested, too.

**Comment by alex-konovalov** [comment]
Same for me.

**Comment by nthiery** [comment]
For information: Logilab ( @fcayre, @nchauvat, ...) is in the process
of moving away from latex/beamer for their training support. They are
considering rst, notebooks, python(sphinx-gallery), ... They have
expressed interest in a coding sprint, in the short run, around
notebook conversions, sphinx, rst, ... They are willing to organize it
in Paris. Given the timing, it's probably best not to wait for the
larger workshop discussed in this issue. Please express interest here.

Personally, I am very much looking forward a Sphinx based rst to
notebook converter!

**Comment by rbeezer** [comment]
Interested, especially if there is a role for MathBook XML or XSL (as input or 
to provide output).

Please keep me informed on details.

Thanks,
Rob

**Comment by minrk** [comment]
We need to work on scheduling this workshop. I would like to try to host this at Simula in Oslo, if possible, likely in early to mid October or early November.

I've opened this [whenisgood](http://whenisgood.net/gjejzms) for scheduling the workshop.

**Comment by minrk** [comment]
Based on the whenisgood responses, it looks like the week of 16 October is going to work best for this. We can host it [at Simula](https://www.simula.no/about/contact-simula), which is in Fornebu in the Oslo area. I can provide more transport details if that sounds good to everyone.

I suppose we should set up a formal event?

**Comment by sebasguts** [comment]
I would be interested in this, too.

**Comment by minrk** [comment]
Anyone interested in participating in this workshop can register here: https://www.eventbrite.com/e/opendreamkit-workshop-on-live-structured-documents-tickets-37364670736

**Comment by minrk** [comment]
A reminder to everyone interested that this workshop will be in Oslo the week of 16 October. Please [register](https://www.eventbrite.com/myevent?eid=37364670736) if you are planning to come and feel free to ask me any questions about logistics.

**Comment by kohlhase** [comment]
Do we have a list of participants yet?

**Comment by nthiery** [comment]
A participant list would be great indeed, as well as some preliminary schedule. I'll be organizing the [Fête de la Science](http://fetedelascience.org) for the lab here on Sunday, so may adjust my flight time accordingly to not rush too much between the two.

**Comment by nthiery** [comment]
Ok, for the record, I booked my flight, arriving in Oslo at 23:30 on Sunday the 15th, and flying back on around 17:00 on Monday the 23rd.
I was planning to stay at the recommended hotel near Simula (Scandic Fornebu), but apparently it's booked out for that period (?). 

Who would be up for sharing an AirB&B with me? There are a few options close by which should make for around 50€ per person per night. Let me know quickly.

@minrk : is there a mailing list for the registered participants to forward this request to?

**Comment by takluyver** [comment]
I'll be there from Sunday morning to Saturday morning, staying at Scandic Fornebu.

**Comment by kohlhase** [comment]
I will attend Sunday night to Wednesday afternoon.

**Comment by rbeezer** [comment]
I'll attend Tuesday through Friday.  I booked a room in the city center, since it is my first trip to Norway.  Offline much of the next two weeks - without even electricity.

See everybody soon.

Rob

**Comment by minrk** [comment]
Participants registered so far:

- @kohlhase
- @tkw1536
- @takluyver 
- @nthiery 
- @vidartf 
- @minrk
- @sebasguts 
- @rbeezer 

As for agenda, I would like to spend most of the time working toward specific goals, rather than presenting things to each other. To that end, I think spending the morning of Monday and Tuesday presenting some of the aspects of different projects we can work on, and the rest of the time in work groups, with some recap on Friday afternoon.

I will plan to present on JupyterLab javascript and the current state of Thebe-style tools for adding execution to webpages such as documentation. Any attendee is welcome to present a talk demonstration about what they would like to collaborate on during the week.

Feel free to propose something you would like to work on / demo / have demoed by someone else here in this Issue.

**Comment by takluyver** [comment]
I'm at the hotel. If anyone else is here or nearby in Fornebu, and wants to get dinner together, let me know.

**Comment by kohlhase** [comment]
Tom and I will be coming in at 22:00, too late for dinner. But we can meet at breakfast. 
I think that @nthiery said that he wanted to be at Simular 8-9. So unless I hear something from him on this channel, I will plan for a breakfast at 7:30.

**Comment by minrk** [comment]
I’ll be at Simula ready for everyone by 9. See folks in the morning!

**Comment by nthiery** [comment]
Here is a pad for brainstorming:
https://semestriel.framapad.org/p/live-structured-documents-workshop

**Comment by nthiery** [comment]
Hi @minrk!
Would you have a chance to briefly report on this workshop in D2.11 #36 today? I am already quite overloaded :-)
File to be created in https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP2/D2.11/events
using the template available from this directory.

**Comment by minrk** [comment]
Yes, I'll write this right now.

**Comment by minrk** [comment]
Added a writeup of this workshop to D2.11

**Comment by nthiery** [comment]
>    Yes, I'll write this right now.

I appreciate that :-)

**Comment by nthiery** [comment]
>    Added a writeup of this workshop to D2.11

Proofread! Thanks Min :-)
