### ISSUE TITLE
Add deliverable status and blog link to the proposal metadata

### ISSUE THREAD

**Issue by nthiery** [OpenDreamKit/OpenDreamKit#220]
I propose that we add the status of a deliverable and link to relevant blog post to the proposal metadata:

      \begin{wpdeliv}[due=6,id=pari-pythonlib1,dissem=PU,nature=OTHER,lead=UB,issue=83,
                               status=submitted,blog=http://truc/foo]
	  {Python/Cython bindings for \Pari and its integration in Sage}
      \end{wpdeliv}

This will enable the automatic generation of, e.g., the list of submitted deliverables, with direct links to their reports and blogs.

Possible values for `status`: no value, `submitted`,`validated`, the latter being set after the review by the referees. Unlike for the report, and possibly the slides, our blog posts don't have a systematic location. Hence the necessity of storing the information.

What do you think?

TODO:
- [x] Implement the support for the above keys and storage in the pdata file @nthiery
- [x] Maybe: use that information when generating the proposal pdf? @kohlhase, @nthiery
- [x] Use the metadata in http://opendreamkit.org/follow/#Reports @VivianePons
- [x] Add status=submitted/delivered information for all deliverables for Month <= 18 @bpilorget  
      For an example, see: https://github.com/OpenDreamKit/OpenDreamKit/blob/master/Proposal/WorkPackages/HPC.tex#L360
- [ ] Add link to blog posts for all relevant deliverables for Month <= 18 @bpilorget 
      (while you will be collecting that information, please throw it as well in the corresponding github issue descriptions, so that its last line look like, e.g.  ``**Final report**, **slides**, **blog post**''; for an example, see the description of #119)

**Comment by kohlhase** [comment]
Good idea, I will take care of this, but probably only after I come
home, so do not hold your breath for this month. 

Michael

**Comment by bpilorget** [comment]
OK. Not sure I understand the last line on the TODO list. You can show me next time we see each other this week.
Benoît

**Comment by nthiery** [comment]
Looking at the latex side ...

**Comment by bpilorget** [comment]
We can do it tomorrow together Nicolas!

**Comment by nthiery** [comment]
For the last item, I made an example on D5.6 (#119).

**Comment by nthiery** [comment]
The style file now supports the metadata (but does nothing with it beside writing it to the pdata file).

The proposal metadata is now available in yaml for our web page in:
https://github.com/OpenDreamKit/OpenDreamKit.github.io/blob/master/_data/proposal.yml

To update it when the proposal is modified:

    cd <ODK>/Proposal
    make install-proposal-metadata

**Comment by bpilorget** [comment]
Deliverables due M18 were generated automatically today. Still need to check if blogposts must be added to deliverables. In the making

**Comment by kohlhase** [comment]
I have added that to the official LaTeX-proposal.

**Comment by nthiery** [comment]
Thanks @kohlhase!
@bpilorget : please either check the box above if all blogposts have been added. Otherwise please reopen the issue.
