### ISSUE TITLE
Periodic technical report

### ISSUE THREAD

**Issue by nthiery** [OpenDreamKit/OpenDreamKit#221]
For the project review, we need to prepare a Periodic Technical Report.

This can essentially be an updated (and maybe fleshed up a bit?) version of D1.3: Internal Progress Report for year 1 #19 and it's followup D1.5 for year 3 #21.

In principle, it just have to be delivered on the day of the review, but it would be good to provide it to the reviewer some time in advance so that they can have the time to read it.

**Comment by nthiery** [comment]
Thanks @bpilorget for the initial file and everyone for starting to flesh it up. I have added the appropriate style files and did some tweaks on the latex file. It now compiles smoothly.
We should submit it to the reviewers by the end of the week. Please keep the work on it up!

**Comment by VivianePons** [comment]
All done for WP2!

**Comment by nthiery** [comment]
Oops #221 and #227 duplicate each other. I am closing this one since more discussions happened on the other side.
