### ISSUE TITLE
Organize the First Reporting Period review meeting in Brussels and follow up workshop

### ISSUE THREAD

**Issue by nthiery** [OpenDreamKit/OpenDreamKit#223]
# General

- [X] [Web page](http://opendreamkit.org/2017/04/24/first-project-review/) @bpilorget
- [x] Manage participants @bpilorget
- [x] Quality Review Board meeting? @fangohr
- [x] Steering Committee meeting @bpilorget
- [x] Invite members of the advisory board; organize a meeting thereof? @nthiery / @bpilorget
- [x] [Slack channel](https://opendreamkit.slack.com/messages/C51ASH3V3/)

# Review meeting

See #222

# Brussels Premises

[CLORA](http://www.clora.eu/)
[Avenue des Arts, 8](https://www.google.be/maps/place/Kunstlaan+8,+1210+Sint-Joost-ten-Node/@50.8493378,4.3424626,14.25z/data=!4m5!3m4!1s0x47c3c37d43cc0845:0x5bb9d80283d77220!8m2!3d50.8481962!4d4.3698149)
1210 Saint-Josse-ten-Noode

- Monday 24/04:
    - Rooms "Hergé" and "Magritte" booked from 9 am until 12:30 O'clock
        -> "Hergé" for Quality review Board (meeting begin at 10:30 AM), only open to the QRB members and the Coordinator
        -> "Magritte" for those who wish to begin to practise presententaison etc.
    - LUNCH
    - Rooms "MONTOYER" & "MAGRITTE" - booked from 12:30 until 20:30 PM
        - Brief Steering Committee after lunch ([Agenda](http://opendreamkit.org/2017/04/24/brussels-steering-committee/))
        - Rehearsals in the afternoon. Put your comments on https://hebdo.framapad.org/p/wp-presentations

- Tuesday 25/04: Rehearsals all day, Rooms "MONTOYER" & "MAGRITT"E- from 8:30 AM until 20:30 PM

- Wednesday 26/04: REVIEW, Room "DELVAUX-PICASSO"- booked from 8:00 AM until 18:00 PM

# Workshop after the review

- Will take place in Brussels, around Dima et al's AirBnB, Rue Royale, halfway between stations Gillon and Sainte Marie (ask for number), slightly north of station Botanique. Walkable from CLORA. 
- For attendance: https://framadate.org/MPxYiQTu1JZjHuJp

**Comment by jdemeyer** [comment]
@pdehaye The person I know at VUB (Vrije Universiteit Brussel) and who is a GAP package developer is not available during that week. I am not really inclined to let the workshop be organised by somebody who is totally unrelated to ODK. So I think that Gent would be the best location for the follow-up meeting on thursday and friday.

**Comment by jdemeyer** [comment]
Do you have an idea on the practicalities of the Brussels -> Gent move? Is the plan that participants would stay a few days in a hotel in Brussels and then a few days in Gent? If so, it would be most practical to decide on a common time to move. I assume that the dinner after the review will be in Brussels, so it looks most practical to move Thursday morning.

The fast train from Brussels-Central to Gent takes about 35 minutes, so that's not an issue.

**Comment by JohnCremona** [comment]
More practical questions: I am planning to book my travel soon, arriving
late afternoon Sunday and leaving early Thursday.  Where in Brussels will
we be staying?  Has someone decided on a hotel?

**Comment by nthiery** [comment]
> Where in Brussels will we be staying? Has someone decided on a
> hotel?

@bpilorget: could you please have a look at this? Unless one of our
Belgium fellows would have some specific suggestions?

**Comment by jdemeyer** [comment]
I don't have any particular suggestion. But I'm sure that there are plenty of places to stay near the review location (I added the address in the issue description).

**Comment by pdehaye** [comment]
Me neither. Haven't lived there in a long time... and certainly not organized à conference !
Paul

**Comment by bpilorget** [comment]
@OpenDreamKit/participants 
The Commission has negotiated prices for researchers and experts coming to brussels for EU project matters. Here is the pdf version of the list of hotels with negotiated prices: http://ec.europa.eu/research/participants/data/support/expert/hotel-list_en.pdf. They are all in the area of the CLORA premises.

We at Paris-Sud advise and will go to the Best Western hotel (page one of the PDF). What you need is to send by mail to the hotel the printed and filled in page 9 of the PDF.
Let's all try to go the same hotel but if you prefer to go somewhere else you can.

**Comment by bpilorget** [comment]
@jdemeyer Yes, we are planning to organise a dinner on the Wednesday evening in Brussels, so the move from Brussels to Ghent will take place on the Thursday morning if possible.

**Comment by bpilorget** [comment]
For the record, it was technicaly not possible to have the rehearsals in the same room as the one booked for the Review. However it is in the same building, with the same infrastructures and I know people working there so things should be smooth.

**Comment by jdemeyer** [comment]
Is there a chance of getting 2 beamers? I can imagine this would be useful, for example to use for presentation slides and a second one for demonstrating the software. I would certainly use 2 beamers if I could.

**Comment by nthiery** [comment]
On Wed, Mar 08, 2017 at 12:39:53PM -0800, jdemeyer wrote:
>    Is there a chance of getting 2 beamers? I can imagine this would be
>    useful, for example to use for presentation slides and a second one for
>    demonstrating the software. I would certainly use 2 beamers if I could.

That would be nice indeed. Benoit?

Worst case, I have a small portable LCD beamer I could possibly bring
with me; although I don't know if it's powerful enough for a larger
room; besides I'll be flying from Montreal.

**Comment by jdemeyer** [comment]
> Worst case, I have a small portable LCD beamer I could possibly bring with me; although I don't know if it's powerful enough for a larger room; besides I'll be flying from Montreal.

In that case, I guess it's easier if I bring one from Gent.

**Comment by bpilorget** [comment]
I will ask for the beamers. Me and viviane can bring beamers from UPSUD in any case. No need for Nicolas to fly from Montreal with this in your luggage :)

**Comment by dimpase** [comment]
Anyone interested in sharing an AirBnB apartment instead of Best Western? Would be about half the price, I think.

**Comment by nthiery** [comment]
>    Anyone interested in sharing an AirBnB apartment instead of Best
>    Western? Would be about half the price, I think.

If it's nearby the hotel, I am on it. Do you mind investigating what's
available?

**Comment by dimpase** [comment]
I am about to book a place that will be able to host 3 or 4 people, it is 800m from the hotel.

**Comment by dimpase** [comment]
OK, I've booked the place mentioned in the previous comment;
it has 4 beds in 3 rooms, that is to say that we (I assume Nicolas is joining) are looking for 1 or 2 more persons to stay there, too.

**Comment by nthiery** [comment]
>    OK, I've booked the place mentioned in the previous comment;
>    it has 4 beds in 3 rooms, that is to say that we (I assume Nicolas is
>    joining) are looking for 1 or 2 more persons to stay there, too.

I confirm. Thanks Dima for the booking!

**Comment by florian-rabe** [comment]
I'm confused about the state of the follow-up workshop.

Moving to a different city for two days seemed strange in the first place, and as far as I can see (Maybe I'm missing something?) there is not much organization going on.

The ODK participants seem to be unconvinced of the follow-up workshop, too: The poll for attendance shows only a few participants.

* Is it worth having it at all in the present form?
* Would it make more sense to instead stay an extra day in Brussels?

**Comment by kohlhase** [comment]
Dear all,

I will not be able to do the thursday, and I am not thrilled to come
back for the friday, so I would be happy if we substituted some other
meeting for WP6.

Michael

**Comment by nthiery** [comment]
About the location: the rationale for moving to Gent was that we don't
have a meeting room in Brussels and accommodation is expensive there.

About the topic: as planned, that was to be decided depending on
potential participants. Here is the list:

        Nicolas, Paul, Dima, Jeroen, Min?, Michael?, Erik, Luca? Florian?

        plus our invitee Thomas

So few people available and not a clearly emerging theme.

- Option 1: just cancel that workshop; too bad, did not work out.

- Option 2: have a WP6 sprint with Paul, Florian, Thomas. If it's just
  so few of us one option would be to just extend the rental of our
  Airbnb apartment and stay and work there. Dima: could you check on
  the availability?

- Option 3: anyone else in the above list wanting to run a sprint?

It would be best to decide today, as I need to validate my plane
tickets from Montreal by this evening.

With my move to Montreal in three days, I am in submarine mode. So
someone please lead the discussion.

Cheers,
                                Nicolas

**Comment by dimpase** [comment]
Cancelling the workshop is a bit too late for me at least, I already booked my ticket to Brussels.
(well, I can find something to do there or in the neighbourhood...)

I'll check whether AirBnB can be extended now.

**Comment by jdemeyer** [comment]
> I'm confused about the state of the follow-up workshop.

The main reason to have the follow-up workshop was to have something "fun" to do after the review. I agree that staying in Brussels might have made more sense, but it didn't work out to organize that (there are universities in Brussels but there is nobody close enough to ODK to organise something). So then we decided to move to Gent.

> Moving to a different city for two days seemed strange in the first place, and as far as I can see there is not much organization going on.

Well, it's only two days and a few people, so not much needs to be organised. I can assure you that things will be organised as needed.

> The ODK participants seem to be unconvinced of the follow-up workshop, too: The poll for attendance shows only a few participants.

Fine for me.

>     Is it worth having it at all in the present form?

I'd leave that to the participants to decide. Even if we don't have a lot of people in Gent, it could still be interesting I think.

**Comment by pdehaye** [comment]
I just had a chat with Nicolas, and offered to take over organisation if it
takes place in Brussels.
I think this would be best, given that we can easily find a good space
there for the number of people we are, possibly the AirBnB. Jeroen, thanks
for offering repeatedly to host, but one has of course to factor in the
individual trouble of moving from one place to another, finding bearings,
etc.
Dima, let me know ASAP if the AirBnB does not work out. If it doesn't, I
can start looking for something else.
Paul

**Comment by jdemeyer** [comment]
Fine for me.

**Comment by dimpase** [comment]
Yes, it's possible to extend (for 1 or 2 days - I didn't check for more). Tell me the exact departure day (I will leave on Friday evening).
I suppose we can negotiate with the host to leave in the afternoon rather than in the morning...

**Comment by pdehaye** [comment]
I think Friday afternoon would work well. By later we will be a very small
group indeed!
Paul

**Comment by minrk** [comment]
It is my current plan to participate in the Thursday part of the workshop, returning Thursday evening. But I don't know what work is planned during the workshop, so I'm not sure if it's useful to people for me to stick around. I can get a cheaper/earlier flight home if the workshop is focused on other things.

**Comment by jdemeyer** [comment]
> But I don't know what work is planned during the workshop, so I'm not sure if it's useful to people for me to stick around.

I would certainly find it interesting to discuss some Jupyter-relating things.

**Comment by minrk** [comment]
@jdemeyer Perfect! Then I'll leave Thursday evening on the latest flight I can book.

Since I won't stay Thursday night, the Gent / Brussels move doesn't matter too much to me, other than potentially consuming workshop time early on Thursday.

**Comment by minrk** [comment]
@dimpase I'd like to join the AirBnB if there's still a slot. I'll be there Sunday-Thursday.

**Comment by dimpase** [comment]
@minrk OK, great, you are in! please email me what I should enter as your contact details for the AirBnB host.

**Comment by florian-rabe** [comment]
I understand we're converging on a Thursday and possibly Friday workshop in Brussels.

Then I'll book accordingly.

If it helps with organizing, I'm fine having the follow-up meeting in a very informal environment.

**Comment by takluyver** [comment]
> plus our invitee Thomas

Just to check, is that me, or another Thomas? If it's me, I've totally missed the invitation.

**Comment by pdehaye** [comment]
Different Thomas. Will explain if he actually comes, and not through GitHub
notifications, maybe.

**Comment by dimpase** [comment]
OK, AibBnB is rebooked so that we depart on Friday, and also a confirmation that on Friday we can stay longer for 1/2 day extra price. @nthiery - could you confirm your AirBnB invite?

**Comment by videlec** [comment]
I will be around the whole week and available for the workshop in Bruxelles or Gent.

@dimpase I have my own accomodation in Bruxelles. No airbnb for me.

**Comment by pdehaye** [comment]
So to confirm we are all on the same page: the extra two days some of us will stay in Brussels, not too many though, so it will actually be possible for all to work together in the AirBnB. 
Correct? If so I or someone else should send a separate message to the list of participants because I am afraid this info is buried here in notifications not everyone is reading. 
Paul

**Comment by bpilorget** [comment]
@pdehaye It seems so. @jdemeyer please take the lead on this. Nicolas is currently packing for Canada and won't be back to work before Monday I'm afraid. Here is the Review poll if it can be of some help for the organisation: https://framadate.org/MPxYiQTu1JZjHuJp

**Comment by pdehaye** [comment]
I promised I would take the lead if it was in Brussels so I will do an announcement separately on that. Will gather needed information first with individuals who have it. 
Thanks Benoît for sending the poll which I had lost. 
Paul

**Comment by nthiery** [comment]
Thank you Paul for leading this and Jeroen for all the time taken
previously investigating the options in Gent! Sorry for the last
minute change of plan ...

**Comment by embray** [comment]
Nearly forgot this is already coming up 😨   I'm planning my travel now, but I'll probably just be there Monday/Tuesday/Wednesday and head home Thursday.

**Comment by slel** [comment]
I'd like to attend, at least Mon-Tue (more if I can arrange it). I can stay at my brother's in Brussels.

**Comment by fangohr** [comment]
Name badges: All and @nthiery @bpilorget  - I think it would be professional and useful to have name badges for all participants (reviewers and OpenDreamKit members). 

It may be too late now for properly printed ones (although Wednesday is far away ...), but the very least we could bring stickers and pens so that people can write their name and stick on their shirt. (Or slightly better: print names on stickers, and stick those on shirt).

For the reviewers, this is the only hope of putting names of people to faces. They may have read our deliverable reports, and will find it useful to target individuals with particular questions etc - just helps with transparency. Introductions in the morning are nice, but nobody can be expected to remember 10+ people when being introduced in a 2 minute round.

**Comment by fangohr** [comment]
PS Where is the discussion on the demonstrator sessions? Have we got a dedicated issue for this? Couldn't find it right now - thank you!

**Comment by nthiery** [comment]
On Wed, Apr 19, 2017 at 04:31:09AM -0700, Hans Fangohr wrote:
>    Name badges: All and [1]@nthiery [2]@bpilorget - I think it would be
>    professional and useful to have name badges for all participants
>    (reviewers and OpenDreamKit members).

+1

@bpilorget: could you prepare some? Please include the reviewers and PO.

Thanks in advance,

**Comment by nthiery** [comment]
>    PS Where is the discussion on the demonstrator sessions? Have we got a
>    dedicated issue for this? Couldn't find it right now - thank you!

For now, this is #222. If there starts to be more traffic, we will
split a a separate issue just for the demonstrations.

**Comment by bpilorget** [comment]
OK for the badges but probably some people are coming that are not planned to yet (for deliverables or demonstrators etc). I think it's safer, cheaper (and it will save me time in this busy week!) to use stickers. I'll check if we have some aat the laboratory, if not we ccan buy them in a regualr shop.

**Comment by dimpase** [comment]
`-1` for stickers, as they fall off. I can bring proper badge pockets with clips. How many do we need?

**Comment by jdemeyer** [comment]
Do we have a timetable for monday/tuesday? In particular, at what time do we start?

**Comment by JohnCremona** [comment]
On 20 April 2017 at 16:07, jdemeyer <notifications@github.com> wrote:

> Do we have a timetable for monday/tuesday? In particular, at what time do
> we start?
>

That would be useful to know.  On a more practical level -- I'll be
arriving at the eurostar station just after 8pm, is anyone else arriving at
a similar time?  My plan is to take a taxi to the hotel (Best Western) and
find something to eat -- I assume some others are staying there too?

Sorry to detract attention from the serious business of preparations.  I am
looking forward to the various presentations and am happy to do some
(proof)reading if that would be helpful.

John

**Comment by dimpase** [comment]
I come by Eurostar, but only at 11pm. Anyhow, the hotel (or our AirBnB) is about 2.5km from the station, 15 minutes with direct metro lines (2 or 6) to Kruidtuin (a.k.a. Botanique).

**Comment by jdemeyer** [comment]
FYI: with any train ticket to Brussels, you are allowed to take the train to any other train station in Brussels. So you could also take the train to Brussels-North and walk from there.

**Comment by bpilorget** [comment]
PRACTICAL INFORMATION IS ONLINE (on this issue and on the webpage dedicated to the meeting):
- Monday 24/04:
    - 10:30: Quality review Board, Room "MAGRITTE" - Only open to the QRB members and the Coordinator. There is anyway not enough room for everyone
    - LUNCH
    - Rooms "MONTOYER" & "MAGRITTE" - booked from 12:30 until 20:30 PM
        - Brief Steering Committee after lunch ([Agenda](http://opendreamkit.org/2017/04/24/brussels-steering-committee/))
        - Rehearsals in the afternoon

- Tuesday 25/04: Rehearsals all day, Rooms "MONTOYER" & "MAGRITT"E- from 8:30 AM until 20:30 PM

- Wednesday 26/04: REVIEW, Room "DELVAUX-PICASSO"- booked from 8:00 AM until 18:00 PM

**Comment by pdehaye** [comment]
Another practical piece of advice along the same lines as what Jeroen said
regarding trains: Brussels has an unbeatable plan for citi-bike rentals, if
you feel slightly adventurous.
For 8EUR/week, 1.60 EUR/day, you can take one of those city bikes an
unlimited number of times for 30 minutes at a time, at no extra cost.
http://en.villo.be/Rates/Rates/Consult-the-rates
Paul

**Comment by bpilorget** [comment]
By the way @dimpase I am bringing pin clip badges for everyobe. You needn't bring some. Also with me a second beamer and two pointers. For those with a MAC please bring adequate plugs for beamer.

**Comment by nthiery** [comment]
Hi all; I am in Brussels. If you are already around, you are welcome to join at our appartment.
For details, and live discussion about the meeting, see our [slack channel](https://opendreamkit.slack.com/messages/C51ASH3V3).
See you soon!

**Comment by kohlhase** [comment]
could you invite me as michael.kohlhase@fau.de to the slack channel. It seems that I do not have access otherwise.

**Comment by kohlhase** [comment]
Dennis and I are in the train still, we will be in Brussels-Nord about 19:30. 
Maybe we can have dinner together?

**Comment by dimpase** [comment]
I also cannot seem to be able to use slack without an invite.

Thx
Dima

**Comment by fangohr** [comment]
Hi @dimpase and @kohlhase -  I have invited you to the channel. Anybody else?

I have also made Nicolas and Benoit admins for the Slack channel, so that they can invite more people.

**Comment by tkw1536** [comment]
It would be great if I could get an invite for the slack channel also.

**Comment by nthiery** [comment]
>    It would be great if I could get an invite for the slack channel also.

Done.

For other candidates: please send me or Hans a private query.

**Comment by JohnCremona** [comment]
On 23 Apr 2017 18:03, "Michael Kohlhase" <notifications@github.com> wrote:

Dennis and I are in the train still, we will be in Brussels-Nord about
19:30.
Maybe we can have dinner together?

Are you here yet?  I just checked in to the hotel.



—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/OpenDreamKit/OpenDreamKit/issues/223#issuecomment-296453358>,
or mute the thread

**Comment by JohnCremona** [comment]
After Googling "slack channel" I think I prefer food.


On 23 Apr 2017 19:58, "Nicolas M. Thiéry" <notifications@github.com> wrote:

> It would be great if I could get an invite for the slack channel also.

Done.

For other candidates: please send me or Hans a private query.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/OpenDreamKit/OpenDreamKit/issues/223#issuecomment-296468204>,
or mute the thread

**Comment by kohlhase** [comment]
We are at Nicolas' appartment. We are cooking pasta with him and Min.

Do you want to join, call me at +49 152 049 18243.

Michael

**Comment by JohnCremona** [comment]
On 23 April 2017 at 20:19, Michael Kohlhase <notifications@github.com>
wrote:

> We are at Nicolas' appartment. We are cooking pasta with him and Min.
>
> Do you want to join, call me at +49 152 049 18243 <+49%201520%204918243>.
>

Thanks but I had something to eat and will retire.  See you tomorrow

**Comment by nthiery** [comment]
Good morning everyone!
I am at the Clora. Ping me in case there is noone in the lobby to open the door: +33 6 77 90 32 79.
Let's get to work, we have plenty to do!
The goal for this morning is *to have draft slides ready and cross proofread for the mock presentations this afternoon*. Same for demos and poster if at all possible.
Let's use the [Slack channel](https://opendreamkit.slack.com/messages/C51ASH3V3/) for discussions.
See you soon!

**Comment by kohlhase** [comment]
[WP6-Review1.pdf](https://github.com/OpenDreamKit/OpenDreamKit/files/950682/WP6-Review1.pdf)

OK, here are my slides. Please give me feedback.

**Comment by kohlhase** [comment]
and if anybody is interested, the sources are at https://gl.mathhub.info/MiKoMH/talks/tree/master/source/ODK/talks but they are in sTeX, so this may be of limited utility.

**Comment by jdemeyer** [comment]
> WP6-Review1.pdf
> 
> OK, here are my slides. Please give me feedback.

Just had a quick look. It's of course hard to judge slides without the presentation, so just a remark: make sure to have sufficient introduction (for example, take time to explain the context and the concept "Math in the Middle"). I feel like the slides jump right in and if you are not careful, people might get lost already on slide 2 or 3.

**Comment by JohnCremona** [comment]
Nicolas I am at the Covent Garden reception having a hard time explaining
who I am .  They do not recognise CLORA

On 24 Apr 2017 9:13 a.m., "Nicolas M. Thiéry" <notifications@github.com>
wrote:

Good morning everyone!
I am at the Clora. Ping me in case there is noone in the lobby to open the
door: +33 6 77 90 32 79 <+33%206%2077%2090%2032%2079>.
Let's get to work, we have plenty to do!
The goal for this morning is *to have draft slides ready and cross
proofread for the mock presentations this afternoon*. Same for demos and
poster if at all possible.
Let's use the Slack channel
<https://opendreamkit.slack.com/messages/C51ASH3V3/> for discussions.
See you soon!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/OpenDreamKit/OpenDreamKit/issues/223#issuecomment-296550991>,
or mute the thread

**Comment by kohlhase** [comment]
Here is also the poster. 
[WP6-poster.pdf](https://github.com/OpenDreamKit/OpenDreamKit/files/951344/WP6-poster.pdf)

and again the sources are at  https://gl.mathhub.info/MiKoMH/talks/tree/master/source/ODK/talks

**Comment by wbhart** [comment]
Michael,

On page 3, what does the WS stand for (in the WP6 WS abbreviation)?

interest on -> interest in

page 7: if all are t -> if all are T ??

**Comment by ClementPernet** [comment]
The first version of the WP5 presentation slides:
[WP5_pres-v1.pdf](https://github.com/OpenDreamKit/OpenDreamKit/blob/master/ReportingPeriod_1/Presentations/WP5/WP5_pres-v1.pdf)
Sources are in https://github.com/OpenDreamKit/OpenDreamKit/blob/master/ReportingPeriod_1/Presentations/WP5/

**Comment by videlec** [comment]
I suggest to gather all comments on presentation at

    https://hebdo.framapad.org/p/wp-presentations

**Comment by hivert** [comment]
Fast rereading: 

- Slide 13 appears twice
- Slide 18 integeration (does it mean rounding to the nearest integer ? ;-)

**Comment by videlec** [comment]
@hivert could you put it on the pad https://hebdo.framapad.org/p/wp-presentations ?
