### ISSUE TITLE
Effective use of communication channels: mailing lists, issue comments, slack, gitter, ...

### ISSUE THREAD

**Issue by nthiery** [OpenDreamKit/OpenDreamKit#225]
This issue is to discuss how to best use our communication channels (mailing lists, comments on issues, slack, gitter) for effective communication, leaving a usable history behind and not flooding our fellow participants. As outcome of the discussions, some recommendations should be inserted in our [project README](https://github.com/OpenDreamKit/OpenDreamKit/blob/master/README.md#project-discussions)

**Comment by nthiery** [comment]
@alex-konovalov on the participants mailing list:
> GitHub repo was flooded indeed. Unless we need to preserve all
> micro-comments on GitHub as an evidence or for analysis of social
> aspects, are we free to delete various non-essential comments
> which obscure the big picture and pollute the history in the issues?
>
> As I've already said before, it hard to cope with the intensity of
> notifications from GitHub. That's not only one project for which
> I am receiving notifications, and although I am trying to stay on
> top and read them with a high priority, it's not difficult to
> overlook things.
>
> Although I am not a big fan of Gitter, I think it is better than
> GitHub for real-time micro-managing and coordinating, so I can make
> an effort to keep it open more often (I don't use IRC any more, and
> use Slack, so I can manage to use two such apps, but not three).
> Is there a way to participate in Gitter discussions from Slack, BTW?

**Comment by nthiery** [comment]
About the flood of github notifications: it's supposed to be easy to configure github notifications to various levels of verbosity. E.g. to only get noticed on issues were one has been explicitly @mentionned. Could someone report on this? It's my job to watch everything (hmm, big brother of some kind?), so I am not a good test case myself.

I agree with recommending the use of chat (gitter/slack/appear/pads) for real-time micro management. To let the information flow and remain, it's good though to put at the end a brief summary of the conversation in the github issue.

I would tend not to clear the issue history (up to, of course, cleaning e.g. one's own message from potentially offensive material one may have said under the pressure of emotion, without really meaning it). You never quite know in advance what information will be relevant in the long run. And indeed it's an interesting trace of the social aspects. It's the role of the github issue description (i.e. first comment) -- and of the report -- to hold a synthesis / overview.

**Comment by willfurnass** [comment]
@nthiery It looks like there might be two mechanisms for disabling automatic email notifications (other than explicit mentions) for your Organizations' repositories:
 - Turn off 'watching' per repo: https://github.com/watching
 - Disable automatic watching when you are given push access to a repo: https://github.com/settings/notifications

I'll give those a test.

**Comment by alex-konovalov** [comment]
Of course, there is no universal solution since each of us has different habit of working with emails and Github. I certainly know that the user can switch off watching per repository but that is not something that I want to. I also know that I can set up mail rules and they will be put into some mailbox - also not something that I want to, because then I will never look at them. So my fate is to have them in my inbox and try to delete them as soon as I see that they need not to be stored, or read and move them to an ODK mailbox. 

I hope that slack or gitter for "real-time micro management" should work for us - with the following rule: nobody should rely that a particular person or everyone will read each post. This is a transient channel. If you had a discussion in it, you may want to summarise it in an issue on GitHub.

OK not to clean up issues history then.

**Comment by nthiery** [comment]
On Fri, Mar 03, 2017 at 02:42:17AM -0800, Alexander Konovalov wrote:
>    Of course, there is no universal solution since each of us has
>    different habit of working with emails and Github. I certainly know
>    that the user can switch off watching per repository but that is not
>    something that I want to.

For most participants it would be fair to only watch issues where they
are @mentioned explicitly. Especially for people like you that monitor
on slack/gitter the creation of new issues and can decide to
explicitly watch those of interest. Of course you are a more advanced
participant so your mileage may vary.

> I also know that I can set up mail rules and they will be put into
> some mailbox - also not something that I want to, because then I
> will never look at them.

+1

> I hope that slack or gitter for "real-time micro management" should
> work for us - with the following rule: nobody should rely that a
> particular person or everyone will read each post.  This is a
> transient channel. If you had a discussion in it, you may want to
> summarise it in an issue on GitHub.

+1

Even for issues, I don't expect anyone to read anything where they are
not explicitly mentioned.

**Comment by defeo** [comment]
> About the flood of github notifications: it's supposed to be easy to configure github notifications to various levels of verbosity. E.g. to only get noticed on issues were one has been explicitly @mentionned. Could someone report on this?

I confirm @willfurnass findings. As watchers of this repo, we're automatically subscribed to all issues and pull requests made to it (unless you've configured your global preferences not to be notified for issues/pull requests/etc.).

You can also subscribe/unsubscribe to individual issues: click the "unsubscribe" button in the (right) sidebar of this issue, and you will stop receiving emails for this issue alone.

You can also do the opposite: stop *watching* this repo, and individually subscribe to issues you're interested in. You may risk missing some new issues that concern you, but if those who created the issue want to send you a head-up, they just need to @-mention you.

**Comment by defeo** [comment]
> I agree with recommending the use of chat (gitter/slack/appear/pads) for real-time micro management. 

I find it very hard to reach people on gitter: the only ones I can constantly find through it are Alex, POD and Hans. Even you, @nthiery, are pretty hard to wake-up via Gitter. I think we should encourage people to activate gitter mail notifications when they are @-mentioned (top-right menu, "Room settings").

It was decided to not use Slack, so I would avoid duplicating our channels, as that may only lead to more unavailability.
