### ISSUE TITLE
Periodic Technical Report - Part B

### ISSUE THREAD

**Issue by bpilorget** [OpenDreamKit/OpenDreamKit#227]
# Periodic Technical Report for Reporting period 1

- *Period covered*: from 01/09/2015 to 28/02/2017
- *Internal deadline*: 16/04/2017
- *Authors:* WP leaders, coordinator, administrator
- **[Final report](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/ReportingPeriod_1/Technical_Report/report-final.pdf)**, [Source file](https://github.com/OpenDreamKit/OpenDreamKit/blob/master/ReportingPeriod_1/Technical_Report/report.tex)

For the project review, we need to prepare a Periodic Technical Report. Part B is the scientific part of it. It can essentially be an updated (and maybe fleshed up a bit?) version of D1.3: Internal Progress Report for year 1 #19 and its followup D1.5 for year 3 #21.

In principle, it just have to be delivered on the day of the review, but it would be good to provide it to the reviewers and advisory board some time in advance so that they can have the time to read it. Hence the deadline.

The WP leaders are in charge of summarizing their activities for their WP, on a task per task basis.

- [x] WP1 @bpilorget, @nthiery
- [X] WP2 @VivianePons 
- [x] WP3 @defeo 
- [x] WP4 @minrk 
- [x] WP5 @ClementPernet 
- [x] WP6 @kohlhase 
- [x] WP7 @dimpase 

The coordinator is in charge of the rest (help and proofreading welcome though :-))

**Comment by bpilorget** [comment]
@nthiery @VivianePons @defeo @minrk @ClementPernet @kohlhase @dimpase 

As you know, a Periodic Technical Report is due for the Review (26/04/2017). The coordinator and the Work Package leaders are in charge of this. I addedthe official template to our repository here: https://github.com/OpenDreamKit/OpenDreamKit/blob/master/Periodic%20Report/RP1/report.tex

We discussed this with Nicolas and we think the best would be to have this report ready before the review in order to send it to our advisors so that we can have their insight for the review. Hence the tentative deadline is 16/04/2017.

**Comment by bpilorget** [comment]
@nthiery @VivianePons @defeo @minrk @ClementPernet @kohlhase @dimpase
I filled in most of the WP1 section. You can take it as an example for your own WP you are leading.

**Comment by minrk** [comment]
Thanks, @bpilorget!

**Comment by bpilorget** [comment]
PING

**Comment by kohlhase** [comment]
I am not sure what I should do here. 

I have committed a version that fixes all LaTeX problems except one (a WPref, where I do not know the target). The report now has a title (see the stuff after the ```\makeatletter```).

**Comment by bpilorget** [comment]
Thanks. Nicolas meant to find a solution for the title.
As WP6 leader you must write a summary of the activities of WP6, task per task. You can follow the example of WP1 if you don't see what I mean.

**Comment by minrk** [comment]
I've filled out WP4 with one exception: I'm not sure what to put for D4.11 (#79) the micromagnetic VRE case study. Perhaps @fangohr could provide a brief report there?

**Comment by fangohr** [comment]
Yes, @minrk, I am on the case for D4.11. 

Related question from briefly reviewing the report: do we collect publication in the report (I don't think we do at the moment), and/or do we report them anywhere? Should we?

**Comment by nthiery** [comment]
Good question. I would say no. On the other hand, we probably want to put figures about the publications.

In general, @bpilorget, where should we report on the KPI's? Here, in Part B of the Tech report?

**Comment by nthiery** [comment]
Thanks @VivianePons and @bpilorget  for leading the move with the WP1 and @WP2 part! Thanks @minrk, @fangohr for the WP4 part. I am about to proofread them.

**Comment by kohlhase** [comment]
I am currently working on WP6, you should expect a push before tonight.

**Comment by bpilorget** [comment]
Publications are reported on the Part A of the Report for which I and Nicolas are in charge.
KPIs are to be shortly reported in the WP1 of the technical report but the real report will happen at the presentation I think.

This is what I did for the other project and it went smoothly.

**Comment by bpilorget** [comment]
@nthiery I haven't had the chance to work again on the report until now because of other more urgent things but I should be roughly 100% on ODK until the Review now.

**Comment by kohlhase** [comment]
I have just pushed what I intend to write for WP6. I have commented on all the tasks that have started (according to the proposal) before Month 18. In particular, I left out all the others. Is that correct?

**Comment by kohlhase** [comment]
There are still a couple of citations in the text. As always I think we should have citations at least of our own publications in the report. But I can eliminate them if so decided.

**Comment by kohlhase** [comment]
The structure of the report is still quite ugly, since the subsections (for the work pacages ) are much less conspicuous than the task headings. We should do something to the macros there. I would just move away from the ```amsreport``` class we use as a base class here.

**Comment by bpilorget** [comment]
For the tasks that haven't begun, please put a title for them and include below somehting like "non applicable for this period" or "has not begun yet".

**Comment by kohlhase** [comment]
OK, done that. You should probably check that all of us have done so before you submit.

**Comment by dimpase** [comment]
While trying to `make` the report I get
```
$ make
cp Proposal/LaTeX-proposal/eu/eudelivreport.cls WP5/D5.4/eudelivreport.cls
cp: not writing through dangling symlink ‘WP5/D5.4/eudelivreport.cls’
Makefile:17: recipe for target 'WP5/D5.4/eudelivreport.cls' failed
make: *** [WP5/D5.4/eudelivreport.cls] Error 1
```
what should be done to fix this?

**Comment by nthiery** [comment]
I'll check that out. For now, just run pdflatex on the file. Cheers,

**Comment by dimpase** [comment]
@nthiery  I see, that symbolic link has to removed by force on my desktop system---it has slightly odd settings for preserving files.

**Comment by dimpase** [comment]
how about references in the report? presently there is nothing on how to get the right bibfiles there.

**Comment by nthiery** [comment]
Yup. Somehow I had forgotten those links while fixing #212. Fixed and pushed.

**Comment by nthiery** [comment]
+1 on references. I added relevant bibtex stuff to the file.

Actually this is using biber, following what we have done in our deliverables. We probably should update our makefile to use biber instead of latex (gosh, it's slow though ...).

**Comment by nthiery** [comment]
@minrk: I pushed some minor edits to the WP4 section and inserted a few TODO's.

**Comment by ClementPernet** [comment]
WP5 is now finished and ready for proofreading.

**Comment by jdemeyer** [comment]
Where exactly is the file? The "Source file" link on the top of this issue doesn't work.

**Comment by ClementPernet** [comment]
@jdemeyer : I've updated the link to the source file

**Comment by dimpase** [comment]
there is no deliverable tagged `hpc-gap`, only a task. Thus ugly TeX errors.

**Comment by dimpase** [comment]
WP7 part is ready for reviewing.

**Comment by bpilorget** [comment]
Thanks toa ll. Only @defeo's and @nthiery's parts missing (first two sections for Nicolas)

**Comment by ClementPernet** [comment]
@dimpase : Fixed the hpc-gap delivreable issue.

**Comment by dimpase** [comment]
@ClementPernet - sorry, no, you haven't. You did something totally orthogonal:
```
-Task~\taskref{hpc}{hpc-gap} is the next  
+Task~\taskref{hpc}{GAP-HPC-report} is the next
```
--(long)taskref is OK, the (long)delivrefs are not... E.g. `l.554 Deliverable~\delivref{hpc}{hpc-gap}` still does not compile.

**Comment by alex-konovalov** [comment]
May I suggest to use line breaks in the source file - this would make it much more readable via the GitHub's mail interface. Thanks.

**Comment by ClementPernet** [comment]
Oups, my bad. Sorry for noise. I pushed the fixed refs.

**Comment by nthiery** [comment]
Thanks @ClementPernet for your section on WP5. I just proofread it and it's good to go.

**Comment by nthiery** [comment]
Thanks @dimpase for your section on WP7. Could you flesh it up a bit so that the reader could get a better sense of the context and how each piece of work fits into it? The abstracts of our WP7 deliverables is probably a good source of pieces of language to reuse/adapt.

**Comment by nthiery** [comment]
Dear WP leaders ( @OpenDreamKit/coordination )

I have laid out the ground and started fleshing up the Objectives section, in which we are supposed to explain how the work we achieved actually contributes to the project Objectives. This is also the occasion to help the reader get the big picture:

https://github.com/OpenDreamKit/OpenDreamKit/blob/master/ReportingPeriod_1/Technical_Report/report.tex#L65

I believe this boils down to briefly highlighting, for each objective, the relevant achievements (with links to the corresponding tasks), possibly with some additional explanations. I have already done so for some of the objectives, and won't be touching this section until tomorrow. Could you read through it and add items and/or explanatory language as you see fit?

Thanks,

**Comment by nthiery** [comment]
I have fleshed up a bit the "Infrastructures" section:

https://github.com/OpenDreamKit/OpenDreamKit/blob/master/ReportingPeriod_1/Technical_Report/report.tex#L1083

Could someone (maybe @minrk?) proofread it, and possibly expand on it? @kohlhase: would you want to say something about MathHub here?

**Comment by defeo** [comment]
Sorry for being late at the party! The easter bunny just brought the WP3 section :)

Ready for proofreading. It's missing info on #53, I'd need @fcayre's input on that. And @fangohr might want to doublecheck the part on #57.

Happy egg chase!

**Comment by fangohr** [comment]
Thanks, Luca. The part on #57 is okay. Thanks for pinging me.

**Comment by nthiery** [comment]
I am confused, I don't see the changes. @defeo, did you push?
The last commit I see locally and on github is 9a6967d2876266fe48c85deb08f45d389568a13e.

**Comment by defeo** [comment]
My bad, forgot to push.

Done

On Sun, Apr 16, 2017 at 2:26 PM, Nicolas M. Thiéry <notifications@github.com

**Comment by nthiery** [comment]
Quick reaction @defeo :-) Thank you!
Proofreading now. If you are still around, could you have a look at the objectives section? Also a few words of introduction to the work package would be nice for the reader.

**Comment by nthiery** [comment]
WP3 Proofread. I reads smoothly, thanks @defeo! I left a couple minor TODO's.

**Comment by nthiery** [comment]
@minrk: there are still some TODO's in your section :-)

**Comment by minrk** [comment]
@nthiery thanks, WP4 TODOs should be addressed.

**Comment by nthiery** [comment]
Thanks @minrk; WP4 is indeed good to go. Could you have a look at the objectives section, in particular objectives 1 and 2?

**Comment by nthiery** [comment]
@OpenDreamKit/coordination: I have just completed the objectives section. It could very much benefit from everyone's attention.
@bpilorget: could you double check that we filled up reasonnably all the required bits?
@defeo, @dimpase: please take care of the remaining TODO's in your WP's section and in the objectives.

The file is fair game; I won't be touching it until tomorrow afternoon, Montreal time. By this time, we really should send it to the reviewers.

Thanks in advance!

**Comment by dimpase** [comment]
@kohlhase which `pdata.sty` must one use? On a machine that does not have "global" `pdata.sty`, e.g. no
```
(/usr/share/texlive/texmf-dist/tex/latex/proposal/base/pdata.sty
Package: pdata 2013/02/13 v1.4 Project Data
```
`make` gives up with 
```
! LaTeX Error: File `pdata.sty' not found.
```
On the other hand, I see
```
$ find . -name pdata.sty
./WP5/D5.4/pdata.sty
./WP6/D6.1/pdata.sty
./WP4/D4.4/pdata.sty
./WP4/D4.2/pdata.sty
./WP4/D4.5/pdata.sty
./Proposal/LaTeX-proposal/base/pdata.sty
```
so that I presume the latter file is the one that one should use, as it is newer (it says: :`\ProvidesPackage{pdata}[2016/12/15 v1.6 Project Data]`)  (and `pdata.sty` in the rest of directories should go, for uniformity of the output etc...).
Note that `WP6/D6.2/pdata.sty` and `WP4/D4.2/pdata.sty` are older versions (dated 2015), actually added by @kohlhase ; while the remaining ones are symbolic links to `./Proposal/LaTeX-proposal/base/pdata.sty`;

**Comment by kohlhase** [comment]
Yes, the last one should be the right one.

**Comment by dimpase** [comment]
@kohlhase OK, see 92a7e14250ac97e751d7eed9f5a41136cd848431

 - the commit message also says what to do to setup this properly.

**Comment by kohlhase** [comment]
Actually, the "right way" is to add the ```LaTeX-proposal``` directory to the ```TEXINPUTS``` environment variable.

**Comment by defeo** [comment]
> @defeo, @dimpase: please take care of the remaining TODO's in your WP's section 

Mostly done: I'm only missing info on T3.4 (#53).

> and in the objectives.

The objectives look good to me.

**Comment by defeo** [comment]
> The file is fair game; I won't be touching it until tomorrow afternoon, Montreal time. By this time, we really should send it to the reviewers.

Oh wait. By "tomorrow afternoon" you meant NOW? You shouldn't be speaking québécois to an EU project :)

I'll write a sentence for T3.4.

**Comment by nthiery** [comment]
>    Oh wait. By "tomorrow afternoon" you meant NOW?

Yes!

> You shouldn't be speaking québécois to an EU project :)

:-)

>    I'll write a sentence for T3.4.

Thanks!

**Comment by bpilorget** [comment]
Hey all. Hope you enjoyed the Easter weekend.
Thanks for all the work carried out for the report. I think it is quite exhaustive now. It can be submitted to the Advisory Board right now.

**Comment by jdemeyer** [comment]
@minrk: I made some edits to the section about T4.12 (CyPari) in 94f51f85097069e4731112af1405f4c9ad1aee44.

**Comment by nthiery** [comment]
For the record: I committed the latest pdf and report-final.pdf, and
added a link from the issue description.

**Comment by bpilorget** [comment]
Report was accepted by the Reviewers
