### ISSUE TITLE
D6.6 GAP/SAGE/LMFDB Interface Theories and Alignment in OMDoc/MMT for System Interoperability

### ISSUE THREAD

**Issue by kohlhase** [OpenDreamKit/OpenDreamKit#247]
- **WP6:** [Data/Knowledge/Software-Bases](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP6)
- **Lead Institution:** FAU
- **Due:** 2018-02-28 (month 30)
- **Nature:** Other

See page 55 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

This is merged from #138 and #139.

cc: @nthiery

**Comment by bpilorget** [comment]
Issue is no more relevant. See #139 for the right issue
