### ISSUE TITLE
D6.10: Curated Math-in-theMiddle Ontology and Alignments for GAP/ SAGE/ LMFDB

### ISSUE THREAD

**Issue by kohlhase** [OpenDreamKit/OpenDreamKit#248]
- **WP6:** [Data/Knowledge/Software-Bases](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP6)
- **Lead Institution:** FAU
- **Due:** 2018-08-31 (month 36)
- **Nature:** Other

See page 55 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

This has been merged from #141 and #142

cc: @nthiery

**Comment by bpilorget** [comment]
Issue is no more relevant. See #142
