### ISSUE TITLE
D6.13: Full-text search (Formulae + Keywords) in OpenDreamKit

### ISSUE THREAD

**Issue by kohlhase** [OpenDreamKit/OpenDreamKit#249]
- **WP6:** [Data/Knowledge/Software-Bases](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP6)
- **Lead Institution:** FAU
- **Due:** 2019-02-28 (month 42)
- **Nature:** Other

See page 55 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

this has been merged from #140 and #134 
cc: @nthiery

**Comment by bpilorget** [comment]
Issue is no more relevant. See #134
