### ISSUE TITLE
Review meeting does not appear in "events" on website

### ISSUE THREAD

**Issue by pdehaye** [OpenDreamKit/OpenDreamKit#276]
Having left ODK for a while, I was looking for information on when the review meeting was. 

I went to the website, and tried all the links related to "events" ("reviews", "project meetings", etc), and never landed [here](https://opendreamkit.org/meetings/2018-10-28-Luxembourg/). 

This is likely to be flagged by reviewers as they try at the last minute to find information about the meeting (cf first review...)

**Comment by nthiery** [comment]
Yeah, just running behind. Done. The post should be up soon.

>    Having left ODK for a while, I was looking for information on when the
>    review meeting was.
> 
>    I went to the website, and tried all the links related to "events"
>    ("reviews", "project meetings", etc), and never landed [1]here.
> 
>    This is likely to be flagged by reviewers as they try at the last
>    minute to find information about the meeting (cf first review...)
