### ISSUE TITLE
Showcase WP5 / HPC work

### ISSUE THREAD

**Issue by nthiery** [OpenDreamKit/OpenDreamKit#289]
We will want to showcase the work that was achieved around parallelism in our various components. The target audience will be our reviewers (while reviewing the deliverables, and during the review), and the general public.

 I propose the following:
- For each component (PARI, Singular, LinBox, SageMath, ...), we prepare a Jupyter notebook showcasing some of the key achievements. Maybe things like running some calculations without and with parallelism, etc. (for LinBox, that would be the occasion to finally try it with cling :-) )
- We setup a JupyterHub server (like for the previous review) on UPSud's cloud with about 64 cores, and install the software and jupyter notebooks. We provide authentication credentials to our reviewers.
- For each component, we add on the deliverable github issue description links to the notebook (download + binder + JupyterHub server); the links will be available from the reports as well.
- We create a use-case page on opendreamkit.org about "running mathematical software on parallel hardware", with similar links and some overview text.

Tentative time line:
- By Friday, each component creates a stub notebook and publishes it on a public git repository, ideally making the repository binder ready. Or just decides on where it will be, without actually creating the stub. This way we can add links from the reports.
- By October 1st, have a good first version of the demo. This way reviewers can access it when they will review the deliverables. We can also ask for feedback to our advisory board, etc.
- By the review have the final version ready.

**Comment by nthiery** [comment]
cc: @KBelabas, @alex-konovalov, @stevelinton, @tthsqe12, @hivert, @videlec, @wbhart

**Comment by stevelinton** [comment]
@nthiery Any problem with GAP having a small number of noteboooks (two or three) rather than just 1. In particular I think we'll need one with an HPCGAP kernel and one without, demonstrating meataxe64 sensibly will need a kernel on a big, quietish, multicore machine which might be wasted on other things, etc.....

**Comment by nthiery** [comment]
> @nthiery Any problem with GAP having a small number of noteboooks
> (two or three) rather than just 1.

Sure thing, no problem.

**Comment by alex-konovalov** [comment]
For GAP notebooks, we will be accumulating them in https://github.com/OpenDreamKit/gap-demos/

**Comment by nthiery** [comment]
For information: I have deployed a machine on our local cloud for running WP5 demos. It has 32 cores (Intel Core Processor (SkyLake), 64Mb of RAM and 60GB of disk space.

I can grant you access if you send me your public ssh key:

   ssh debian@134.158.74.39

See it as a sandbox; install whatever debian package (debian is sudoer), and whatever additional software you need in a subdirectory for your demo (e.g. ~/Sage for all that is needed for a Sage demo). Make sure to document you installation procedure, as we might need to recreate the machine from scratch at some point.

**Comment by stevelinton** [comment]
@ntheiry Thanks. 
I assume you mean 64GB RAM and 60TB disk :-)

**Comment by nthiery** [comment]
:-) 64GB of ram indeed. But 60GB of disk. I could create a bigger one if needed though.
