### ISSUE TITLE
justification for Oxford in WP2 and WP4

### ISSUE THREAD

**Issue by dimpase** [OpenDreamKit/OpenDreamKit#299]
https://github.com/OpenDreamKit/OpenDreamKit/blob/9586b3cd399489f2ddb8e316d2971f2f92432993/ReportingPeriod3/TechnicalReport/FinancialOfficersComments.tex#L45

I propose to add the following:
----

_Regarding WP2_: it was clearly an oversight during the grant preparation, as dissimination and outreach was a task where more participants took part than originally planned. In particular Oxford was asked to present ODK tools and technologies at a number of international and UK-wide events,
and agreed to such requests, as it felt it is a very important part of the project. This resulted in contributing to \longtaskref{dissem}{dissemination} in WP2. As well, it participated in reviewing new technology, as in \longtaskref{dissem}{tech-review} in WP2.

_Regarding WP4_: as WP7 was cancelled, the focus of Oxford shifted to other WPs, where its expertise and skills were useful and beneficial, such as \longtaskref{UI}{sage-sphinx} and \longtaskref{UI}{vis3d} in WP4.

**Comment by dimpase** [comment]
@IzabelaFaguet - this is what I can add. I don't understand where in the grant docs such clarifications should go, though. Shoud Oxford be added as a participant in WP2 and WP4, somewhere?

**Comment by IzabelaFaguet** [comment]
Dear Dima, 

I have sent you the github link in my previous email:
https://github.com/OpenDreamKit/OpenDreamKit/blob/9586b3cd399489f2ddb8e316d2971f2f92432993/ReportingPeriod3/TechnicalReport/FinancialOfficersComments.tex#L45

but it's fine, thank you very much , I will add this to the technical report.

**Comment by dimpase** [comment]
OK, I suppose I misunderstood what to make it "properly described in Technical Report" means.

**Comment by IzabelaFaguet** [comment]
it's fine, many thanks Dima :)
