### ISSUE TITLE
Logo for OpenDreamKit

### ISSUE THREAD

**Issue by nthiery** [OpenDreamKit/OpenDreamKit#5]
We will need a logo by the time the project will start. We may want to go through a professional designer to finalize it. For now, if you have ideas, please put them below. Have fun!

Here are some preliminary sketches that were proposed by the participants:
- By Harald: <img src="https://raw.githubusercontent.com/OpenDreamKit/OpenDreamKit/master/media/logos/drafts/logo-harald.png" width="15%" align="middle">
- By Hans: <img src="https://raw.githubusercontent.com/OpenDreamKit/OpenDreamKit/master/media/logos/drafts/logo-hans.png" width="20%" align="middle">
- By Alex:  <img src="https://raw.githubusercontent.com/OpenDreamKit/OpenDreamKit/master/media/logos/drafts/logo-alex.jpg" width="20%" align="middle">
- By Matthias: <img src="https://cloud.githubusercontent.com/assets/335567/7798987/84170b92-02b5-11e5-9a02-8759eb14c8ee.png" width="24%" align="middle">
- By Nicolas:  <a href="https://github.com/OpenDreamKit/OpenDreamKit/blob/master/media/logos/drafts/nicolas/opendreamkit-simple.svg"><img src="https://raw.githubusercontent.com/OpenDreamKit/OpenDreamKit/master/media/logos/drafts/nicolas/opendreamkit-simple.png" width="20%" align="middle"></a>; previous one: <a href="https://github.com/OpenDreamKit/OpenDreamKit/blob/master/media/logos/drafts/nicolas/opendreamkit.svg"><img src="https://raw.githubusercontent.com/OpenDreamKit/OpenDreamKit/master/media/logos/drafts/nicolas/opendreamkit.png" width="20%" align="middle"></a>
- By Benoît:  <a href="https://github.com/OpenDreamKit/OpenDreamKit/blob/master/media/logos/drafts/logo-benoit.jpg"><img src="https://raw.githubusercontent.com/OpenDreamKit/OpenDreamKit/master/media/logos/drafts/logo-benoit.jpg" width="15%" align="middle"></a> (to be colored, ...)
- By Cameron Oelsen: <img src="https://cloud.githubusercontent.com/assets/6437976/11543197/22d9974c-98f0-11e5-8234-dcf6179f10b5.png" width="30%" align="middle">
- By Samuel: <img src="https://cloud.githubusercontent.com/assets/2786973/12569282/3b539278-c3c5-11e5-932d-f6bb981cceda.png" width="15%" align="middle"><img src="https://cloud.githubusercontent.com/assets/2786973/12569787/e7daff50-c3c9-11e5-8d32-ffc9f8061ff6.png" width="15%" align="middle">

At the end, Cameron's logo was elected. Congratuations!

**Comment by defeo** [comment]
Large logos, such as Alex' or Mathias', also need a smaller variant suitable for 16×16px² use (favicons and similar).

At the same time, we may also choose a standard font for all visual communication. At the moment, the website is using some default Google fonts coming with the theme.

**Comment by Carreau** [comment]
> Dear Mattias,
> 
> I really like your logo on the left.
> 
> The cloud seems a bit massive to me (taking away from the owl/moon
> combo. Have you thought about just leaving out the cloud or at least
> making it much lighter. I am not sure why there is a cloud at all, I
> assume as a metaphor for dream, but the moon already does that.

The logo felt a bit too light with no cloud, but I have to get a better font, 
maybe that would help. Anyway these are just ideas. 

> 
> In any case, the owl/moon/fullmoon combo alone would work very well as
> an abbreviate logo (e.g. for favicons).

I'm a bit sad because I don't see how to make that monochrome.  Which would
help in many contexts. Unless we head for a detailed version of the fool-moon
part which can be recognized.

> 
> Even though it dos not spell out "Math" at all, this is the proposal I
> like best so far.

You can probably have the rest of the font which is "custom" and have letter cutout in form of 
math symbols.


> Dear Matthias, thank you very much for the suggested logo! I very much enjoy
> the idea of the sun for "O" and the moon for "D", as well as an owl for
> (mathematical?) knowledge; and the left part by itself would make a nice
> pictogram indeed! As for the cloud, it may be relevant too because of the use
> of cloud technologies.
 


> May I suggest ti try some experiments with colours to make the logo looking less dark, please?

I'm no designer and I'm naturally bad at color. I can give a shot.

> 1) more natural (yellow or orange) colour of the sun

It suppose to be full moon, but we can try sun. 

> 2) come lighter colour of the cloud (light blue?). Perhaps not just a solid cloud, but only a contour of it? Also, why the letter "r" is not inside the cloud - may we fit all "reamKIT" inside it? It may be useful to have a version without cloud to compare.

> 3) The moon would look more natural if it would be white - but that would require a contrast background. How it will look like if the background is blue-ish, the sun is yellow, and the moon, cloud and letters are white, for example?

The rare times when I try to do design, I push toward having logo prototype
being monochrome, We had this issue when doing the Jupyter logo last year. One
you get a colored logo it's tough to get the black & white / white & black
version right. You will in particular always have website/users that want a FontAwesome
or any other variant of the logo.


> 4) One could also experiment with different owls, see e.g. https://www.iconfinder.com/search/?q=owl&maximum=512 for some inspirations - none of them seem suitable though since we want the moon and the owl to form the letter "D".

I tend to avoid looking reuse some of these for Licence issue. I prefer to get pictures, and hand draw with inkscape myself, then "path > simplify" to be certain not to have any problem with that.

> 
> Would you be able to find some time to try these ideas, or willing to share the source with others so they could try?

Time will be though, I made a PR with the source ( #6 ). I'm not a designer, and the moon is just the intersection of 2 circles. I'll see if I can get some things done.

**Comment by wbhart** [comment]
I don't like Harald's suggestion (sorry Harald). It reminds me too much of the communist hammer and sickle.

There is a really great video online about the design of flags. The principles were basically:

1) Use simple (perhaps even primary) colours and few of them
2) Keep the design simple and stylised
3) Each component of the design should have meaning
4) Don't write the name of the country/state/city on the flag (if you need text on your logo to explain what it is, it isn't a good logo)

So far the logo of Mathias comes the closest to being a good flag (logo).

**Comment by JohnCremona** [comment]
On 23 October 2015 at 16:08, wbhart <notifications@github.com> wrote:

> I don't like Harald's suggestion (sorry Harald). It reminds me too much of
> the communist hammer and sickle.
>
>
I agree.

Alex's has the nice feature that it explains the acronym but it it too dull
for a logo.  I would like to see it kept for use in certain places though.

I like the simplicity of Hans's.

John

There is a really great video online about the design of flags. The

**Comment by alex-konovalov** [comment]
Thanks - this is very weekend-like kind of a discussion :)
 
My top favourite is the logo by Mathias, and after returning to it after a while I like it now more. It may look nice as a laptop sticker. The left part (sun and moon) may be a favicon. My suggestion would be to spend some time on thinking how to improve it even more:
* the colour of the sun may be brighter, more orange-like (I think this was discussed somewhere, but I can't find where). I was told that this is a moon, but we already have one moon on the logo, so why do we need two ;-) ?
* The owl may look more like a "wise-owl", and less like a "spooky-owl". But of course the proportions (tall and slim) should be the same, so the owl on the moon will look like the letter "D"
* The cloud is relevant to cloud computing, but I would love to see a version with the blue colour, so the cloud will not look like there is a thunderstorm approaching. This would probably imply same colour for the moon and the letters.

Of course, it may happen that combining these three ideas will result in something looking worse than the initial version, but it might be worth to try. 

I like Hans' logo, but I am biased - seen it before too often. If someone could suggest to me what it symbolises and how that could be relevant to the project, I may start to rank it higher. 

I agree that my wordplay-based-logo is dull. Of course, it was quickly drawn to show the layout, but it's not clear whether playing with fonts and colours of the letters and the background may improve it much - I am not sure. By adding some graphic and changing the layout of letters - maybe, but I have no suggestions at the moment.

**Comment by Carreau** [comment]
The Jupyter project have a design student somewhere. I can try to see if I can borrow him for a few hours to work on that.

Do you want me to try ?

**Comment by wbhart** [comment]
"I like Hans' logo, but I am biased - seen it before too often. If someone could suggest to me what it symbolises and how that could be relevant to the project, I may start to rank it higher."

I agree. Nice logo, but I don't understand the deep symbolism.

**Comment by fangohr** [comment]
Hi, the whole logo creation process is available at https://github.com/OpenDreamKit/OpenDreamKit/blob/master/media/logos/drafts/source/logo-v2.ipynb

In short, the curve shown is a parametrised curve showing x(t) and y(t):
```
n = 2
t = np.linspace(0, 2*np.pi*n, 1000)

a = -1
b = 1
x = a* 0.5 * np.sin(2 * t) + b * np.cos(t/n)
y = a* 0.4 * np.cos(2 * t) + b * np.sin(t/n)
```
 If you look at it the right way, it looks like a human with  a head, two arms, two legs. The curve is also drawn with a bit of randomness, to give it a 'human touch' (xkcd style). So one could argue that this shows a piece of mathematics and connects with people (who use it, or dream about it). 

If we want to look for deep symbolism here, one could add that the logo is produced in the ipython notebook and should be producible and reproducible by the very tools that this project is (amongst other things) concerned about. 

Most of all, I didn't like the default Twitter egg.

**Comment by alex-konovalov** [comment]
@fangohr :+1: that's already a story! I like this kind of symbolism and reproducible logo, which then you may nicely show at various live software demos. Would be interesting to see how the ipython notebook may evolve with future versions of the software. You may try to calculate it in a more complicated way to use more tools involved in the project, e.g. approximation of pi with SageMath. In my eyes, this makes your logo a strong candidate too.

P.S. Actually, to me it always looked like a flower, I've never thought of it as of a human. Petals may be different components that fit together in a kit...

**Comment by kohlhase** [comment]
I am completely with @alex-konovalov first post here, I like the owl-cloud idea best, but would like to see some work on it. Especially sun color and owl shape. Even with the "story" behind the curve.

**Comment by lawrennd** [comment]
I like the idea of Hans's logo and the reproducibility. It could be tweaked a bit but it's a standout candidate for me.

Our centre rose for the GP summer school logo we designed was created using samples from Gaussian processes, so I like these types of ideas.

**Comment by nthiery** [comment]
@wbhart I took Harald's suggestion as a pun; in fact a pretty good one; I had a good laugh! Alas it's indeed too colloquial for our use case, and the pun pollutes the message with unrelated controversial stuff. Still there are very good ideas in there to reuse.

- I like having an explicit reference to the European flag. It's a good color scheme, simple and immediately recognizable. And it blends well with the "Dream" of OpenDreamKit. The stars work well for that too.

- I like the simplicity of Matthias logo. And the owl, moon, and cloud! They are nice references to science, dream, cloud-based architectures, ...

  The text is not very legible (varying background/foreground color, in particular in the middle of letters); this is probably easy to fix. The cloud is somewhat too prominent; one option would be to draw just its outline.

- I like the story behind Hans' logo (and an easy variant would be to use the European flag's color scheme). It's annoying though that the symbolism is not self explanatory.

- If we want to build on the idea of the owl, I like using specifically Athena's owl; this puts emphasis on the symbolism of ``knowledge, wisdom, perspicacity and erudition'' [1]; and it also refers nicely to ancient European tradition. I created mine starting from the picture of the greek 1 euro coin on Wikipedia, which is under Creative Common's license. It doesn't work yet so well at a small scale, but I'd hope that someone would know how to stylize it some more.

- About my own design: I tried to combine nice ideas from the other designs (and from a discussion with Luca), and tell the whole story about ODK: bringing together people in Europe to build our dream open toolbox for math/science from many components. I am of course biased, but at a large scale I am quite happy with the general layout.

  It's however quite crowded, which does not work at a small scale. Maybe someone can come up with a stylised version? E.g. the flag + open box + tiny reminders of some of the main items? And we could use the large version when we have more room, e.g. on the sidebar of the website.

  Also only an exterior eye can tell if the logo indeed conveys the intended story.

@Carreau: yes please proceed; having help from Jupyter's design student would be great.


[1] https://en.wikipedia.org/wiki/Owl_of_Athena

**Comment by fangohr** [comment]
I agree that a 'simple' logo is good (Harald and Hans version tick that box fully, Nicolas and Mathias slightly less but should be possible to simplify the design).

I also like to pick on the EU colour scheme (blue and yellow) and possibly the EU Flag in some form. 
I think this would work nicely as (i) the money comes from the EU, and (ii) there is no single new software or activity that is likely to use this logo widely beyond the duration of the project [as most things we improve and develop already exist and have their respective logos]. So we can make the mots of acknowledging the funder.

Regarding the idea of _reproducibility, maths and software_: whatever layout we end up with, we should be able to script creation of it: for the EU flag, we have 12 stars on a circle, each star having 5 corners -- there must be some set of symmetry group on S1 that can be used to create these shapes with code. We can certainly write some nested loops or recursive calls to produce this.

For more artistic shapes (such as owls, clouds, etc), we can hand draw them and/or process through inscape's 'path' feature as Matthias suggested above: this gives a vector representation of the tracing. In principle, this could be included as raw data into the script that draws the logo. Just a geeky showcase of putting code and data together in the same place and fully document how we got to the results. Not essential at all, of course.

Asking the design student for advice, new ideas and iterations on the existing material would be great.

**Comment by alex-konovalov** [comment]
Had only quickly scrolled through all morning comments. Just to say that it's not necessary to follow both EU colour and flag - and I am even not sure if this is permitted. This is an example how the circle of stars was added to the SCIEnce project logo: here you see its full and simple versions:
![www2full259](https://cloud.githubusercontent.com/assets/5751387/10710308/8313b2cc-7a4c-11e5-91a4-262c62c26c79.jpg)
![www2simple259](https://cloud.githubusercontent.com/assets/5751387/10710309/84ca5080-7a4c-11e5-9ef0-d423a71bb17c.gif)

**Comment by Carreau** [comment]
> yes please proceed; having help from Jupyter's design student would be great.

We might get some help from Cameron by end of week. Monday/Tuesday are full with fall classes and assignments also.

**Comment by nthiery** [comment]
On Mon, Oct 26, 2015 at 05:19:40PM -0700, Matthias Bussonnier wrote:
>    We might get some help from Cameron by end of week. Monday/Tuesday are
>    full with fall classes and assignments also.

Great, thanks!

No rush if it's more convenient for him a bit latter.

Cheers,
				Nicolas

**Comment by fangohr** [comment]
@alex-konovalov good point about not having to use colour scheme, and layout to make a connection with the EU.

Here is another thought: The OpenDreamKit acronym has exactly 12 letters -- that's the same number as there are stars in the EU flag. Does anybody feel inspired to draft a layout with those 12 letters being scattered like numbers on a clock as in the EU flag? Maybe this can combine the geometry of Harald's flag with the owl / cloud from Nicolas' and Matthias' designs (and not needing the ODK and OpenDreamKIT text to feature in the main logo; thus it will be simpler and more recognisable even if printed smaller?).

**Comment by nthiery** [comment]
On Tue, Oct 27, 2015 at 05:33:43AM -0700, Hans Fangohr wrote:
>    Here is another thought: The OpenDreamKit acronym has exactly 12
>    letters -- that's the same number as there are stars in the EU flag.
>    Does anybody feel inspired to draft a layout with those 12 letters
>    being scattered like numbers on a clock as in the EU flag? Maybe this
>    can combine the geometry of Harald's flag with the owl / cloud from
>    Nicolas' and Matthias' designs (and not needing the ODK and
>    OpenDreamKIT text to feature in the main logo; thus it will be simpler
>    and more recognisable even if printed smaller?).

And be done programmatically :-)

By the way, I forgot to mention that the sources of my logo and its
constituents are available on:

        https://github.com/OpenDreamKit/OpenDreamKit/tree/master/media/logos/drafts/nicolas

Not sure there is much of it that can be programmed.

**Comment by cameronoelsen** [comment]
I was just playing around after @Carreau pinged me on this, nothing set in stone just took another approach to the logo :)
![test1](https://cloud.githubusercontent.com/assets/6437976/10986866/ad0a5014-83e2-11e5-91ee-07c2e26189b5.png)
![test2](https://cloud.githubusercontent.com/assets/6437976/10986870/b459640e-83e2-11e5-9726-dcdcbef9ebb1.png)

I can take another crack at it if you guys want specific elements in the redesign!

**Comment by Carreau** [comment]
I like the style of this logo  !

**Comment by ellisonbg** [comment]
@cameronoelsen very nice! Specific comments:

* I really like the treatment of the word "Open"  - both the typeface and segmentation of each letter works really well.
* I think the "DREAM KIT" typeface should probably be closer to that of the "OPEN" - either the same or something that has a different contrast - maybe that doesn't have rounded corners at all.
* I really like the colors, but you might want to use more of the deeper blue that is in the "O".

**Comment by nthiery** [comment]
@cameronoelsen: very stylish indeed! With a professional touch to it :-)
Thanks!

- Dream and kit are more important keywords than open.
- Maybe the box would be more obviously a box by drawing the back edges where they are actually visible, rather by transparency through the sides.
- I indeed would be interested in another crack taking into account some of the many elements that have been discussed earlier in this issue.

Cheers,

**Comment by alex-konovalov** [comment]
Looks very modern! Thanks! 
* Is the box closed or open? To me, the top looks like the closed lid of the box. Could it be removed so instead of it one could see the bottom and the walls? (so we opened it and bubbles spread outside - they can't spread through the closed lid ;)

**Comment by nthiery** [comment]
@cameronoelsen: will you have a chance to give it a second crack, taking into acount the elements discussed in this issue? If so would you have a rough timeline?

**Comment by nthiery** [comment]
@alex-konovalov: thanks for rephrasing my thoughts into something easier to understand :-)

**Comment by bpilorget** [comment]
@cameronoelsen Hi! Have you been able to give the logo a second try?

**Comment by cameronoelsen** [comment]
@bpilorget @nthiery @alex-konovalov Thank you for the suggestions and sorry it took so long to get this second try out, lots of school work has been coming down on me. But, below I have posted the second try! Your guys' feedback was very helpful so if you have anything else that you'd like me to incorporate/try, feel free to follow up :) 
![dreamkit2](https://cloud.githubusercontent.com/assets/6437976/11543197/22d9974c-98f0-11e5-8234-dcf6179f10b5.png)

**Comment by alex-konovalov** [comment]
@cameronoelsen Thanks for your work, very good! I think this gives us an opportunity to naturally have three forms of logo: 
* all parts as above
* only the box and bubbles
* only OpenDreamKit text

Just two remarks from me so far:
* the back of the box seems to have different height from the front. Could you please lower the bottom of the box to fix this illusion?
* I liked the shape of the evaporating bubbles that we had in the 1st version, when there were some more of them:) Any particular reason that we have less of them now?

The 1st of these two suggestions is IMHO critical since it breaks the geometry, the 2nd is subjective.

**Comment by cameronoelsen** [comment]
@alex-konovalov Here is the revision on the height, think that fixes the illusion! As to the evaporating bubbles, the height of the bubbles was making the logo a little too high in height and I felt they were a little unnecessary
![revise2](https://cloud.githubusercontent.com/assets/6437976/11544229/a52773f4-98f5-11e5-9c71-eb052d58f497.png)

**Comment by alex-konovalov** [comment]
@cameronoelsen thanks, now the box looks perfect. I trust that this is the best position of the bubbles, but maybe just try to move the whole group of bubbles a bit down too, so it will overlap with the bottom of the box a little bit more (like it was before). Regarding the height of the bubbles, reducing it makes sense, I agree. Could it be worth to play with their diameter to make the top corner of the "foam" a bit more shaped - I think that's what I've liked in the initial version, how the proportions are changed while moving higher...

**Comment by cameronoelsen** [comment]
Here is the logo with the bubbles moved down, I will play with the arrangement and diameter in my next iteration :+1: 

![revise3](https://cloud.githubusercontent.com/assets/6437976/11545118/55d8ceec-98fa-11e5-92f5-380605d4f695.png)

**Comment by nthiery** [comment]
Thanks @cameronoelsen!

Do you see any way to integrate some of the visual elements that have been discussed earlier in this issue to connect this logo to our universe (math, europe, science, computation). I am thinking things like the owl, the cloud,

I would have very much liked to refer to the European Flag, but (apparently)[http://www.enpi-info.eu/enpi/userfiles/PB_Visibility%20EN.pdf) that is forbidden. See also article 29.4 of the Grant : « Moreover(beneficiaries) may not appropriate the EU emblem or any similar trademark or logo, either by registration or by any other means”.  What a pity. (thanks Benoît for the info!).

**Comment by nthiery** [comment]
According to the above rule, and also because it was too crowded anyway, I posted above a simplified version of my logo proposal.

**Comment by slel** [comment]
I sketched a simple logo for our "kit based on a dream based on openness",
symbolised by a letter K on top of a letter D on top of a letter O.
![odk-logo-slel](https://cloud.githubusercontent.com/assets/2786973/12569282/3b539278-c3c5-11e5-932d-f6bb981cceda.png)
The logo also evokes a ladybird, which can debug some plants, and fly here and there;
at large sizes we could add dots representing all the open components of OpenDreamKit.
I made it black and white as a prototype, but we could choose other colours.
I wrote it in LaTeX with TikZ, because I know that better than svg, but translating should be easy.
```
\documentclass{article}
\usepackage[paperwidth=26mm,paperheight=22.5mm,hmargin=0mm,vmargin=0.5mm,noheadfoot]{geometry}
\usepackage{tikz}
\setlength{\parindent}{0pt}
\begin{document}%
\pagestyle{empty}
\centerline{%
\begin{tikzpicture} [cap=round]
%\draw [very thin,red] (-0.7,-0.82) rectangle (1.86,1.32);
\path [clip] (-0.7,-0.82) rectangle (1.86,1.32);
\draw [very thick,rotate=30]
  (1,0) arc (0:360:0.8cm and 0.9cm) --cycle;
\draw [very thick,rotate=30]
  (-30:0.95cm and 1.0cm) -- ++(0:0.2cm) arc (-90:90:0.5cm) -- +(180:0.2cm);
\draw [very thick,rotate=-15]
  (1.58,1.12) -- ++(-0.5,0) -- +(0,0.5);
\end{tikzpicture}%
}%
\end{document}
```

**Comment by fangohr** [comment]
I like it (Ladybird).

**Comment by bpilorget** [comment]
Hey @cameronoelsen! The ODK consortium voted and your logo has been chosen.
Thanks a lot for your work. Could you send us an svg version so that we can include it on our website? That would be great, thanks.

**Comment by cameronoelsen** [comment]
@bpilorget Sounds awesome! What is the email address you would like me to send it to. You have full rights to use it wherever you'd like as well.

**Comment by bpilorget** [comment]
@cameronoelsen you can send it to benoit.pilorget@lri.fr
Thanks for the full right use! It is already on the ODK latex template document, and now we need to use it for our communication (website etc).

**Comment by cameronoelsen** [comment]
@bpilorget Where is the ODK Latex template document at? Just want to see the usage of it :)

**Comment by bpilorget** [comment]
https://github.com/OpenDreamKit/OpenDreamKit/blob/master/Proposal/LaTeX-proposal/deliverablereport.cls

**Comment by nthiery** [comment]
Time to make it official. A clear majority emerged in the poll, so I chose Cameron's bubbles logo.
Thank you all for stating your preferences!

And congratulations and thanks Cameron for the nice work!

**Comment by nthiery** [comment]
Before we close this issue, we may want to do some polishing. I guess the main thing would be to have
OpenDreamKit be capitalized the official way. In particular since we typically shorten it to ODK.
@cameronoelsen: would you be so kind as to volunteer to do this?
Then we probably also want to have several versions of it (with or without text, ...) in different formats (svg, pdf, maybe png)
Thanks!

**Comment by defeo** [comment]
@cameronoelsen, what software did you use to produce the SVG ? Inkscape is having trouble displaying the letters :(

**Comment by nthiery** [comment]
Ok, we haven't touched the logo in a year. We may as well consider it as final and close this issue.
