### ISSUE TITLE
T3.1: Portability

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#50]
- **WP3:** [Component Architecture](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP3)
- **Lead Institution:** Université de Versailles Saint-Quentin
- **Partners:** Université Paris-Sud
- **Work phases:** 0-36
- **Deliverables:** #66, #67

Description from page 41 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf):

In order to achieve maximum availability and accessibility, mathematical software must be developed and tested for a wide range of computer architectures and operating systems.  However most of open source development happens in POSIX environments (usually Linux or OS X), and almost exclusively on x86 platforms.  The vast majority of the developers of mathematical software does not have the expertise, nor the access to appropriate hardware and software, to insure appropriate testing and porting of components.  The best incarnation of this issue is the involved installation procedure for Sage on Windows, a major adoption barrier and common source of complaints by end-users.

In this task we will address the common needs of the community in terms of portability layers, building and testing infrastructure:
- Best practices adopted by the larger open source community will be investigated and leveraged, and existing expertise will be shared between the component developers.
- Windows being largely dominant in the desktop/laptop market, a specific focus will be placed on the port of Sage, and therefore all the components included in its distribution (in particular Pari/GP, GAP, Singular, Linbox) to this platform (#66).
- The deployment of a common infrastructure for multi-platform continuous integration (testing, building and distribution) will be addressed (#67).

**Reporting Period 1 update:** No deliverable is due for the evaluation period, but we are happy to report that Erik Bray of UPSud has made considerable progress on #66 by producing a [one-click Windows installer based on Docker](https://github.com/embray/sage-windows). Although the Docker based installer has proven itself a very good solution, our plan is still to deliver a Cygwin-based installer on month 24.

**Comment by jdemeyer** [comment]
I guess this could count: http://trac.sagemath.org/ticket/19701
