### ISSUE TITLE
T3.3: Modularisation and packaging

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#52]
- **WP3:** [Component Architecture](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP3)
- **Lead Institution:** Université de Versailles Saint-Quentin
- **Partners:** Université Paris-Sud, Logilab
- **Work phases:** 0-48
- **Deliverables:** D3.1 (#58), D3.6 (#65), D3.10 (#59)

In this task we will investigate best practices for composing, sharing and interfacing computational components and data for connected mathematical systems.

See page 42 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

Some tickets which fit well within this task, but which are not too closely related to any specific deliverable:
- [x] https://trac.sagemath.org/ticket/21501: Allow SAGE_LOCAL to be customized
- [ ] https://trac.sagemath.org/ticket/21480: Make sagelib setup.py self-contained and independent of SAGE_ROOT
- [ ] https://trac.sagemath.org/ticket/21508: Clean up src/setup.py to bring it to standard distutils behavior
- [ ] https://trac.sagemath.org/ticket/21535: Make src/setup.py independent of SAGE_CYTHONIZED
- [ ] https://trac.sagemath.org/ticket/21516: Fix sagelib sdist (src/setup.py sdist)
- [ ] https://trac.sagemath.org/ticket/21507: Make sagelib a PyPI package
- [ ] https://trac.sagemath.org/ticket/21469: Enable VPATH builds

**Reporting Period 1 update:** The first deliverable, D3.1: “Virtual images and containers” was delivered on time early in the project, producing the expected results.

A focused workshop in March 2016 (Sage Days 77, followed by Sage Days 85 in March 2017) also triggered much work and progress on the packaging side, both by OpenDreamKit participants and the community. Partly thanks to this, SAGE is now on its way to be available as a standard package in major distributions such as Debian and Anaconda. We stress the fact that this task is very much ahead of schedule: having SAGE in Debian was the goal set for #59, which is only due in month 48.

The workshops were also the occasion to clarify the modularization, packaging, and distribution needs and challenges. This has paved the way for #65, due in month 24.

**Comment by jdemeyer** [comment]
I think that [cysignals](https://github.com/sagemath/cysignals) fits very well in this task. It will also make CyPari packaging easier.
