### ISSUE TITLE
T3.4: Simulagora integration

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#53]
- **WP3:** [Component Architecture](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP3)
- **Lead Institution:** Logilab
- **Partners:** None
- **Work phases:** 0-48

See page 42 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by defeo** [comment]
@fcayre, I shall need a few words on this task for the periodic report (#227). One paragraph is enough. Thx.
