### ISSUE TITLE
T3.6: Document and modularise SageMathCloud 's codebase

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#55]
- **WP3:** [Component Architecture](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP3)
- **Lead Institution:** Université Paris-Sud
- **Partners:** Université de Versailles Saint-Quentin
- **Work phases:** 0-24
- **Deliverables:** D3.2 (#61), D3.4 (#63)
- **See also:** D3.5 (#64)

Original task description, as taken from page 42 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf):

From its inception in 2013, [SageMathCloud](http://cloud.sagemath.com) has quickly developed into a full featured VRE.  Because of the tight, partly closed source development cycles, SageMathCloud's codebase has quickly grown in size, with its documentation not always keeping the pace. As a result, it is at the moment very hard for a newcomer to set up a clone service of SageMathCloud just from its sources.

Now that SageMathCloud is [fully open source](https://twitter.com/sagemath/status/544939872294014977), we need to go through its codebase, understand and document it (D3.2, #61), isolate components that might be reused by other software (e.g.: Jupyter), and make it as portable as possible.

The ultimate goal of this task is to produce a personal version of SageMathCloud, to be shipped along with Sage, that a user can run on his own personal computer (D3.4, #63).

**Reporting Period 1 update:** The first deliverable of the task, #61, was delayed because of the slow recruitment process in UPSud. We were able to catch up on time for the first reporting period, the result being a [remarkable contribution](https://github.com/sagemathinc/smc/blob/master/src/doc/design_overview/overview.rst) by Erik Bray to the internal documentation of SageMathCloud.

On the other hand, #63, due in month 24, was achieved by the SageMathCloud developers before the start of OpenDreamKit. We are currently evaluating the most useful way to re-allocate the planned effort.

**Comment by defeo** [comment]
[Sage Days 70](http://wiki.sagemath.org/days70) had a focus on Sage/SMC/Jupyter. In particular, they where scheduled to work towards personal installs of SMC. Could someone who was there (@VivianePons, maybe?) report on progress, please?

I was able to track these two documents/discussions:

- https://cloud.sagemath.com/projects/ad9e7c84-b1de-4c64-b056-9a5e04d9107e/files/wstein/talks/smc-dev/smc-dev.pdf
- https://groups.google.com/forum/#!topic/sage-cloud/v2gaeDM0Vf8

Is there anything else?
