### ISSUE TITLE
T3.8: Python interface for OOMMF micromagnetic simulation library

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#57]
- **WP3:** [Component Architecture](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP3)
- **Lead Institution:** University of Southampton
- **Partners:** University of St Andrews
- **Work phases:** 7-13

This task provides a Python interface to the Object Oriented Micromagnetic Framework (OOMMF). This allows to access the capabilities of this package as one component of a virtual research environment, together with the existing ecosystem of scientific python libraries and tools.

The task has been completed and the resulting software is available online on [GitHub](https://github.com/joommf/oommfc) and through the Python packaging index under the name [oommfc](https://pypi.python.org/pypi/oommfc). The interface has been presented to users in the
micromagnetic community through our dissemination workshops (#30). This task is part of a
number of steps towards a virtual research environment for micromagnetic simulations (#38).

**Comment by fangohr** [comment]
Exploration of interface options is done in https://github.com/fangohr/oommf-python
