### ISSUE TITLE
D3.3: Support for the SCSCP interface protocol in the distribution of all relevant components ( Sage , GAP , etc.)

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#62]
- **WP3:** [Component Architecture](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP3)
- **Lead Institution:** University of St Andrews
- **Due:** 2016-08-31 (month 12)
- **Nature:** Other
- **Task:** T3.2 (#51)
- **Proposal:** [p.43](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)
- **Final report:** due 2017-02-28

**SCSCP** stands for the **Symbolic Computation Software Composability Protocol** - the remote procedure call framework by which different software components (primarily mathematical software systems) may offer computational services to a variety of possible clients using the [OpenMath](http://www.openmath.org/) encoding both for the data and protocol instructions (see the [**SCSCP specification**](http://www.symbolic-computing.org/scscp) for further details). 

SCSCP has been developed in the EU FP6 project 026133 [SCIEnce - Symbolic Computation Infrastructure for Europe](http://www.symbolic-computing.org/). In the duration of the project (2006-2011) and subsequent years, several native CAS implementations of SCSCP client and server, and also APIs for Java, C and C++ had appeared (see the complete list [here](http://www.symbolic-computing.org/)). However, there were no Python OpenMath SCSCP implementations (except a prototype quality client supporting only lists of integers) and that hindered further extension of the SCSCP framework.

In this deliverable, we have extended support for SCSCP to other relevant systems involved in the project. This builds foundation to D3.9 "Semantic-aware Sage interface to GAP" (#68) and other activities outlined in our paper ["Interoperability in the OpenDreamKit Project: The Math-in-the-Middle Approach"](https://dx.doi.org/10.1007/978-3-319-42547-4_9) (Intelligent Computer Mathematics. CICM 2016. Lecture Notes in Computer Science, vol 9791. Springer). More specifically, we have achieved the ability to communicate using SCSCP protocol to the following systems/languages:
- [x] Python (both versions 2 and 3): via pure pip-installable packages 
  - [x] openmath 
    - PyPI: https://pypi.python.org/pypi/openmath
    - GitHub: https://github.com/OpenMath/py-openmath
  - [x] scscp
    - PyPI: https://pypi.python.org/pypi/scscp
    - GitHub: https://github.com/OpenMath/py-scscp
- [x] SageMath: via Python packages listed above
- [x] LMFDB: via Python packages listed above
- [x] PARI: 
  - [x] support via D4.1 "Python/Cython bindings for PARI and its integration in Sage" (#83)
  - [ ] later via D4.10 "Second version of the PARI Python/Cython bindings" (#84)
- [x] GAP: via (updated versions of) GAP packages:
  - [x] OpenMath
    - Website: https://gap-packages.github.io/openmath/
    - GitHub: https://github.com/gap-packages/openmath
  - [x] SCSCP
    - Website: https://gap-packages.github.io/scscp/
    - GitHub: https://github.com/gap-packages/scscp 
- [x] Singular: via GAP and/or SageMath
- [x] MMT/MathHub: OpenMath and SCSCP client/server implementations in Scala

---
Remarks:
- Relevant tickets in Sage: https://trac.sagemath.org/ticket/19970 and http://trac.sagemath.org/ticket/19971
- In view of the new DFG-funded project "Symbolic Tools in Mathematics and Their Application'' which will develop the OSCAR system, based on Julia, it's desirable to implement OpenMath and SCSCP in Julia and later use Singular through it (see the blog post https://wbhart.blogspot.co.uk/2016/11/new-computer-algebra-system-oscar_20.html)

**Comment by defeo** [comment]
Some ideas for nice useful demonstrators that could come out of this work:

- Maple has an SCSCP interface (probably not activated by default on user machines, though). We could use SCSCP to improve the SageMath <-> Maple interface.
- Same goes for Mathematica.
- Databases that have an SCSCP interface could be queried live from the Sage command line. This applies to a couple of DBs maintained by @alex-konovalov, and to those that will get SCSCP support through MMT (think LMFDB, FindStat).

**Comment by defeo** [comment]
@alex-konovalov, what transport is relevant for SCSCP? Shall we implement the XML Processing Instructions over TCP protocol described in the [SCSCP specs, Sec. 5](http://www.symbolic-computing.org/science/images/7/74/SCSCP_1_3.pdf), or shall we wrap it in SOAP? Which protocol do SCSCP clients in the wild use?

@tkw1536, [zeep](http://docs.python-zeep.org/en/latest/) looks like a good library for SOAP. For raw TCP, I don't know what's the best option to support both Py2 and 3.

**Comment by tkw1536** [comment]
@defeo To my knowledge all SCSCP clients do it via raw sockets, so I am not sure if we should use something on top of that. Unfortunately I do not know any library for sockets that does both python 2 and 3 either.

**Comment by alex-konovalov** [comment]
@defeo:

> @alex-konovalov, what transport is relevant for SCSCP? Shall we implement the XML Processing Instructions over TCP protocol described in the [SCSCP specs, Sec. 5](http://www.symbolic-computing.org/science/images/7/74/SCSCP_1_3.pdf), 

yes, I suggest that you do exactly this so you do not need SOAP at all. This is the way how all existing implementations work by now.

**Comment by defeo** [comment]
Ok, thanks to both. I'll think a bit about more the best way to implement in python and come back to you, @tkw1536

**Comment by defeo** [comment]
Just talked to J. Gerhard of Maplesoft. Maple has an SCSCP client in the client version. The SCSCP server is only available in MapleNet. Bad luck for the Sage <-> Maple interface :/

**Comment by markuspf** [comment]
@defeo @tkw1536 what is the status of the SCSCP interfaces you are assigned to above?

Also, what about singular? Can @sebasguts maybe comment?

**Comment by tkw1536** [comment]
@markuspf Inside MMT / MathHub we have a working client implementation but it is not really integrated yet.

**Comment by defeo** [comment]
The Sage implementation is on hold as I am visiting UWaterloo ATM. Will resume the work in one week.

**Comment by markuspf** [comment]
Please note that this is due on 2016-08-31, so 5 weeks from now.

**Comment by defeo** [comment]
Yup, I know. No worries, 5 weeks is enough.

**Comment by bpilorget** [comment]
@defeo Is the report almost over?

**Comment by bpilorget** [comment]
The README gives info on how to write deliverables: https://github.com/OpenDreamKit/OpenDreamKit

**Comment by defeo** [comment]
Next week.

**Comment by nthiery** [comment]
Just in case that could be relevant: I stumbled on [mathdon](https://github.com/scoder/mathdom), a Content MathML DOM parser for Python. Incidentally mathdom is developped by  @scoder, core dev of Cython and of LXML, the later being a fast XML Dom parser written in Cython.
For the record, Content MathML is one of the official idioms for OpenMath, and is likely to be endorsed by the OpenMath society as the recommended OpenMath idiom.
cc: @kohlhase

**Comment by defeo** [comment]
Hello, work on this on the Sage side is essentially done: https://github.com/OpenMath/py-scscp. Of course, it may be helpful to add documentation and comment the code :innocent:

How's work on the other components? @tkw1536 said:

> Inside MMT / MathHub we have a working client implementation but it is not really integrated yet. 

anything new? Singular?

I can start writing the Sage part of the report, but maybe @alex-konovalov wants to setup the scaffold before that?

**Comment by kohlhase** [comment]
I am thrilled to hear about progress on the SageMath side. 
For me the next step would be to test the communication between the (three) systems that is possible now. I guess until the OpenMath Interface of Sage is further, it would be a good first step to send around integers between SageMath, MMT, and GAP as a hello world. 
After that we should really start working on getting the Use Case we talked about in Bremen running.

**Comment by defeo** [comment]
I agree. Unfortunately I was not able to obtain a copy of gap with a working scscp package (did not try very hard, but the linux arch package is currently broken). Any help appreciated.

**Comment by jgmbenoit** [comment]
have you tried to play with the [gap-scscp debian package](https://packages.qa.debian.org/g/gap-scscp.html) (on a testing)) box ?

**Comment by alex-konovalov** [comment]
@defeo You need GAP and also IO and OpenMath packages. Install GAP from the source distribution, and build packages, including the IO - then all should work.

**Comment by kohlhase** [comment]
@alex-konovalov don't you have a SCSCP-enabled GAP running on some machine somewhere, so that they can just connect up to that? After all, that is what SCSCP is meant to do.

**Comment by defeo** [comment]
> @alex-konovalov don't you have a SCSCP-enabled GAP running on some machine somewhere, so that they can just connect up to that? After all, that is what SCSCP is meant to do.

I am skeptic about hosting a public facing SCSCP server, especially a
testing one. Looks like a huge security risk.

I'd be happy enough with a docker container.

**Comment by alex-konovalov** [comment]
@defeo 

> I'd be happy enough with a docker container.

Then please see https://hub.docker.com/r/gapsystem/gap-docker/ - accidentally it has instructions how run SCSCP server. That is GAP 4.8.5 BTW.

**Comment by bpilorget** [comment]
# Deliverables update

@defeo @alex-konovalov  As you know , during the interim review in Bremen, reviewers gave advice to improve deliverables. UPSud tried to follow their advice by updating D5.1 #107
The main critic is that deliverables should be static document. Therefore we went through the #107 report to check if all links were still working and also if the information contained on the links was necessary for the understanding of the report.
As a result when it was necessary annexes were added to the #107 report.

Can you please do the same for this deliverable and add annexes when need be?

**Comment by nthiery** [comment]
Hi Alex!
There is not much time left for this deliverable. Do you mind starting to write the report, and making sure that anything that remains to be done is being actively worked on?

Thanks!

**Comment by kohlhase** [comment]
Yes, that would be very good. @tkw1536 (Tom) could you indicate whether you have time to help in the near near future?

**Comment by tkw1536** [comment]
@kohlhase I will do my best to help, but as I am currently in the process of finding a new apartment I am not sure how much time I will have. 
Concerning status inside MMT, we have a working client implementation, and the beginnings of a server version. 
Is it correct that for this deliverable we only need support for the protocol itself? If we also need to determine how to tightly integrate MMT functionality and SCSCP functionality, I will definitely need some more help.

**Comment by tkw1536** [comment]
@alex-konovalov Did you already start a report on this? Is there a plan on how to split it up between the different systems? @kohlhase has asked me to write the report from the KWARC side. 

@defeo What is the status of the SCSCP implementation in Sage / Python?

**Comment by defeo** [comment]
@tkw1536 `pip install scscp` :)
(or the equivalent command in Sage)

**Comment by kohlhase** [comment]
Wow, that sounds good. 
@tkw1536 I am looking forward to a report on how this works in an example.

**Comment by nthiery** [comment]
Dear M18 deliverable leaders,

Just a reminder that reports are due for mid-february, to buy us some time for proofreading, feedback, and final submission before February 28th. See our [README](https://github.com/OpenDreamKit/OpenDreamKit/#submitting-a-deliverable) for details on the process.

In practice, I'll be offline February 12-19, and the week right after will be pretty busy. Therefore, it would be helpful if a first draft could be available sometime this week, so that I can have a head start reviewing it.

Thanks in advance!

**Comment by alex-konovalov** [comment]
FYI, new releases of OpenMath and SCSCP packages for GAP, now hosted on GitHub and GitHub pages:
- https://gap-packages.github.io/openmath/
- https://gap-packages.github.io/scscp/

**Comment by kohlhase** [comment]
very good to know. What has changed? 
I see that the acknowledgements in the OpenMath manual do not include ODK (have not checked SCSCP) and that the issues URL in SCSCP manual has no link.

**Comment by alex-konovalov** [comment]
@kohlhase 
> very good to know. What has changed?

Both packages were not updated for a while (SCSCP since 2013, OpenMath since 2016) and apart from cosmetic updates of all URLs for the new hosting, there were various compatibility fixes to work with the new GAP release and GAP development version, cleaning up of obsolete variables, improving testing setup, etc. Also, `<OMOBJ>` tags now include `xmlns` and `version` attributes.
 
> I see that the acknowledgements in the OpenMath manual do not include ODK (have not checked SCSCP) 

Fixed for both packages, in manuals and their websites

> and that the issues URL in SCSCP manual has no link. 

Where? Please send me a link to the exact page.

**Comment by tkw1536** [comment]
@alex-konovalov @defeo 
For testing, I have just deployed an MMT SCSCP server instance on ash.eecs.jacobs-university.de on port 26133, (212.201.49.2, I haven't tested IPV6). It is minimal in the sense that it can currently only do ```scscp_transient_1 / addition``` and no other computations. I did some testing with the MMT client and that worked without problems. Concerning GAP and Python / Sage, I did test this a few weeks ago and it worked back then, but it would be good if you could verify this. 

/cc @Jazzpirate @kohlhase

**Comment by alex-konovalov** [comment]
@nthiery I've edited issue description (one item from @tkw1536 needs at least couple of words).

**Comment by nthiery** [comment]
Thanks; that's useful info!

Can you add an abstract of a couple paragraphs with some words of context (how this fits within ODK's aim, a brief description of what SCSCP is, what was achieved)? In case that feels too redundant with the introduction in report.tex, then maybe that introduction should become the abstract by being moved here?

**Comment by alex-konovalov** [comment]
@nthiery Updated issue description again - please check https://github.com/OpenDreamKit/OpenDreamKit/issues/62

**Comment by alex-konovalov** [comment]
P.S. @nthiery is there a tool to convert markdown to latex, or I have to do it manually?

**Comment by defeo** [comment]
@alex-konovalov, if you're trying to include the issue description, just use the command `\githubissuedescription`. Otherwise, I recommend pandoc.

**Comment by alex-konovalov** [comment]
@defeo githubissuedescription is there, but it does not convert updated github-issue-description.md to github-issue-description.tex

**Comment by nthiery** [comment]
On Fri, Feb 24, 2017 at 12:22:53PM -0800, Luca De Feo wrote:
>    [1]@alex-konovalov, if you're trying to include the issue description,
>    just use the command \githubissuedescription. Otherwise, I recommend
>    pandoc.

Indeed: fetching the markdown, converting it to latex & such is
handled automatically when doing:

        make WP3/D3.3/report.pdf

In other words: don't worry about it and focus on the issue
description on one hand, and the rest of report.tex on the other hand,
and I'll finalize the pdf production.

Cheers,
                                        Nicolas

**Comment by alex-konovalov** [comment]
@defeo indeed `pandoc -o github-issue-description.tex github-issue-description.md` works. Need manual tweaking to enter new lines when the final version will be out.

**Comment by alex-konovalov** [comment]
@nthiery: we will be waiting for an example from @tkw1536 on Tuesday morning.

**Comment by nthiery** [comment]
@tkw1536: Tuesday morning over :-)

**Comment by alex-konovalov** [comment]
Checklist:
- [ ] finish conclusions
- [ ] add authors
- [ ] update GitHub issue in the pdf
- [ ] hopefully one more example from @tkw1536

**Comment by nthiery** [comment]
> - [ ] @nthiery do you know how to put a space before `DELIVERABLE` in the 1st line of the title page ?
Fixed in fdc63d4fe465671133d7c3f660d01e7b3549d40b and pushed.

**Comment by tkw1536** [comment]
Sorry for not doing anythign this mornign, I was working on D4.3. I am working on the example right now.

**Comment by alex-konovalov** [comment]
@tkw1536 thanks. @nthiery as far as @stevelinton and me are concerned, after having a look at @tkw1536 new example this will be ready to go. The issue description above has been updated last time this morning, if you wish, you can convert it to latex in the meantime.

**Comment by tkw1536** [comment]
@alex-konovalov I have just pushed the second example. I also re-did the first example and it now has proper syntax highlighting.

**Comment by alex-konovalov** [comment]
@tkw1536 thanks, that looks good. @nthiery this is now ready to go, only needs your magic to fetch the latest issue description from GitHub.

**Comment by nthiery** [comment]
@alex-konovalov: could you fix the "Distrubuted" typo in READMEs/Parallel-GAP-SCSCP.pdf?
Then I'll submit.

**Comment by alex-konovalov** [comment]
@nthiery Fixed! Also updated issue description in both places to avoid overfull line with the long URL. Please submit!

**Comment by nthiery** [comment]
Submitted!
Thanks @defeo for your hard work on implementing SCSCP for Python, @alex-konovalov for leading this very thorough report and spearheading SCSCP, and everyone who helped.
Now let's see how this supports the wider adoption of SCSCP. Keep it up!
