### ISSUE TITLE
T4.4: Refactor Sage 's Sphinx documentation system

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#72]
- **WP4:** [User Interfaces](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP4)
- **Lead Institution:** Université Paris-Sud
- **Partners:** Simula Research Laboratory, Université de Versailles Saint-Quentin
- **Work phases:** 0-36
- **Deliverables:** [D4.13](https://github.com/OpenDreamKit/OpenDreamKit/issues/87)

See page 45 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf).

SAGE, like PYTHON and many other PYTHON based projects, uses the SPHINX documentation system. Due to particularly stringent needs, many layers of customisation and adaptations have accumulated over the years, in particular for proper scaling to the sheer size of the Sage documentation (13k pages just for the reference manual).

A deep refactorisation (D4.13 #87) is critically needed to get rid of multiple duplication, and foster sustainability by outsourcing back to SPHINX all generic aspects (parallel compilation, index generation, etc.).

**Comment by embray** [comment]
Sorry, I was just looking for the actual deliverable and thought this was it for a second.
