### ISSUE TITLE
T4.10: Common option system for various displays in Sage

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#78]
- **WP4:** [User Interfaces](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP4)
- **Lead Institution:** CNRS
- **Partners:** None
- **Work phases:** 0-24

Page 46 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf):

Given a mathematical object, it often has various possible representations on a computer. From raw text to LATEX, from simple 2d picture to a complicated 3d animation.

In this task, we will provide a uniform option system for displaying an object within SAGE (raw text, LATEX, tikz, matplotlib, jmol, tachyon, . . . ). We will implement some of the missing display and will benefit of the work done in T4.9 (#77).

**Comment by minrk** [comment]
@nthiery this task has no deliverables, but its work period is complete. Is there anything (or anyone) you can point me to to summarize for the D1.5 report?

**Comment by nthiery** [comment]
Oops, thanks, good catch, this went under my radar. Presumably there was work done by the community on this task, but I don't know if there was ODK contributions. Bordeaux is the lead here;
@videlec?

**Comment by videlec** [comment]
This task was mostly an initiative of Adrien Boussicault. Nothing has been done on this side.
