### ISSUE TITLE
D4.1: Python/Cython bindings for PARI and its integration in Sage

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#83]
- **WP4:** [User Interfaces](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP4)
- **Lead Institution:** CNRS
- **Due:** 2016-02-29 (month 6)
- **Nature:** Other
- **Task:** T4.12 (#80)
- **Proposal:** [p.47](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf).
- **[Final report](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP4/D4.1/report-final.pdf)**

The SageMath project includes many different subsystems, mostly written in C/C++. For each subsystem, Sage provides a low-level interface, usually written in Cython, through which the higher level components access the subsystem. The mathematical community would immensely benefit if the low-level interfaces were maintained outside of the Sage project, as separate Python packages. Indeed such decoupling would enable other Python projects to build upon those externalized interfaces, thus helping to improve them, and share maintenance effort.

Of all the subsystems, the case of PARI is of particular interest. Since its inception, Sage has had a low-level Cython interface to PARI, which has evolved over time in a highly coupled way. Around 2012, some Sage developers forked this interface into a project they called [CyPari](https://bitbucket.org/t3m/cypari/). One of the primary goals of the CyPari fork was to make independent Python bindings to PARI for use in a project called [Snappy](https://bitbucket.org/t3m/snappy). Over time, the CyPari fork has diverged from the Sage/PARI interface, and has gotten behind in terms of functionality.

The goal of this deliverable is to reconcile the fork by externalizing the Sage/PARI interface into an independent package, maintained by the Sage community, which may ultimately replace CyPari inside Snappy. The task happened to be more difficult than originally thought. The high level of coupling between Sage internals and the PARI interface makes it very delicate to pull the latter out of the SageMath codebase. The process of making this possible has led to a great amount of refactoring inside the Sage project, which is summarized in [Trac ticket 20238](http://trac.sagemath.org/ticket/20238).

Because of the high degree of coupling, and thanks to the availability of Snappy, this deliverable constitutes a highly valuable case study for future externalizations of low-level interfaces in SageMath. To bring this deliverable to completion, we have decided to split it in several steps:

- [x] Move SageMath's C signalling api to a separate Python/Cython package. The package is called [cysignals](https://github.com/sagemath/cysignals), and is [integrated to SageMath 7.1](http://trac.sagemath.org/ticket/20002).
- [x] Decouple SageMath's PARI interface from the coercion model. This has been achieved in [SageMath 7.4](http://trac.sagemath.org/ticket/21158).
- [x] Clean up the interface API, by removing unneeded object orientation and external dependencies. This has been achieved, and is [integrated to SageMath 7.5](http://trac.sagemath.org/ticket/20241).
- [ ] Move SageMath's PARI interface to a separate Python/Cython package depending on cysignals. The package is called [CyPari2](https://github.com/defeo/cypari2), and will replace the old PARI interface starting from [SageMath 7.6](http://trac.sagemath.org/ticket/20238).

The CyPari2 package is not ready to replace the [PyPi package CyPari](https://pypi.python.org/pypi/cypari/) yet. The most important missing functionality is Windows compatibility. A full replacement to CyPari is the goal of deliverable D4.10 #84.

**Comment by jdemeyer** [comment]
I think it would be good to better work out what this deliverable could mean.

The proposal says "standalone bindings for PARI in Python and integrate it in Sage". There are really two things here:
(A) Stand-alone bindings for PARI in Python.
(B) Bindings for PARI in Sage.

We already have (B) in Sage. And (A) is done by [CyPari](https://bitbucket.org/t3m/cypari), which is essentially a fork of the Sage bindings (using an older version of Sage and PARI).

However, I think that it is not possible to make a stand-alone library like CyPari function within Sage. The main obstacle I see is the coercion model: you just cannot plug arbitrary classes into the Sage coercion model, you need to inherit from `Element`. A second potential obstacle is the signal and error handling.

One thing we could do is to factor out all the common stuff between (A) and (B) into some template (C) (I say template because it wouldn't be a complete Python module) which can then be made into either (A) or (B).

**Comment by defeo** [comment]
Reading the description of T4.12, I really understand this deliverable asks for (B). I think this is more about the social issue (who maintains what), than the technical problem. The Pari devs (and me too) would be very happy if something like CyPari received more official support from the Sage community, rather than being an underground project.

As you point out, it is impossible to plug CyPari directly into Sage: we would need to wrap every CyPari class in an `Element` wrapper, which is essentially doing the same work twice.

So we probably have to go the (C) way, which feels like a lot of work for an uncertain benefit, but this is going to pave the way for other libraries (Pari was picked here simply because we have Pari devs in the project): if from this work we can come up with a standard way to write python wrappers so that they can be easily integrated into Sage's class system, then we win!

Now, this is just my vision on this task. I didn't write it (and I don't remember why, I didn't even sign UVSQ up for it), so it might not be in line with the vision of the WP and task leaders. So I'm waiting for input from the leaders, and I'm happy to work on it.

**Comment by jdemeyer** [comment]
> Reading the description of T4.12, I really understand this deliverable asks for (B).

I don't read it that way. In any case, (B) already exists. I think the proposal asks for (A) and then use (A) in Sage to implement (B).

Let me also add that I'm totally +1 to more cooperation between the Sage and PARI projects.

**Comment by defeo** [comment]
Sorry, I misread your comment. Of course s/(B)/(A)/ in my previous comment.

**Comment by nthiery** [comment]
Oups, T4.12, and its two deliverables D4.1 and D4.10 really belongs to WP 3 Component Architecture, not WP4 User Interfaces. We should have noticed this earlier! Oh well, no big deal, and it's to late to fix it anyway. But please reassign the issues to their appropriate leader (@videlec?).

**Comment by jdemeyer** [comment]
This might be a good project for the [PARI/GP workshop](http://pari.math.u-bordeaux.fr/Events/PARI2016/).

**Comment by defeo** [comment]
> This might be a good project for the PARI/GP workshop.

Good idea. I'll be there.

**Comment by videlec** [comment]
Sadly I will not be at the PARI/GP workshop (too far away from Santiago). A templating approach

**Comment by jdemeyer** [comment]
For reference, I forked `CyPari` at https://github.com/jdemeyer/cypari and @defeo asked the CyPari devs what they want to do with the CyPari project.

**Comment by embray** [comment]
I'm still catching up on this issue, but let me know if there's anything I can do to help on it, especially the packaging.

**Comment by jdemeyer** [comment]
Nothing has happened really... I have many ideas though.

My first priority now is to finish https://github.com/sagemath/cysignals which could be seen as dependency of CyPari, since PARI uses the signals framework.

**Comment by defeo** [comment]
> My first priority now is to finish https://github.com/sagemath/cysignals which could be seen as dependency of CyPari, since PARI uses the signals framework.

Quite some work here! I'd be happy to help, but I don't know how I can be useful.

Maybe I can start working on extracting the Sage-Pari interface without waiting for cysignals to be completed?

**Comment by jdemeyer** [comment]
> without waiting for cysignals to be completed?

cysignals itself is complete, the last piece is just integrating it in Sage.

**Comment by defeo** [comment]
I've pushed a attempt at rebooting cypari here: https://github.com/defeo/cypari. Very dirty and not yet functional. @jdemeyer, let's try and deliver this thing by the end of next week.

**Comment by bpilorget** [comment]
Hi there @defeo & @jdemeyer
Do you think you can deliver this soon? FYI @embray says he can help you with this if needed

**Comment by defeo** [comment]
@jdemeyer is coming to Orsay on March 14-18. We plan to deliver that week (I know, that's a 2-3 weeks delay, sorry).

**Comment by bpilorget** [comment]
You can track the progress here: http://trac.sagemath.org/ticket/20238

**Comment by jdemeyer** [comment]
There are currently two tickets in need of review: http://trac.sagemath.org/ticket/20219 and http://trac.sagemath.org/ticket/20226

**Comment by jdemeyer** [comment]
I managed step 2 of our plan: uncouple PARI from the coercion model. The actual uncoupling was almost trivial, but the changes to the coercion model are not.

I plan to wait until [#21158](https://trac.sagemath.org/ticket/21158) is closed before continuing to work on CyPari. It's not a good idea to work on top of too many unreviewed tickets.

**Comment by defeo** [comment]
Perfect timing, I was right back on this too! I'll review it tomorrow.

**Comment by bpilorget** [comment]
@defeo @jdemeyer @nthiery Hi! How are things going?

**Comment by defeo** [comment]
Working on this. @jdemeyer will you be there at SD75? That'd be a good time to finalize.

**Comment by videlec** [comment]
I am looking at [#20686](https://trac.sagemath.org/ticket/20686).

**Comment by jdemeyer** [comment]
> will you be there at SD75?

No, I cannot. I could come to Paris in the beginning of september.

**Comment by defeo** [comment]
> No, I cannot. I could come to Paris in the beginning of september.

All right. I guess it can wait that little. I'll keep working on this at SD75 anyway.

**Comment by jdemeyer** [comment]
@videlec What about https://trac.sagemath.org/ticket/21005? We still need a reviewer for that.

**Comment by bpilorget** [comment]
# Deliverables update
@jdemeyer @defeo  As you know , during the interim review in Bremen, reviewers gave advice to improve deliverables. UPSud tried to follow their advice by updating D5.1 #107
The main critic is that deliverables should be static document. Therefore we went through the #107 report to check if all links were still working and also if the information contained on the links was necessary for the understanding of the report.
As a result when it was necessary annexes were added to the #107 report.

Can you please do the same for this deliverable and add annexes when need be?

**Comment by nthiery** [comment]
Hi Luca, Jeroen!
I am finally in the process of uploading the reports. Is the report for this deliverable final?
Do we want to check the last item on the  above TODO list or comment further on it?

**Comment by defeo** [comment]
Uh, there's still a couple of tickets open from before Xmas. I don't expect the report to change, but we both would feel more comfortable if those tickets were closed, before saying this deliv is complete. It's not much work, however I do not have time for this before 1 or 2 weeks.

**Comment by nthiery** [comment]
Ok, this sounds fair enough. Thanks for the update!

**Comment by jdemeyer** [comment]
There are a few things to be done but I think that the hardest part has been done. At this point it's just a matter of priorities. The last months I worked more on building & packaging Sage (WP3) instead of this.

**Comment by nthiery** [comment]
Hi Jeroen!

Good question about priorities. Building&packaging progress is indeed great long term investment; thanks for all your work in this direction!

The hard deadline of Month 18 (February 28th) is coming very soon though, and there are several deliverables PSud/Versailles/Gent are involved in that remain to be finalized (this one, SCSCP #62, Jupyter kernels #93, Sage/Jupyter convergence #94 ) or more (SMC!!! #61). So unless there are tight deadlines on the B&P side (such as the recent debian release), it would be safe to focus some energy on the above deliverables.

We will brainstorm about that later today with Luca; let us know if you are available, and we can do a videoconference with you.

**Comment by jdemeyer** [comment]
> We will brainstorm about that later today with Luca; let us know if you are available, and we can do a videoconference with you.

I'm only reading this now. You still mean today or should we do it another day? In any case, I guess we will meet in Edinburgh (I will come tuesday evening).

**Comment by nthiery** [comment]
On Thu, Jan 05, 2017 at 11:54:15AM -0800, jdemeyer wrote:
> I'm only reading this now.

No worry, it was a last minute notice, just in case you'd be
around. Thanks for getting back to us.

We mostly discussed what to do with the SMC deliverable (see this
morning's comment on #55). Erik has volunteered to put some work
there. In case you'd be interested too (e.g. around an SMC deployement
in Gent?)  please comment there.

We also discussed the Pari deliverable. Luca will have a sprint on
next week at the Pari days. He could probably use a bit of help here
and there (review, ...).

> In any case, I guess we will meet in Edinburgh (I will come tuesday
> evening).

Ah, great! Good occasion to finalize the Jupyter deliverables.

Cheers,

**Comment by jdemeyer** [comment]
> Luca will have a sprint on next week at the Pari days.

I will be there too.

**Comment by nthiery** [comment]
Dear M6 deliverable leaders,

Just a reminder that reports are due for mid-february, to buy us some time for proofreading, feedback, and final submission before February 28th. See our [README](https://github.com/OpenDreamKit/OpenDreamKit/#submitting-a-deliverable) for details on the process.

In practice, I'll be offline February 12-19, and the week right after will be pretty busy. Therefore, it would be helpful if a first draft could be available sometime this week, so that I can have a head start reviewing it.

Thanks in advance!

**Comment by defeo** [comment]
@nthiery, I've updated the report. I think it is ready for submission, maybe @jdemeyer wants to comment on it.

**Comment by nthiery** [comment]
On Wed, Feb 08, 2017 at 10:33:50AM -0800, Luca De Feo wrote:
>    [1]@nthiery, I've updated the report. I think it is ready for
>    submission, maybe [2]@jdemeyer wants to comment on it.

Great, thanks! I'll submit tomorrow.

Suggestions:

- Edit the github description to state, as in the text, that the last
  item (CyPari replacement) is planned as part of D4.10.

- Include as appendix the ticket description for #20238 (e.g by
  printing the ticket to pdf and \includepdf its first pages; see
  WP2/D2.1/report.tex for an example).

**Comment by defeo** [comment]
Done

**Comment by nthiery** [comment]
Thanks Luca! I submitted the report to the EU portal after tiny format edits.

Thanks everyone for all the hard work on this challenging deliverable!

**Comment by bpilorget** [comment]
Yay! Congratulations!
