### ISSUE TITLE
D4.11: Notebook Import into MathHub.info (interactive display)

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#85]
- **WP4:** [User Interfaces](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP4)
- **Lead Institution:** FAU Erlangen-Nürnberg
- **Due:** 2018-08-31 (month 36)
- **Nature:** Demonstrator
- **Task:** T4.6 (#74)
- **Proposal:** [p. 47](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)
- **[Final report](https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP4/D4.11/report-final.pdf)** ([sources](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP4/D4.11/))

OpenDreamKit supplies a vision for integrating disparate and incompatible systems into a VRE. This deliverable considers three of these systems: the Jupyter user interface system, the MathHub document hosting system, and the MMT knowledge representation system (which already serves as the center of Math-in-the-Middle infrastructure developed in OpenDreamKit, see D6.5 (#139).

Concretely, we report two practical steps towards this goal. Firstly, we have designed and implemented a Jupyter kernel for MMT. Secondly, we show how to combine the advantages of Jupyter Notebooks and MathHub documents. We evaluate the integration in two case studies. The first one serves as a stepping stone towards the OpenDreamKit VRE: MitM-based computation via MMT using a Jupyter Notebook that is maintained by MathHub. The second one applies our results to a concrete problem outside of mathematics: a knowledge-based specification dialog for modeling and simulation.

Thus, this report answers the need for interface integration of documents and REPL interfaces identified in Deliverable Report [D4.2](https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP4/D4.2/report-final.pdf) and, implements and integrates the designs and prototypes from D4.3 (#92) and D4.9 (#97) into a coherent prototype.

**Comment by bpilorget** [comment]
@kohlhase This deliverable is officially due for 31/08/2017. Can you please report on the progress you have achieved?
Thanks in advance

**Comment by bpilorget** [comment]
D4.11 moved from M24 to M36 to incorporate results from workshop on live structured documents

**Comment by nthiery** [comment]
Hi Michael @kohlhase,
Thanks for the draft of report! I forgot to mention that I went through it mid-July, made some minor changes and added some ednotes.
Let me know when you have a version ready for final review. The sooner, the better :-)

**Comment by kohlhase** [comment]
> @nthiery @kohlhase I didn't know if we should use the original due date (M24) or the modified due date (M36) on the front page of the deliverable.
> I used the original for now.

I think we should use the modified one (and I have changed it), this is the currently in effect "contract".

**Comment by kohlhase** [comment]
I have re-read and tweaked/extended the report in various places. Up to a JEdit screenshot I need from @Jazzpirate  (ETA 11:00) this is ready to go. 
@nthiery what do we do next?

**Comment by kohlhase** [comment]
OK, the screenshot is in. We can submit.

**Comment by nthiery** [comment]
>    [1]@nthiery You had added an ednote "move this to the github
>    description" to the abstract.
>    I didn't understand what you meant and assumed it's safe to ignore.

Well, safe, yeah, I can do it myself like I did for many other
reports. But if you could read the README, that would save me time.
Thanks in advance,

https://github.com/OpenDreamKit/OpenDreamKit/blob/master/README.md#submitting-a-deliverable

**Comment by florian-rabe** [comment]
@nthiery I've added a description of the deliverable to the issue. (Sorry for not realizing what your ednote meant.)

**Comment by nthiery** [comment]
Thanks for finalizing this report; I should be able to squeeze the
submission later today.

**Comment by kohlhase** [comment]
Thanks a lot.

**Comment by nthiery** [comment]
>    I think we should use the modified one (and I have changed it), this is
>    the currently in effect "contract".

It should indeed be the date given in the amended contract, so M36.

**Comment by nthiery** [comment]
Submitted!

**Comment by kohlhase** [comment]
Thanks a lot for the support.

**Comment by IzabelaFaguet** [comment]
Accepted by the EU on December 5th.
