### ISSUE TITLE
D4.14: Computational Fluid dynamics visualisation in web notebook

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#88]
- **WP4:** [User Interfaces](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP4)
- **Lead Institution:** Simula Research Laboratory
- **Due:** 2018-08-31 (month 36)
- **Nature:** Other

See page 48 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by bpilorget** [comment]
#88 was merged in #86 after the 3rd amendment to the contract
