### ISSUE TITLE
D4.16: Exploratory support for semantic-aware interactive widgets providing views on objects represented and or in databases

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#90]
- **WP4:** [User Interfaces](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP4)
- **Lead Institution:** Université Paris-Sud
- **Due:** 2018-08-31 (month 36)
- **Nature:** Demonstrator
- **Task:** T4.5 (#73)
- **Proposal**: [p. 47](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)
- **[Final report](https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP4/D4.16/report-final.pdf)** ([sources](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP4/D4.16/))

The [Jupyter Notebook](https://jupyter.org) is a web application that enables the creation and sharing of executable documents containing live code, equations, visualizations, and explanatory text. Key features include Jupyter widgets which enable interactive visualization and can be composed to create full-featured interactive applications.

In this report, we explore the potential of Jupyter widgets for (pure) mathematics. The unique challenge comes from the huge variety of mathematical objects that the user may want to visualize and interact with, and the variety of graphical representations.

Over the course of four PM's, we pursued two main directions: the interactive visualization and edition of combinatorial objects ([sage-combinat-widgets](https://github.com/sagemath/sage-combinat-widgets)) and the interactive exploration of Sage features based on a display of mathematical objects enriched with contextual semantic information ([sage-combinat-explorer](https://github.com/sagemath/sage-explorer)).

**Comment by minrk** [comment]
@nthiery what's the current status of the report on this deliverable?

**Comment by nthiery** [comment]
Hi @minrk,
Thanks for querying; Odile (@zerline) has been working hard on this deliverable, and we have a good first prototype working and deployed on binder: https://github.com/sagemath/sage-explorer

We will meet on Monday to start writing the report and plan what can be achieved for the deliverable itself in the coming weeks, and how we want to advertise it and have it beta-tested.

**Comment by nthiery** [comment]
Hi @markuspf!
In the report for this deliverable (still a draft), we mention Francy in the introduction, and later we have a brief section about it. Could you please have a look at it and check that it's correct? Suggestions welcome too. And of course we should discuss further about it at some point!

https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP4/D4.16/report.tex#L290

**Comment by nthiery** [comment]
@zerline: I merged the D4.16 branch back into master.

**Comment by nthiery** [comment]
Thank you @zerline for all the material for the report and summary! Some more information, a bit of polishing and Voilà.
Submitted :-)

**Comment by IzabelaFaguet** [comment]
Accepted by the EU on December 5th.
