### ISSUE TITLE
D4.2: Active/Structured Documents Requirements and existing Solutions

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#91]
- **WP4:** [User Interfaces](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP4)
- **Lead Institution:** Jacobs University Bremen
- **Due:** 2016-02-29 (month 6)
- **Nature:** Report
- **Task:** T4.6 (#74)
- **Proposal:** [p. 47](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)
- **[Final report](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP4/D4.2/report-final.pdf)**

Related projects:
- MathBookXML: http://mathbook.pugetsound.edu/
- Jupyter notebook exporter for Sphinx: https://github.com/sphinx-doc/sphinx/pull/2117
- Jupyter javascript plugin for static sites: https://github.com/oreillymedia/thebe
  See also: https://www.oreilly.com/ideas/jupyter-at-oreilly
- ReST to IPython Notebook converter through pandoc and markdown: https://github.com/nthiery/rst-to-ipynb/

cc: @fcayre, @nthiery, @fangohr, @marcinofulus, @rbeezer

**Comment by kohlhase** [comment]
We have asked for an extension for this deliverable and as far as I understand we have until the review meeting in June. I have hired a student who will prepare the survey part of this and I will get this done. 
We are still finding out where to best develop it. 

I am leaning towards a public repository on http://gl.kwarc.info (and give anyone who wants write access) and then move it to the WP4 repos when it is done enough from my PoV.

**Comment by kohlhase** [comment]
I just went ahead and made https://gl.kwarc.info/ODK/D4.2.git and we are going to run with that for a while.

**Comment by minrk** [comment]
Great, thanks!

**Comment by AlexMaiereanu** [comment]
Hello!

I am the student in charge of the survey part. Now I documenting about this issue and right after I will begin to post any material that I make.

**Comment by nthiery** [comment]
On Wed, Mar 16, 2016 at 03:36:07AM -0700, AlexMaiereanu wrote:
>    I am the student in charge of the survey part. Now I documenting about
>    this issue and right after I will begin to post any material that I
>    make.

Welcome on board, and thanks in advance for the hard work!

				Nicolas

**Comment by kohlhase** [comment]
am very sorry to be late on this. I have just committed a draft to ```WP4/D4.2```. I have promised Nicolas to submit to him tomorrow night. Therefore I would be interested in quick feedback on this. Sections 1,2,3 are just rehashing of known stuff (Active Documents and Jupyter). Section 4. is a proposal for a synthesis. I would really like your feedback on this. 
In my presentation  I would concentrate on the synthesis proposal. 
@nthiery is the level of coverage OK in this way? 
@nthiery,@minrk we may want to discuss this proposal in more detail in a joint session between the WP4 and WP6 workshops in Bremen (are you coming?).

**Comment by minrk** [comment]
Great, I'll have a look. I will be in Bremen and happy to discuss this
while there.

**Comment by kohlhase** [comment]
I have committed this deliverable report to this repository and notified Nicolas and Benoit that it is ready.

**Comment by kohlhase** [comment]
@nthiery, why did you reopen?

**Comment by bryongloden** [comment]
@nthiery, yup

**Comment by nthiery** [comment]
Report submitted to EU

**Comment by bpilorget** [comment]
# Deliverable updates
@kohlhase As you know , during the interim review in Bremen, reviewers gave advice to improve deliverables. UPSud tried to follow their advice by updating D5.1 #107
The main critic is that deliverables should be static document. Therefore we went through the #107 report to check if all links were still working and also if the information contained on the links was necessary for the understanding of the report.
As a result when it was necessary annexes were added to the #107 report.

Can you please do the same for this deliverable and add annexes when need be?

**Comment by nthiery** [comment]
Hi @kohlhase,
I am finally in the process of resubmitting the deliverables. I have fixed two typos in the report. There is one undefined reference (fig:web, in ActiveDocumentsOverview.tex). Could you double check on this, and use the occasion to double check the external links as mentionned above?
Thanks!

**Comment by kohlhase** [comment]
I have fixed the references (multiple and undefined). 

I am a bit confused, I saw that the report did not have a githubissuedescription so I added that in the process I looked at D4.1 D5.1 and they only consist of the issue description (no content) is that intentional?

**Comment by nthiery** [comment]
On Mon, Jan 09, 2017 at 04:45:50AM -0800, Michael Kohlhase wrote:
>    I have fixed the references (multiple and undefined).
>    I am a bit confused, I saw that the report did not have a
>    githubissuedescription so I added that

Thanks!

I'll merge the abstract in the github issue description and submit on
the EU portal.

>    in the process I looked at D4.1 D5.1 and they only consist of the
>    issue description (no content) is that intentional?

I am confused too: D4.1 has a good page of text in addition to the one
page of overview in the issue description:
https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP4/D4.1/report.tex

For D5.1, it was deemed sufficient to give an overview of the goal and
achievements in the issue description (about 1/2 page), and to defer
to the appendices (documentation, ... ~20 pages).

Cheers,
		Nicolas

**Comment by nthiery** [comment]
Resubmitted on the EU portal.
