### ISSUE TITLE
D4.3: Distributed, Collaborative, Versioned Editing of Active Documents in MathHub.info

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#92]
- **WP4:** [User Interfaces](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP4)
- **Lead Institution:** Friedrich-Alexander Universität Erlangen/Nürnberg (FAU), formerly Jacobs Universität Bremen
- **Due:** 2017-02-28 (Month 18)
- **Nature:** Demonstrator
- **Task:** T4.7 (#75): Active Documents Portal, T4.8 (#76): Visualisation system for 3D data in web-notebook
- **Proposal:** [p. 48](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)
- [**Final report**](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP4/D4.3/report-final.pdf)

One of the most prominent features of a virtual research environment (VRE) is a unified user interface. The OpenDreamKit approach is to create a mathematical VRE by integrating various pre-existing mathematical software systems. There are two approaches that can serve as a basis for the OpenDreamKit UI: ```computational notebooks``` and ```active documents```. The former allows for mathematical text around the computation cells of a real-eval-print loop of a mathematical software system and the latter makes semantically annotated documents active.

MathHub is a portal for active mathematical documents ranging from formal libraries of theorem provers to informal – but rigorous – mathematical documents lightly marked up by preserving LaTeX markup. In the OpenDreamKit project MathHub acts as:

* A portal and management system for theory-graph structured active documents, i.e. documents that use the semantic structure of the document and the knowledge context it links to to render semantic services embedded in the document – it becomes active, i.e. interactive, reactive - see D4.2 (#91).

* The repository for the Math-in-the-Middle (MitM) ontology, see D6.2 (#136). This ontology is used as a basis for interoperability of the mathematical software systems that make up the OpenDreamKit VRE toolkit, which is a crucial concern for work package [WP6](https://github.com/OpenDreamKit//OpenDreamKit/tree/master/WP6).

As the authoring, maintenance, and curation of theory-structured mathematical ontologies and the transfer of mathematical knowledge via active documents are an important part of the OpenDreamKit VRE toolkit, the editing facilities in MathHub play a great role for the project.

This report discusses the main design decisions of the editing facilities in MathHub; they can be assessed at http://mathhub.info.

**Comment by kohlhase** [comment]
We have done work on this, but that has been delayed by Constantin Jucovschi leaving. We could write up what we have, but I would like to see more work on this before we deliver.

**Comment by minrk** [comment]
@kohlhase do you still want more time on this one? If so, we should probably do whatever we need to do formally for delaying a deliverable (@nthiery). Is there any help any of us can provide?

**Comment by bpilorget** [comment]
@minrk We are working on the delay. It should not be a problem but we wait for the formal notice to change the due date here

**Comment by kohlhase** [comment]
> @kohlhase do you still want more time on this one?
@florian-rabe 

Work on this deliverable (D4.3) has been delayed due to the somewhat unexpected uptake of the Math-in-the-Middle (MitM) architecture, which prompted us to re-allocate JacU resources to WP6 in the first year. We proppose to move the submission of this deliverable to month 18 (in time for the first project review, so that it can be presented there; after all it is a demonstrator). In this way, we can also include the MitM ontologies into the editing/display facilities of MathHub.info

@bpilorget is that the explanation you need?

**Comment by bpilorget** [comment]
@kohlhase Yes perfect, thank you.

**Comment by bpilorget** [comment]
@minrk (WP leader) and @kohlhase (lead beneficiary)
This deliverable is due for February 2017

**Comment by minrk** [comment]
@kohlhase what needs to be done to finish this deliverable for February?

**Comment by kohlhase** [comment]
I will write up something; we already have done the work (mostly) and I can copy/paste a report.

**Comment by nthiery** [comment]
Dear M18 deliverable leaders,

Just a reminder that reports are due for mid-february, to buy us some time for proofreading, feedback, and final submission before February 28th. See our [README](https://github.com/OpenDreamKit/OpenDreamKit/#submitting-a-deliverable) for details on the process.

In practice, I'll be offline February 12-19, and the week right after will be pretty busy. Therefore, it would be helpful if a first draft could be available sometime this week, so that I can have a head start reviewing it.

Thanks in advance!

**Comment by minrk** [comment]
@kohlhase is there anything I can do to facilitate getting a draft of this report in soon?

**Comment by kohlhase** [comment]
no, not really. But I will have something at the end of the weekend.

**Comment by kohlhase** [comment]
OK, I have completed the report document (it grew to 15 pages, since we had to describe the setup). This can be submitted from my PoV. It would be great, if someone could have a look at it soon, since I will be traveling from Saturday morning and probably offline until March 14. 
If there is anything pressing to do, you can contact @tkw1536 or @Jazzpirate But I think that should be un-necessary.

**Comment by minrk** [comment]
Thanks!

**Comment by nthiery** [comment]
Hi!
I have just been through the current report. Altogether it looks good. I just pushed a couple typo fixes and minor todo's. Here are some others todo's

- Write an abstract to be put on the github issue description. The current introduction could basically serve as one. The only thing is to decide how to handle the one citation there; the references to other deliverables are not a problem. In the abstract, i

- Figure 1: the layout could be optimized (more spacing between the nodes, ...) to improve readability.

- The text needs line-by-line proofreading

- The text could state early on, plausibly in the abstract, that the collaborative editing workflow is similar in nature to that of common website authoring systems (e.g. GitHub / gitlab pages, ...) which are based on distributed version controlled sources combined with a static website generator. One can then argue that this type of workflow is being massively used by a wide variety of users around the world and has proven to be practical, robust, and sound. Once this has been stated, one can highlight the specific challenges. E.g. the variety of documents, from informal to formal, which requires variants on the workflow, solid error reporting, ...

Cheers,

**Comment by bpilorget** [comment]
@nthiery Will do the English line by line proofreading by tomorrow

**Comment by nthiery** [comment]
@florian-rabe, @kohlhase: anybody available from Kwark to finalize the little points mentionned above?
@bpilorget: how far are you with the proofreading?

Thanks,

**Comment by tkw1536** [comment]
@kohlhase is currently on vacation (~ until end of March), I will have a look at the points above.

**Comment by tkw1536** [comment]
@nthiery I have just committed and pushed: 
* Added an abstract in the github description: also pulled that into the report itself
* I updated Figure 1 as much as I could, but I am not exactly a tikz expert. There is more spacing now, but some of the texts don't quite want to center

I will do some proof reading later on (also counting on @Jazzpirate s help for that). 
I will also try to incorporate your last point, but with the amount of time left and all the other things that I need to finish until tomorrow, I am not sure if I will be able to commit anything

**Comment by nthiery** [comment]
Thanks @tkw1536! Do whatever you can for the last point, and let me know when you have run out of time and we should just consider this as done.

**Comment by bpilorget** [comment]
@nthiery @tkw1536 Corrected minor typos after line by line proofreading

Most of "TODOS" are gone in the latest version. But I noticed two flaws in "editing.tex":

-  paragraphe from lines 155 to 160 don't seem to make much sense (a lot of hyphens cutting the sentence)
- Still one Todo line 162: must be erased or corrected

**Comment by bpilorget** [comment]
+ updated the github issue

**Comment by tkw1536** [comment]
I have just pushed some more edits, in particular I updated some of the screenshots and fixed a bunch of minor typos. I will do some more typo checking, but otherwise the report will have to stay as is form my side. 
Concerning paragraph 155: I think it does make sense the way it is, one just needs to read the sentence a bit more carefully.

**Comment by nthiery** [comment]
Ok, thanks. Let me know when you are done with the typo check, and I'll submit.

**Comment by tkw1536** [comment]
@nthiery You can go ahead and submit now. I have read the report over once more and found no further typos.

**Comment by nthiery** [comment]
Submitted!
Thanks @tkw1536 and @kohlhase for pushing forward interfaces for collaborative edition of mathematical documents.
Thanks @minrk and @bpilorget for the help on the report.
