### ISSUE TITLE
D4.6: Tools for collaborating on notebooks via version-control

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#95]
- **WP4:** [User Interfaces](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP4)
- **Lead Institution:** Simula Research Laboratory
- **Due:** 2016-08-31 (month 12)
- **Nature:** Other
- **Task:** T4.2 (#70)
- **Proposal**: [p.48](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)
- **[Final report](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP4/D4.6/report-final.pdf)**

Version control tools, such as Git and Mercurial, have become an integral part of open and collaborative science and software. Version control tools allow proposed changes to be reviewed ('diffing') and resolve conflicts through combination of changes ('merging'). Jupyter notebook documents are stored in text files as JSON formatted data. This makes them well suited to tracking in version control, but the JSON structure can make diffing and merging difficult.

For this deliverable, we have developed the `nbdime` tool for diffing and merging notebook documents with awareness of the structured nature of the documents, allowing a significantly improved experience over naïve text-file diffing and merging tools. `nbdime` can be integrated into the popular git version control system, maximizing impact on common developer workflows.

**Comment by martinal** [comment]
Prototyping and discussion har started at

https://github.com/jupyter/enhancement-proposals/pull/8

https://github.com/martinal/nbdime

This issue will be updated only when a major release of the new software is ready, follow the above to join the discussion and work in progress.

**Comment by bpilorget** [comment]
Is the report close to an end?

**Comment by minrk** [comment]
@bpilorget yes, currently finishing it up at #199

**Comment by bpilorget** [comment]
@minrk Perfect
The README gives info on how to write deliverables (scroll down): https://github.com/OpenDreamKit/OpenDreamKit

**Comment by minrk** [comment]
@bpilorget the D4.2 report should be complete and ready for submission now.

**Comment by nthiery** [comment]
Hi Min, Martin,

I have just been through the report and it looks good! Great job on nbdime; that's a major feature, well delivered on time!

I have made minor formating changes; see the commits.

I believe the importance of nbdime could be further highlighted in the report by a short discussion about its relevance to reproducible research, in particular in connection with the upcoming #98: fostering the use of version control leads to better tracability, etc. Could you add such? Then I'll upload the report on the EU web site.

Oh, by the way, thinking about #98 and the comment in the report about the handling of output: if a notebook is used for testing, then it's not necessarily an option to just discard the output and rerun the notebook.

Cheers,

**Comment by minrk** [comment]
@nthiery on it, will push by the end of today. I will also clarify the comments about output - it is not that output is ignored, but that different choices *may* be made about changes in generated output, depending on circumstances.

**Comment by minrk** [comment]
@nthiery added note about reproducibility, #98.

**Comment by bpilorget** [comment]
# Deliverables update

@minrk  As you know , during the interim review in Bremen, reviewers gave advice to improve deliverables. UPSud tried to follow their advice by updating D5.1 #107
The main critic is that deliverables should be static document. Therefore we went through the #107 report to check if all links were still working and also if the information contained on the links was necessary for the understanding of the report.
As a result when it was necessary annexes were added to the #107 report.

Can you please do the same for this deliverable and add annexes when need be?

**Comment by minrk** [comment]
This is delivered.

**Comment by nthiery** [comment]
Report submitted to the EU portal.
